### ISSUE TITLE
[ldd-msss_cam_mh] Sampling to ref instead of name

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#100]
In the main class we have in the xsd:
```
      <xs:element ref="img:Onboard_Compression" minOccurs="0" maxOccurs="unbounded"> </xs:element>
      <xs:element ref="img:Optical_Filter" minOccurs="0" maxOccurs="unbounded"> </xs:element>
      <xs:element name="Sampling" type="img:Sampling" minOccurs="0" maxOccurs="1"> </xs:element>
      <xs:element ref="img:Subframe" minOccurs="0" maxOccurs="1"> </xs:element>
      <xs:element ref="img:Instrument_State" minOccurs="0" maxOccurs="unbounded"> </xs:element>
```
Note that one if these is not like the others.  ;-)  Sampling should have the same ref= as the others so we can use img:Sampling ... the way it is now we have to say msss_cam_mh:Sampling, which defeats the point of reusability in the Velocity templates.

**Comment by thareUSGS** [comment]
I think we are good here. This is what Jordan and I have been trying to figure out. The new version of MSSS_CAM_MH was pushed but it was pointing to a non-existing update for IMG. Chicken before the egg situation. So I have push a MSS_CAM_MH pointing to the latest IMG on github.
https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/tree/v1010/build/release/1.E.0.0_1.0.1.0

But once we really push IMG, this line will need to update (for the line below).
https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/blob/6917a8789549f10cf7d888a6ac8cd937c425b699/build/release/1.E.0.0_1.0.1.0/PDS4_MSSS_CAM_MH_1E00_1010.xsd#L23

Anyway, using this MSS_CAM_MH schema should work for testing. Once we feel IMG is solid, then PDS EN can post, but they don't want to post another version of IMG if it is going to change again.
