### ISSUE TITLE
[ldd-img] negative motor counts

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#101]
The focus motor on mastcam-z reports negative counts (as well as positive).  So please set the data range for motor_count (child of Device_Motor_Count) to any int, not just non-negative int.

**Comment by thareUSGS** [comment]
updated, new build:
https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/6a07fcc36de17943b9c3ed1aa16e67e090cf0d28/1.14.0.0
