### ISSUE TITLE
[ldd-img] loco segments

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#103]
ahhh, we need segment_count in LOCO_Parameters (to go along with the segment list, which is there now), just like it as in ICER_Parameters.

**Comment by thareUSGS** [comment]
added. new v1810 dev. build for testing.
https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/f213c9b7ed734cfc42638c2944733fea228945e8/1.14.0.0
