### ISSUE TITLE
[ldd-img] onboard_compression_venue

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#104]
Please add to Onboard_Compression:

onboard_compression_venue - string, card 0-1
Specifies where the onboard compression was performed.

Currently the valid values (this is for heli) are Hardware, and Software.  Obviously more could be added over time.

I guess put it right after onboard_compression_quality?

**Comment by rgdeen** [comment]
Note, if you'd prefer to use processing_venue you can, but Onboard_Compression is not a subclass of Data_Processing so I thought a different keyword might be more appropriate...?

**Comment by thareUSGS** [comment]
added onboard_compression_venue in V1810
