### ISSUE TITLE
[ldd-img] Lossless as compression type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#105]
Add "Lossless" as a valid for onboard_compression_type.  For the heli I know it's lossless but don't know the specific compression type, so just generic Lossless.

**Comment by thareUSGS** [comment]
updated. although "generic" Lossless is a little odd - could be anything.

@rgdeen new build here for testing:
https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/aba304de5aa01bf848324aefbe6ab706c975bfc4/1.14.0.0

**Comment by rgdeen** [comment]
I agree, but to some extent if it's lossless it really doesn't matter by definition, since the data got perfectly reconstructed.  It matters for lossy so you know what kind of artifacts to expect.

And... thanks!
