### ISSUE TITLE
[ldd-img] decomposition_stages range

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#106]
we have an instance where decomposition_stages is 0, but range min is 1.  Please reset range min to 0.

**Comment by thareUSGS** [comment]
updated at v1810. dev. build:
https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/4dfd928c975763b1177cb9bf754e4ee716c1880d/1.14.0.0
