### ISSUE TITLE
[ldd-img] High_Dynamic_Range_Exposure cardinality

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#118]
High_Dynamic_Range_Exposure needs maxOccurs of any.  It's supposed to be an array.

**Comment by thareUSGS** [comment]
updated to unbounded. @rgdeen  new dev. build here: 
https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/7924c5b6c226309ab03895768adf0c55112b8033/1.14.0.0
