### ISSUE TITLE
[ldd-msn_surface] Commanded_Parameters is not in main class

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#120]
The Commanded_Parameters class is defined in msn_surface: but not used anywhere.  Needs to be included as a card 0-1 in the main Surface_Mission_Information class.  Presumably at the end, consistent with the placement of the other commanded classes.

**Comment by thareUSGS** [comment]
Added in v1200. @rgdeen dev. build is here:
https://github.com/pds-data-dictionaries/ldd-msn_surface/tree/master/build/development/312d31028efb9b5e874a9d1e41a312b8e72a4668/1.14.0.0
