### ISSUE TITLE
[ldd-dawn] Namespace in build artifact is incorrect

### ISSUE THREAD

**Issue by jstone-psi** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#121]
**Describe the issue identified (if applicable)**

The namespace in the xsd and sch files for the version 1.1 of the DAWN dictionary is incorrect, causing validation errors.

The namespace is declared as `http://pds.nasa.gov/pds4/dawn/v1`, and should be `http://pds.nasa.gov/pds4/mission/dawn/v1`.

This error was caused by me, when I built the latest version.

**Describe the solution you'd like**

The namespace should be changed back to `http://pds.nasa.gov/pds4/mission/dawn/v1`. I can take care of this issue.

**LDD Dictionary Version**
1.1.0.0

**PDS4 IM Version**
1.B.0.0

**Comment by jordanpadams** [comment]
@jstone-psi LDDTool must have not been run with the appropriate flag set to indicate it is a mission dictionary

**Comment by jstone-psi** [comment]
I agree, that's probably what happened. The version number in the .xsd file was incorrect, too, so I think I ran it with -m instead of -M.
