### ISSUE TITLE
[ldd-img] Tiling class

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#123]
Tile labels look like this, in INSTRUMENT_STATE_PARMS:

TILE_PRODUCT_ID=('FRF_D252T0652877892_129TDR_N0010000FHAZ02000_11_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_10_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_08_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_07_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_09_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_16_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_15_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_14_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_13_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_12_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_04_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_03_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_06_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_05_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_02_0LLJ01',
'FRF_D252T0652877892_129TDR_N0010000FHAZ02000_01_0LLJ01')
TILE_UPSAMPLE_METHOD=('NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE',
'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE', 'NONE')
TILE_NUM_BANDS=(3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
TILE_FIRST_LINE=(1921, 1921, 961, 961, 1921, 2881, 2881, 2881, 2881, 1921,
1, 1, 961, 961, 1, 1)
TILE_NUM_LINES=(960, 960, 960, 960, 960, 960, 960, 960, 960, 960, 960, 960,
960, 960, 960, 960)
TILE_FIRST_LINE_SAMPLE=(2561, 1281, 3841, 2561, 1, 3841, 2561, 1281, 1,
3841, 3841, 2561, 1281, 1, 1281, 1)
TILE_NUM_LINE_SAMPLES=(1280, 1280, 1280, 1280, 1280, 1280, 1280, 1280, 1280,
1280, 1280, 1280, 1280, 1280, 1280, 1280)
TILE_DOWNSAMPLE_X=(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
TILE_DOWNSAMPLE_Y=(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)

where the e.g. 5th element in each array all the way down represents the 5th tile.

Suggested PDS4 representation: new class in img:Imaging (and of course in Commanded_Parameters for consistency, although we won't be using that here):
```
<img:Imaging>
   ...
   <img:Tiling>
      <description>optional</>   --- not used in the 2020 use case
      <img:num_line_tiles>n</>  --- not used in the 2020 use case
      <img:num_sample_tiles>n</>  --- not used in the 2020 use case
      <img:tile_count>16</>
      <img:tile_lines>n</>    --- not used in the 2020 use case
      <img:tile_samples>n</>   --- not used in the 2020 use case
      <img:tile_type>Irregular</>     --- constant for 2020 use case
      <img:tile_venue>Onboard</>   --- constant for 2020 use case
      <img:Tile>
         <img:tile_number>1</>
         <img:tile_num_bands>3</>
         <img:tile_upsample_method>None</>
         <Internal_Reference>
            <lidvid_reference>pointer to the file a la what's in Input_Product_List</>
         </Internal_Reference>
         <img:Pixel_Averaging_Dimensions>
            <img:height_pixels>1</>
            <img:width_pixels>1</>
         </img:Pixel_Averaging_Dimensions>
         <img:Subframe>
            <img:first_line>1921</first_line>
            <img:first_sample>2561</first_sample>
            <img:lines>960</img:lines>
            <img:samples>1280</img_samples>
         </img:Subframe>
      </img:Tile>
      ... other Tile objects
   </img:Tiling>
   ...
</img:Imaging>
```

Tiling - card 0-1
Contains parameters that describe how an image was or will be broken into tiles, before reassembly into a whole. This is generally intended for cameras that break up an exposure into tiles for transmission, but can also be used to describe tiling done by a ground system (e.g. for display purposes) if needed. Tiles need not be regular nor do they need to cover the entire area, and irregular tiles may overlap. Note that the image in which this class appears is expected to contain all the tiles (i.e. not just a single tile).

tile_type - card 0-1, valids: Irregular, Regular
Defines the type of tiles. Regular tiles are the same size throughout (although the last row or column of tiles might be smaller in order to fit the image size) and should have tile_lines and tile_samples defined. Irregular tiles may have different sizes per tile, described in each Tile class.

tile_lines - int, card 0-1, range 1-any
Defines the number of lines in a regular tile. Not used for irregular tiles.

tile_samples - int, card 0-1, range 1-any
Defines the number of samples in a regular tile. Not used for irregular tiles.

num_line_tiles - int card 0-1, range 1-any
Defines the number of tiles in the line direction for a regular tile. Not used for irregular tiles.

num_sample_tiles - int card 0-1, range 1-any
Defines the number of tiles in the sample direction for a regular tile. Not used for irregular tiles.

tile_count - int, card 0-1, range 0-any
Defines the number of tiles in this set. Should be present and equal to the number of Tile objects if Tile is used; optional if Tile is not used.

tile_venue - card 0-1, valid Onboard, Ground
Specifies where the tiling was done. Generally, Onboard indicates that this image is a reassembly of tiles sent from the spacecraft, while Ground indicates a tile decomposition after processing.

Tile - card 0-any
Describes a single tile. The list of Tiles is optional for regular tiles. Contains a Subframe object which defines the size and location of the tile; this is optional for regular tiles. Similarly, contains a Pixel_Averaging_Dimensions object which defines the subsampling factor of the tile. Both the Subframe and Pixel_Averaging_Dimensions coordinates are defined in sensor coordinates, i.e. they are independent of the downsample or subframe present in the primary image. (For example, if the Pixel_Averaging_Dimensions of both the main image and the tile are 2, there is no relative zoom between them).

Note: Tile should have an xs:choice (card 0-1 between Internal_Reference, External_Reference, and Local_Inernal_Reference (just like e.g. proc:Input_Product).
Note: the Subframe and PAD children of Tile are both card 0-1
Note: if someone wants subframe or zoom relative to the main image in the future, they can define that separately. Having Subframe and PAD relative to the sensor is consistent with other usages.

tile_number - int, card 1 (required!), valid 1-any
Specifies the tile number (array index), starting at 1.

tile_upsample_method - card 0-1, alid None, Replication, Bilinear
Specifies how tiles were upsampled (if needed) to create the full image. Replication simply repeats the pixel value as many times as necessary, Bilinear is bilinear interpolation, and None means upsampling was not necessary.

tile_num_bands - int, card 0-1, valid 0-any
Specifies the number of bands for this tile.

**Comment by rgdeen** [comment]
Upon further reflection, please make the cardinality of Tiling itself (in both Imaging and Commanded_Parameters) 0-any.  The idea is, you might want a Tiling section describing the pre-tiling (as in the 2020 case), and another one describing post-tiling (typically a regular tile decomposition used for display).  That's really 0-2 and if you really want you could do that, but hey, in computer science there are only 3 numbers (0, 1, and infinity) so I'm happier with 0-any.

**Comment by thareUSGS** [comment]
implemented in (forthcoming) v1820 branch
