### ISSUE TITLE
[ldd-img_surface] Additional correlation labels

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#124]
Additional labels supporting stereo correlation processing.

Add items to img_surface:Stereo_Product_Parameters:

correlation_pixel_count - int, card 0-1, range 0-any
Contains a count of the number of pixels that successfully correlated in the image.

correlation_average_scale - float, card 0-1, range any
Contains the "average" scale factor for the correlation. In other words, given the reference image, scale it by this amount to match the target image. This scale factor is not precisely defined; it is determined in different ways by different correlation programs. The intent is to provide a "hint" for users of the correlation without requiring a full set of transform coefficients.

correlation_overlap_percentage - float, card 0-1, range 0-100
Contains the percentage of the reference image that could overlap, geometrically speaking, with the target image. It does not indicate the actual correlation percentage, but rather what might correlate ideally. This can be used to distinguish, for example, nearly perfect correlation in a small overlapping area vs. very poor correlation over the entire image - both of which could have the same correlation_pixel_count). This percentage is not precisely defined; it is an approximation intended to facilitate culling of results.

---

These all come from VICAR labels of the same names in DERIVED_IMAGE_PARMS.

**Comment by thareUSGS** [comment]
implemented at v1.2.1.0
