### ISSUE TITLE
[ldd-img_surface] Reachability labels

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#125]
Add support for two reachability products: ARM type, and GRN/GRA/GRC types.

Standard reachability use case:

```
INSTRUMENT_BAND_ID=(DRILL, GDRT, ...)
CONFIGURATION_BIT_ID=(ARM_SO_EU_WU, ARM_SO_EU_WD, ...)
(CONFIGURATION_BITS = 2)  default to 2 if not given for compat
```

```
<img_surface:Reachability>
   <img_surface:device_id>Arm</>
   <img_surface:Reach_Instruments>
      <img_surface:Reach_Instrument>
         <img_surface:instrument__id>DRILL</>
         <img_surface:band>1</>
      </>
      <img_surface:Reach_Instrument>
         <img_surface:instrument_id>GDRT</>
         <img_surface:band>2</>
      </>
      ...
   </>
   <img_surface:Configurations>
      <img_surface:Configuration>
         <img_surface:device_config>ARM_SO_EU_WU</>
         <img_surface:start_bit>15</>
         <img_surface:stop_bit>14</>
      </>
      <img_surface:Configuration>
         <img_surface:device_config>ARM_SO_EU_WD</>
         <img_surface:start_bit>13</>
         <img_surface:stop_bit>12</>
      </>
   </>
</>
```
Reachability goodness use case:
```
INSTRUMENT_LIST_ID=(DRILL, GDRT, ...)
CONFIGURATION_BIT_ID=(ARM_SO_EU_WU, ARM_SO_EU_WD, ...)
CONFIGURATION_BITS = 1
CONFIGURATION_BAND = 2
```

```
<img_surface:Reachability>
   <img_surface:device_id>Arm</>
   <img_surface:Reach_Instruments>
      <img_surface:Reach_Instrument>
         <img_surface:instrument_id>DRILL</>
      </>
      <img_surface:Reach_Instrument>
         <img_surface:instrument_id>GDRT</>
      </>
      ...
   </>
   <img_surface:Configurations>
      <img_surface:band>2</>
      <img_surface:Configuration>
         <img_surface:device_config>ARM_SO_EU_WU</>
         <img_surface:start_bit>7</>
         <img_surface:stop_bit>7</>
      </>
      <img_surface:Configuration>
         <img_surface:device_config>ARM_SO_EU_WD</>
         <img_surface:start_bit>6</>
         <img_surface:stop_bit>6</>
      </>
   </>
   ...
</>
```

The Configuration keywords would not appear if the optional 2nd band was missing.

Reachability - child of Surface_Imaging, card 0-1
This class describes Reachability products, which define whether and how a moving device (such as an arm) can contact, view, or otherwise interact with the world at each pixel of an image.

device_id - child of Reachability, card 0-1. 2020 and MSL valids: Arm
Identifies the device that this Reachability applies to, for example as "Arm".

Reach_Instruments - child of Reachability, card 0-1
Lists the instruments involved in this reachability assesment.

Reach_Instrument - child of Reach_Instruments, card 0-any
Defines a single instrument for this reachability assessment. For products where each instrument is associated with a band in the output, the "band" attribute specifies which band it is. For products where instruments are involved in the computation but not represented individually in the output, the band should be omitted.

instrument_id - child of Reach_Instrument, card 1. 2020 valids: "DRILL","GDRT","SHERLOC_WATSON","SHERLOC","PIXL", "FCS" . MSL valids: "DRILL","DRT","MAHLI","APXS","SCOOP_TIP" . Note, do not lowercase these in the template, most are acronyms.
Identifies the instrument used in reachability assessment.

band - child of Reach_Instrument, card 0-1, valid 1-any
Specifies the band number (1-based) of the band in which the data for the specified instrument resides.

Configurations - child of Reachability, card 0-1
Specifies the configurations of the device used for reachability assessment. The specific values will be device-dependent but could include e.g. shoulder in/out, elbow up/down, wrist up/down.

Configuration - child of Configurations, card 0-any
Defines a single configuration for this reachability assessment.

device_config - child of Configuration, card 1. MSL and M20 valids: "ARM_SO_EU_WU", "ARM_SO_EU_WD", "ARM_SO_ED_WU", "ARM_SO_ED_WD", "ARM_SI_EU_WU", "ARM_SI_EU_WD", "ARM_SI_ED_WU", "ARM_SI_ED_WD"
Names a specific configuration of the device.

start_bit - child of Configuration, card 0-1, valid 0-any (really don't want to limit the # of bits to anything specific...)
For Configurations that are bit-packed into a word, specifies the starting bit for this configuration. Bits are numbered starting at 0 for the least-significant bit.

stop_bit - child of Configuration, card 0-1, valid 0-any (really don't want to limit the # of bits to anything specific...)
For Configurations that are bit-packed into a word, specifies the ending bit for this configuration. Bits are numbered starting at 0 for the least-significant bit. If present, stop_bit must be equal to or less than start_bit. If absent, start_bit identifies a single bit.

**Comment by thareUSGS** [comment]
A little confusing. I think I got it implemented correctly in v1.2.1.0

So continuous integration failed on this build for 1.F.0.0. GEOM needs some updates to support 1.F.0.0 so for now I built a release for 1.D.0.0 for testing and potential official release.

https://github.com/pds-data-dictionaries/ldd-img_surface/tree/master/build/release/1.E.0.0_1.2.1.0
