### ISSUE TITLE
[ldd-img] Filter window units should not be required

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#129]
In Spatial/Image_Filter there are a number of filter window size keywords (search for "filter_window").  These are all marked as Units_of_Misc, with units required.

While technically these are in units of "pixels", there are tons of other line/sample type keywords (both as coordinates and sizes) in img: and they do not require the "pixels" unit.

So I strongly recommend making these units optional for consistency.

**Comment by thareUSGS** [comment]
Updated for v1820 for Spatial/Image_Filter attributes. 

Note I am fine with Units_of_None. As it stands, Imaging still has 4 other uses of Units_of_Misc for pixel attributes. But I'm not sure if changing those to Units_of_None will be backwards compatible without testing? For example: https://github.com/pds-data-dictionaries/ldd-img/blob/042e7cc50cecfff8a1a70e8c4559b1353245d0d7/src/PDS4_IMG_IngestLDD.xml#L1861

thus I am little hesitant to change for 4 remaining attributes.

**Comment by thareUSGS** [comment]
v1820, dev builds are here for 1.E.0.0 and 1.F.0.0 PDS IM
https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/3626cf622d8cee913e6cb1ea23e2ffa0aa399003
