### ISSUE TITLE
[ldd-img] horizon_mask_elevation

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#130]
Currently we have:
```
<img:Image_Mask>
   <img:Image_Mask_File>
      <img:horizon_mask_elevation>
```
I'm hard pressed to say why hme is a child of IMF rather than being a direct child of Image_Mask.  If you specify a horizon mask elevation you don't really need a file to specify the mask!

So can we add it *also* as a direct child of Image_Mask?  Probably have to leave it in IMF for compatibility reasons.

Note that there's also a img_surface:horizon_mask_elevation, I'm not really sure what the distinction is, but it's not worth resolving (since we can't remove anything for compatibility reasons anyway).

**Comment by thareUSGS** [comment]
added horizon_mask_elevation as direct child to Image_Mask in v1820. I assume it has not been used, but without being to search all archives I am also hesitant to remove from Image_Mask_File thus it is left in.
