### ISSUE TITLE
[ldd-geom] Add Device_Pose to Articulation_Device_Parameters

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#131]
Sorry for the late update, the M20 RP's requested this one.  Kate Crombie also has a use case for it on another mission.

The proposal is to add a new section to geom:Articulation_Device_Parameters that looks like:
```
<geom:Device_Pose>
  <name>arm_attitude_reference</>
  <geom:Device_Quaternion>
    <geom:qcos>xxx</>
    <geom:qsin1>xxx</>
    <geom:qsin2>xxx</>
    <geom:qsin3>xxx</>
  </>
  <Device_Offset>
    <geom:x_position>xxx</>
    <geom:y_position>xxx</>
    <geom:z_position>xxx</>
  </>
</>
```
Definitions:

Device_Pose - child of Articulation_Device_Parameters, cardinality 0-any (yes, I could see multiples here)
Defines the pose of this articulation device.  The name indicates what exactly is being measured and how, and disambiguates if there is more than one Device_Pose.  For example, Mars 2020 has "arm_attitude_reference", which indicates the pose of the rover that was used to calculate gravity droop of the arm.  The interpretation of the pose is mission-specific; see the mission documentation.

name - child of Device_Pose, cardinality 1.  Can reuse pds:name as desired.

Device_Quaternion - child of Device_Pose, cardinality 0-1, derived from Quaternion_Base.
Specifies the quaternion rotation used to define this pose.  Refer to mission-specific documentation for the interpretation of this given the name.

Device_Offset - child of Device_Pose, cardinality 0-1, derived from Vector_Cartesian_Position_Base.
Specifies the offset used to define this pose.  Refer to mission-specific documentation for the interpretation of this given the name.

----

Discussion:

I suspect you're not going to like referring to the mission documentation for the specific definition.  But there's no other way I know of to include this information in geom: where it belongs, where it is associated directly with the articulation device.  If we put it in a mission-specific dictionary we'd lose that association, and have to have some cross-reference mechanism that would be even more complicated.

This is mitigated by the "mission-specific nuance" definitions, implemented via the Property_Maps mechanism in the DD.  For M20, the keyword table in the documentation ends up with the generic description above followed immediately by the mission-specific nuance for the definition, so it's all there in the same place.  See the example in the M20 Peer Review:

[https://pds-imaging.jpl.nasa.gov/reviews/mars2020/mars2020_ecam/document/Mars2020_Camera_SIS_Labels_sort_pds.html]

which shows how this mechanism works in general.

**Comment by rgdeen** [comment]
any update on this one?

**Comment by jordanpadams** [comment]
added perpds-data-dictionaries/ldd-geom@e4b3686d
