### ISSUE TITLE
[ldd-img] Addition of attribute to the Optical_Filter class

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#132]
**Issue Type**
Enhancement

**Describe the issue identified (if applicable)**
For images described by the Array_3d_Image class there is currently no way to explicitly link the Optical_Filter used to the specific image plane (band) in the 3d array.  The proposed additional optional attribute to the Optical_Filter class would allow this linakage.

**Describe the solution you'd like**
Current Optical_Filter Class contains 
Optical_Filter
    filter_name
    filter_id
    filter_number
    filter_position_count
    bandwidth
    center_filter_wavelength
    comment
    Local_Internal_Reference 
    
Add: array_band_number after center_filter_wavelength

array_band_number definition: "The array_band_number is the image plane (band) in the array that corresponds to the optical filter with which the image was acquired."

**Describe alternatives you've considered**
Any other way to link specific attributes to specific planes within 3d_arrays would be good.

**LDD Dictionary Version**
For bug fixes, note the LDD dictionary version in question.

**PDS4 IM Version**
1.14

**Need-by Date**
This is for the Hayabusa2 ONC labels.  As soon as possible would be good. 

**Additional context**
Add any other context or examples products

**Comment by thareUSGS** [comment]
@katecrombie Good question. For branch v1820 I added it for now.

@acraugh @jordanpadams can you recommend a better method to address this or would this be the recommended way forward?  Branch build here:
https://github.com/pds-data-dictionaries/ldd-img/tree/v1820/build/development/812dc489d26aca8c82374e281b83453501dc40db

**Comment by jordanpadams** [comment]
@thareUSGS this seems reasonable to me, but I feel like there may be a similar paradigm implemented in the spectral dictionary that could be borrowed here. @acraugh may have some ideas?

**Comment by rgdeen** [comment]
@thareUSGS turns out we need this for M2020 too... just discovered that today.  For Mastcam filter 0, which is 3-band color, we want to specify the center wavelengths of each filter.

**Comment by thareUSGS** [comment]
Since Optical_Filter is already here adding this still make sense. I guess one could perhaps change to Array_3D_Spectrum and use the Spectral Dictionary. http://sbndev.astro.umd.edu/wiki/Quick_Introduction_to_the_Spectral_Dictionary 

closing for now with current update as described above.
