### ISSUE TITLE
[ldd-chan1] initial update needs for M3

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#133]
**Issue Type**
ENHANCEMENT

**Describe the issue identified (if applicable)**
Initial needs for PDS3 to PDS4 migration for M3 (spectral instrument on chan1)

**Describe the solution you'd like**
I think this is close to the complete list of attributes:

orbit_limb_direction
- string, 
- legal values "ascending", "descending"
- cardinality 1

spacecraft_yaw_direction
- string, 
- legal values "forward", "reverse"
- cardinality 1

[orientation model 1 -- these could be separate classes but do not necessarily need to be]

spacecraft_orientation
- 3-tuple of floats (or as regex, something like \d+\.\d+,\d+\.\d+,\d+\.\d+),
- roll/pitch/yaw in degrees from 'ideal nadir'
- cardinality 0-1 (or 1 if this is a class)

[orientation model 2]

spacecraft_orientation_rates
- 3-tuple of floats
- roll/pitch/yaw in degrees / second since epoch
- cardinality 0-1 (or 1 if this is a class)

[orientation model 3]

spacecraft_orientation_axis_vector
- 3-tuple of floats
- x/y/z unit vector wrt J2000 describing rotation direction since epoch
- cardinality 0-1 (or 1 if this is a class)

spacecraft_rotation_rate
- float
- scalar rotation rate in degrees / second since epoch
- cardinality 0-1 (or 1 if this is a class)

class: reference_orientation
- cardinality 0-1 [or 1 for orientation models 2 and 3 if we're building those as classes]

initial_spacecraft_orientation
- 3-tuple of floats
- roll/pitch/yaw in degrees from 'ideal nadir' at epoch
- cardinality 1

orientation_epoch_time
- float
- time in tdb (as seconds)
- cardinality 1

**LDD Dictionary Version**
For bug fixes, note the LDD dictionary version in question.

**PDS4 IM Version**
1.F.0.0

**Comment by thareUSGS** [comment]
in branch v1100 I am confused by the need for spacecraft_rotation_rate as a single value and ALSO the need for Spacecraft_Orientation_Rates Class as a triplet. Perhaps just one is needed?

spacecraft_rotation_rate:
https://github.com/pds-data-dictionaries/ldd-chan1/blob/896bc4a42a049a0b8994613d5b51253e33ef8096/src/PDS4_CHAN1_IngestLDD.xml#L291

Spacecraft_Orientation_Rates:
https://github.com/pds-data-dictionaries/ldd-chan1/blob/896bc4a42a049a0b8994613d5b51253e33ef8096/src/PDS4_CHAN1_IngestLDD.xml#L583

**Comment by thareUSGS** [comment]
@m-stclair almost ready for a review. I think I need to drum an example using these classes and then we can iterate.

**Comment by m-stclair** [comment]
awesome! let me know when you want me to check them out.

**Comment by m-stclair** [comment]
on the spacecraft_rotation_rate vs. Spacecraft_Orientation_Rates issue: in one of the three orientation models the clementine data providers used, they recorded rate as a scalar, with the direction given by spacecraft_orientation_axis_vector. in the other, they recorded it as a vector. it's possible that there's some more elegant way to separate (or not separate) these values; the structure I outlined in that email basically distinguishes the conventions of the three pointing models they provided. as no new pointing metadata of this type will ever be produced, strictly enforcing these conventions may not be necessary.

**Comment by thareUSGS** [comment]
@m-stclair updated branch schema a little to pull attributes out of orientation classes. Also added an example mapping that will be turned into a test. Are we close?
https://github.com/pds-data-dictionaries/ldd-chan1/blob/1.1.0.0/test/M3G20090813T001943_V01_L1B.xml_partial

**Comment by m-stclair** [comment]
@thareUSGS this looks great! even rolls in a few things from the PDS3 CH1 namespace that I had previously (acceptably but awkwardly) translated using msn, img, or proc. In the next day or two, I'll use it to make a couple test products, see if everything seems to be working cleanly, and get back to you. Thanks!

**Comment by m-stclair** [comment]
I have a couple of pattern fixes; other than that, everything works great. It seems like you automate LDD builds using a CI system I don't have access to. Do you want to me to just go ahead and submit the changes as a pull request that modifies a couple of the files in a development build, and then you can reference those to modify whatever source files you're using as necessary? Or I can just describe them -- whatever's easier.

**Comment by thareUSGS** [comment]
The trick to LDD build are to make a branch. If you don't access then you can still do a pull out just describe it. I can get a branch and CI. Either way. Thanks,
Trent

-------- Original Message --------

**Comment by m-stclair** [comment]
Ok, I'll make a branch. I assume the bot looks at https://github.com/pds-data-dictionaries/ldd-chan1/blob/1.1.0.0/src/PDS4_CHAN1_IngestLDD.xml in order to generate the .xsd. The schematron rules don't seem to be in there, though. What file do I modify to provide it with source for the .sch? 

I'll also add a stub test label for each of the three attitude models.

**Comment by thareUSGS** [comment]
Michael,
  For whatever reason the PDS uses an even more abstracted version of the schema, which is what gets built by the PDS's LDDtool. Why - not sure. But when I took over the schemas from folks here,  it took me a little bit to realize it. It was very confusing at first needing to build the schemas instead of just editing them...
http://sbndev.astro.umd.edu/wiki/Creating_the_Ingest_LDD_Dictionary_Input_File

BTW, this is a thing in XML (not just made up by the PDS).

So, yes the only file needing changing (readme aside), is PDS4_CHAN1_IngestLDD.xml

It is fine to offer schema updates, I can back-port them to LDDs.

-Trent








________________________________

**Comment by m-stclair** [comment]
XML is complicated!

Ok, now I see the line in PDS4_CHAN1_IngestLDD.xml that generates the
schematron rule of concern. I will go ahead and submit a pull request with
these minor changes later today. Thanks!

**Comment by m-stclair** [comment]
and, unfortunately, it looks like I don't have permission to submit pull
requests to this repo. can you add me as a collaborator?

**Comment by m-stclair** [comment]
great, thank you, submitted.

**Comment by thareUSGS** [comment]
push release to EN node.
