### ISSUE TITLE
not having luck retrofitting MESSENGER for CI

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#134]
https://github.com/pds-data-dictionaries/ldd-messenger/tree/v1101

**Comment by thareUSGS** [comment]
hmm - maybe it is working, but build looks like it failed. I will check it out in a bit.

**Comment by jordanpadams** [comment]
@thareUSGS the IngestLDD needs to be renamed to something like `***IngestLDD.xml`. I would recommend something similar to all the other repos, e.g. `PDS4_MESS_IngestLDD.xml`

**Comment by thareUSGS** [comment]
Bingo - I didn't catch that. thanks! I will give it a shot.

**Comment by thareUSGS** [comment]
C.I. working and added review requirement to branches.
