### ISSUE TITLE
[ldd-cart] need some updates for IM 1E00 and 1F00

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#138]
**Issue Type**
BUG

**Describe the issue identified (if applicable)**
Building causes a few errors I **am not sure how to fix.**

```
 ERROR Class:  - At least one value for pds:local_reference_type or pds:reference_type must be defined for geom:Body_Identification_Base/pds:Internal_Reference.
 ERROR Class:  - At least one value for pds:local_reference_type or pds:reference_type must be defined for geom:Frame_Identification_Base/pds:Internal_Reference.
 ERROR Attribute: <coordinate_space_frame_type> - The 'type' attribute must have at least one permissible value.

```
https://github.com/pds-data-dictionaries/ldd-cart/runs/1455829248#step:5:128

**LDD Dictionary Version**
v1950

**PDS4 IM Version**
1E00 and 1F00

**Need-by Date**
Dec, 5, 2020 for new release dealine.

**Comment by jordanpadams** [comment]
@thareUSGS https://pds-data-dictionaries.github.io/development/ldd-how-to.html#specify-enumerated-values-for-attributes-within-inherited-classes

**Comment by jordanpadams** [comment]
@thareUSGS also, this may actually be something that needs to be fixed in the GEOM dictionary. I believe Mitch was looking into it, but not sure where that is at.

**Comment by thareUSGS** [comment]
@mit3ch do you have any comments for <coordinate_space_frame_type> (see above). thanks

**Comment by thareUSGS** [comment]
CART is now building. Need to add CI (github actions) to create a release (although GEOM is also built here which can be removed from built directories. That might mean a manual release?
