### ISSUE TITLE
[ldd-img] Responsivity units

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#139]
Recently we added Spectral_Radiance as units: W/m**2/sr/nm.

However, the img:responsivity_r/g/b/pan attributes are actually in terms of what we call responsivity, or perhaps a good name is "Spectral_Responsivity"?  This is a function of exposure time, and converts the DNs from the sensor to spectral_radiance units.  As such, the unit is really Spectral_Responsivity/(DN/sec), or W/m**2/sr/nm/(DN/sec).

Note that I made up the "Spectral_Responsivity" name; I don't know what this is called generally or if in fact there is a generic name for it.  It's disturbing we can't just put in arbitrary combinations of SI units.  DN is not really an SI unit but it is legal as Units_of_Misc currently.

So is it possible to get this in for use with Mars2020?  It might require a pds core point build, or some such.  If so, the responsivity_r/g/b/pan (but not responsivity_factor*) should be changed to use this unit.  But only if.  The alternative is to just put the unit in a <comment> field.

Note that we need a decision on this ASAP as the RDR Peer Review is in a couple of weeks, and we need to know which way to go on the labels.  Thanks.

**Comment by thareUSGS** [comment]
Jira won't let me in right now to check if similar issue has been addressed. I know any approved SI unit is allowed just not sure on more custom. I am not an unit expert here though - maybe @acraugh or @mit3ch has some advice? If anything, I would think "W/m**2/sr/nm/(DN/sec)", might be allowed under [Miscellaneous_Units](http://sbndev.astro.umd.edu/wiki/Unit_Classes_Standard_Values#Miscellaneous_Units), but I do think it might need a quick SCR to get it approved. Lock-in to pass new issues is Jan 17 for the next build cycle. I will also ask the DDWG (this Thursday) if we don't have a path forward before then.

**Comment by myche** [comment]
Do we need an SCR for tomorrow's DDWG or will we find out then if we actually need such an SCR?

**Comment by mit3ch** [comment]
Hi Trent,

I’m not sure this is the definitive answer. I believe you will want to submit an SCR (using the short form). CCB-251 is an example of a request to add a unit of measure.

BTW, I don’t know which browser you use. While Firefox prohibits access to a site with a flawed or expired certificate, Chrome’s “Advanced” option gives you the option of entering the site anyway.


Mitch

**Comment by rgdeen** [comment]
If the next build is Jan 17, can we use it for 2020?  PR is going out in a couple weeks.  I guess as long as we have a decision by next week we can do it "on spec" for the PR?

**Comment by thareUSGS** [comment]
I will try to capture this in a new SCR.  BTW, the Jira site is back up.

**Comment by thareUSGS** [comment]
#rgdeen the original text is a little confusing (which term means what). I have a new SCR for the DDWG but it is stated as. Does this make sense and meet your needs.

**Problem Statement**: Mars2020 has the need to define a new unit for "spectral responsivity", specifically 'W/m**2/sr/nm/(DN/sec)'.

**Requested Changes**: Add to 'Miscellaneous_Units' the value of 'W/m**2/sr/nm/(DN/sec)' -- also called 'spectral responsivity'.

**Description**: spectral radiance is generally represented using 'W/m**2/sr/nm'. Mars2020 however stores pixel values in terms of "spectral responsivity". This is a function of exposure time, and converts the DNs from the sensor to spectral_responsivity units. Thus they are calling this:

Spectral Responsivity = 'Spectral_Radiance/(DN/sec)' or 'W/m**2/sr/nm/(DN/sec)'

**Comment by rgdeen** [comment]
Correction to Description:

Description: spectral radiance is represented by M2020 using 'W/m**2/sr/nm'.  The calibration parameters however are also a function of exposure time, thus they are expressed as responsivity = Spectral_Radiance/(DN/sec) meaning that spectral_radiance = DN * responsivity / exposure_time.  The addition of spectral_responsivity allows these calibration parameters to be stored in the label with appropriate unit designations.


Note that there are a number of options for spectral_radiance with different units... so in theory there could be a bunch of responsivity units too.  But for all recent Mars missions all we need is the one, W/m**2/sr/nm/(DN/sec) so I'm okay just adding that, and others can add more if needed.  Seems kind of silly to define them all at this point.

**Comment by thareUSGS** [comment]
@rgdeen To tie this one up for a vote, can you post an example label (section) using this value? I think that will help clear it up for others.

**Comment by thareUSGS** [comment]
W/m**2/sr/nm/(DN/s) was approved by DDWG and off to CCB review. Timing is another thing. As this is in the main IM (information model), we might not see it available until IM 1.G.0.0 is released.

**Comment by thareUSGS** [comment]
CCB passed this also. This option will be available in PDS Information Model v1.G.0.0
