### ISSUE TITLE
[ldd-geom] enumeration set to true

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#140]
**Issue Type**
BUG (maybe?)

**Describe the issue identified (if applicable)**
I am thinking this attribute needs to have enumeration = true
https://github.com/pds-data-dictionaries/ldd-geom/blob/808665c280eec296bc5fef57a0c3a4ca11870891/src/PDS4_GEOM_IngestLDD.xml#L2578

**LDD Dictionary Version**
v1.9.0.0

**PDS4 IM Version**
1.F.0.0

**Comment by jordanpadams** [comment]
@thareUSGS looks like that is a bug LDDTool should have caught.
