### ISSUE TITLE
[ldd-disp] Schematron rules are mutually contradictory!  Cannot validate.

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#143]
In PDS4_DISP_1E00_1500.sch we have:

```
  <sch:pattern>
    <sch:rule context="disp:Display_Settings/pds:Local_Internal_Reference">
      <sch:assert test="pds:local_reference_type = 'display_to_data_object'
        ">
        For Local_Internal_Reference in disp:Display_Settings, local_reference_type must equal 'display_to_data_object'.
        </sch:assert>
    </sch:rule>
  </sch:pattern>
```
but also later:
```
  <sch:pattern>
    <sch:rule context="disp:Display_Settings/pds:Local_Internal_Reference">
      <sch:assert test="pds:local_identifier_reference = //pds:*/pds:*/(pds:Array|pds:Array_2D|pds:Array_2D_Image|pds:Array_2D_Map|pds:Array_2D_Spectrum|pds:Array_3D|pds:Array_3D_Image|pds:Array_3D_Movie|pds:Array_3D_Spectrum)/pds:local_identifier">
        Display Dictionary: In the pds:Local_Internal_Reference class, the value of the pds:local_identifier_reference must match the value of the pds:local_identifer of an Array class or sub-class within the File_Area.</sch:assert>
      <sch:assert test="pds:local_reference_type = ('display_settings_to_array')">
        Display_Dictionary: In the pds:Local_Internal_Reference class, the value of the pds:local_reference_type must be 'display_settings_to_array'.</sch:assert>
    </sch:rule>
  </sch:pattern>
```
So one rule says it must be "display_to_data_object" and the other says it must be "display_settings_to_array".  This make it impossible to validate using either value!

I don't really care which one is used (although our SW is currently set up for "display_to_data_object"), but please pick one and use it consistently.

**Comment by thareUSGS** [comment]
I knew back-porting this was going to take a couple tries. But I think we are going to need to change back to "display_settings_to_array". 

The odd part is that the second section shown above is not based on anything I wrote in the [ingest LDD ](https://github.com/pds-data-dictionaries/ldd-disp/blob/master/src/PDS4_DISP_IngestLDD.xml) version (pre-building with LDDtool). **I am actually not sure how that rule is getting injected into the DISP schema**. And to get this actually built with LDDtools, I must include this rule (which results in basically getting it duplicated in the output schema...). 

Here is a dev. build to hopefully test against:
https://github.com/pds-data-dictionaries/ldd-disp/tree/v1500_release/build/development/ddf2364109768dcf51da8c553a0b86d8c8f8cebf

**Comment by jordanpadams** [comment]
@thareUSGS please reach out to @jshughes with the oddity you are seeing there is a good chance this is because the DISP was ingested into the common years ago and their may be some remnants laying around the Steve needs to cleanup.

**Comment by thareUSGS** [comment]
@jshughes If you look at the top section above (that is what I added) to pass LDDbuild. But for the injected section (as Jordan pointed out) also has this section. I'm not sure if I need this duplicated in the ingest LDD. This line specifically:
`      <sch:assert test="pds:local_identifier_reference = //pds:*/pds:*/(pds:Array|pds:Array_2D|pds:Array_2D_Image|pds:Array_2D_Map|pds:Array_2D_Spectrum|pds:Array_3D|pds:Array_3D_Image|pds:Array_3D_Movie|pds:Array_3D_Spectrum)/pds:local_identifier">
        Display Dictionary: In the pds:Local_Internal_Reference class, the value of the pds:local_identifier_reference must match the value of the pds:local_identifer of an Array class or sub-class within the File_Area.</sch:assert>`

**Comment by thareUSGS** [comment]
@jshughes okay I get it. Looking at this [example](https://github.com/USGS-Astrogeology/GDAL_scripts/wiki/Raster-introduction-for-PDS4-conversion-using-GDAL) I can see the name "image" is for <local_identifier_reference> under Display

```
    <Discipline_Area>
      <disp:Display_Settings>
        <Local_Internal_Reference>
          <local_identifier_reference>image</local_identifier_reference>
          <local_reference_type>display_settings_to_array</local_reference_type>
        </Local_Internal_Reference>
```
and in <local_identifier> under <Array_*>
```
    <Array_3D_Image>
      <local_identifier>image</local_identifier>
      <offset unit="byte">0</offset>
      <axes>3</axes>
```

**Comment by jshughes** [comment]
Good call Jordan, there are three DISP rule assertions in the IM database. They will be removed from the IM database.

1) The rule assertion with the error message,  "In the pds:Local_Internal_Reference class, the value of the pds:local_identifier_reference  ... " was written to enforce referential integrity. In other words, the <local_identifier_reference> must have a matching <local_identifer>. Since the data types of these attributes have been changed to xsd:IDREF and xsd:ID respectively, this rule might not be needed. I will ping Ron Joyner. He wrote the rule and there may be an issue with the use of external name spaces.

2) Whether "display_to_data_object" or "display_settings_to_array" is a decision to be made by the DISP LDD stewards.

3) The third rule assertion might need to be added to the LDD. I believe that Elizabeth wrote it. Given the latest .xsd file, it seems that the <Display_Direction> is not required to be nested within Display_Settings. 

		assert: if (disp:Display_Direction) then (disp:Display_Settings/disp:Display_Direction) else true()
		
				Display Dictionary: If the Display_Direction class is in the label, it 
				must be contained in a Display_Settings class.

--- Rule Assertions found in the IM database.

	http://pds.nasa.gov/infomodel/pds#.disp:Display_Settings/pds:Local_Internal_Reference.100002511
	disp:Display_Settings/pds:Local_Internal_Reference
	
		1) assert: pds:local_identifier_reference =
			//pds:*/pds:*/(pds:Array|pds:Array_2D|pds:Array_2D_Image|pds:Array_2D_Map|pd
			s:Array_2D_Spectrum|pds:Array_3D|pds:Array_3D_Image|pds:Array_3D_Movie|pds:A
			rray_3D_Spectrum)/pds:local_identifier

				Display Dictionary: In the pds:Local_Internal_Reference class, the value
				of the pds:local_identifier_reference must match the value of the
				pds:local_identifer of an Array class or sub-class within the File_Area.

		2) assert: pds:local_reference_type = ('display_settings_to_array')

				Display_Dictionary: In the pds:Local_Internal_Reference class, the value
				of the pds:local_reference_type must be 'display_settings_to_array'.                  
				
				
	http://pds.nasa.gov/infomodel/pds#.disp:Discipline_Area.100002510				
	
		3) assert: if (disp:Display_Direction) then (disp:Display_Settings/disp:Display_Direction) else true()
		
				Display Dictionary: If the Display_Direction class is in the label, it
				must be contained in a Display_Settings class.

**Comment by jordanpadams** [comment]
@thareUSGS have you already figured out a workaround? or should we implement this in 1F00 before the release?

**Comment by thareUSGS** [comment]
One rule section is simply duplicated and I don't think a duplicated rules hurts anything? But also we can easily manually remove that section from the release (before posting). Just one file per version to edit.

**Comment by jordanpadams** [comment]
> But also we can easily manually remove that section from the release (before posting).

Copy. But we would really prefer to never touch the output files from LDDTool. @jshughes can we get this into your LDDTool point build as well?

**Comment by jordanpadams** [comment]
@thareUSGS curious about this ticket. when reviewing the ldd-disp PR for this build, can you verify if this is still a problem?

**Comment by thareUSGS** [comment]
@jordanpadams  and @jshughes I think we just needed the rule assertions removed? Not sure where this landed...?

**Comment by jordanpadams** [comment]
@thareUSGS copy. created a sister ticket here: https://github.com/NASA-PDS/pds4-information-model/issues/351

**Comment by acraugh** [comment]
@thareUSGS and @jordanpadams, it looks like this issue (#143) should have been closed quite some time ago and just got missed because of the duplication...
