### ISSUE TITLE
[ldd-geom] new valid needed for coordinate_space_frame_type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#144]
We need an additional valid for geom:coordinate_space_frame_type.  This is not unexpected, valids here will need to be added frequently (it's one the primary reason I'm not happy with checking here, but it is what it is).

MCZ_CAL_PRIMARY - Frame centered on the Primary Mastcam-Z calibration target

**Comment by jordanpadams** [comment]
fixed per pds-data-dictionaries/ldd-geom@e4b3686d
