### ISSUE TITLE
When the build process occurs CSV files fail to escape double quotes.

### ISSUE THREAD

**Issue by seakintruth** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#147]
Many CSV files in many of the LLD repos fail to parse as double quotes are not escaped

An example of how to escape is listed in [RFC 4180.](https://www.ietf.org/rfc/rfc4180.txt)

> If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:
       "aaa","b""bb","ccc"

An example of this issue is line 14 in file [lld-chan1: PDS4_CHAN1_1E00_1110](https://github.com/pds-data-dictionaries/ldd-chan1/blob/master/build/release/1.E.0.0_1.1.1.0/PDS4_CHAN1_1E00_1110.csv)

Current Build Description:
" The spacecraft_yaw_direction attribute provides the spacecraft yaw (look) mode. valids: "Forward", "Reverse" "

Should Be:
" The spacecraft_yaw_direction attribute provides the spacecraft yaw (look) mode. valids: ""Forward"", ""Reverse"" "

**Comment by jordanpadams** [comment]
thanks @seakintruth . this is a bug in our LDDTool. thanks for testing out some of these other output formats. we will add this to our list of bug formats, and you should see a change with v1.16.0.0 of the PDS4 Information Model (April-June timeframe). if you need to this change included now. please let us know, and we can push out a point build of LDDTool to fix this.

**Comment by jordanpadams** [comment]
@seakintruth we were able to fix this bug per NASA-PDS/pds4-information-model#280 . you could try using the latest LDDTool dev version if you would like to test it out:

https://github.com/NASA-PDS/pds4-information-model/releases/tag/13.0.0-SNAPSHOT
