### ISSUE TITLE
[ldd-img] illumination mode

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#148]
Please add img:illumination_mode as an optional child of img:lllumination.  After the name, before the LED class.  String, card 0-1.

Definition:

illumination_mode describes what mode the illumination device is in.  It could be used to indicate a common name for a particular configuration of activated lights, where there are many such devices.

----

The use case is the latter, it says what the general configuration of the PIXL MCC lights are, a simplification of the detailed LED states.  I don't think we need validated values here but just in case the current values are:

Red
Green
Blue
White
UV
SLI-A Dense
SLI-B Sparse
Other
Off

Thanks...

-Bob

**Comment by thareUSGS** [comment]
Added to IMG v1.8.3.0. branch. Development build available for [1.E.0.0 and 1.F.0.0](https://github.com/pds-data-dictionaries/ldd-img/tree/v1830/build/development/788cbcdc47bcd9b56c38b0aacfb42b8d7f490094)
