### ISSUE TITLE
[ldd-img] additional valid for shutter_subtraction_mode

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#150]
Please add "Always" and "None" as additional valids for img:shutter_subtraction_mode.  Goes with the existing Conditional and True values.

Need for M2020.

**Comment by thareUSGS** [comment]
@rgdeen -- updating branch 1.8.40 - 

definition check
None : Shutter subtraction was not used 
Always : ?

Always seems like it should just be True. Can you help here.

**Comment by rgdeen** [comment]
I think this is a subtle distinction between command and result.  From a command point of view, you have conditional, always, none, and maybe others in the future.  That's not necessarily the same as a result where it either was or wasn't done.  So there is a subtle distinction there.  We (intentionally) don't restrict command or result to a subset of values though.

**Comment by rgdeen** [comment]
and honestly I'm not sure that "always" doesn't show up in the result... but anyway that's the rationale.

**Comment by thareUSGS** [comment]
@rgdeen just a ping to review options and requests here.

**Comment by rgdeen** [comment]
if you want a definition: "Always" indicates the subtraction is, or will be, on regardless of other conditions.

But I'm fine if you want to de-enumerate it too.

**Comment by thareUSGS** [comment]
closing with dev builds https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/017a6b604011e5afb26c07169c765069f03e1fc1
