### ISSUE TITLE
[ldd-msn_surface] Add new value option for 'msn_surface:transport_protocol'

### ISSUE THREAD

**Issue by nttoole** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#152]
**Issue Type**
ENHANCEMENT

**Describe the issue identified (if applicable)**
Running vtool on an M20 PDS4 label, it logged an error for the attached product (remove .txt exten).
[ELM_0000_0666952960_800FDR_N0000087LVS_04000_0000LUJ02.xml.txt](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/files/6225113/ELM_0000_0666952960_800FDR_N0000087LVS_04000_0000LUJ02.xml.txt)

Error:  `The attribute msn_surface:transport_protocol must be equal to one of the following values 'Data Product', 'SFDU'.`

Relevant section of the XML Label:
```
<msn_surface:Telemetry>
<msn_surface:telemetry_source_name>IMAGE_VcemgrScidata_0667049271-50909-1_DMS_POST_MRL_RAW_IMAGE_APID_7.png</msn_surface:telemetry_source_name>
<msn_surface:transport_protocol>TEAM-GENERATED IMAGE</msn_surface:transport_protocol>
<msn_surface:telemetry_source_checksum>14411869</msn_surface:telemetry_source_checksum>
</msn_surface:Telemetry>
```

**Describe the solution you'd like**
Add a new legal value for 'msn_surface:transport_protocol'
Value: Team-generated Image
Description:  Image delivered from instrument team with no indication of what the actual protocol was.
A clear and concise description of what you want to happen. Where possible please include details like:

* where you would like the new class attribute to reside in the repo
Legal for for <msn_surface:Telemetry>:<msn_surface:transport_protocol>

**Describe alternatives you've considered**
N/A

**LDD Dictionary Version**
https://pds.nasa.gov/pds4/msn_surface/v1/PDS4_MSN_SURFACE_1F00_1200.xsd

**PDS4 IM Version**
For new feature requests, please note the PDS4 Information Model version you would like the new feature implemented against.

**Need-by Date**
Related to upcoming M20 PDS delivery, so relatively soon.  4/14/21?

**Additional context**
N/A

**Comment by thareUSGS** [comment]
@nttoole As you stated the current following values are 'Data Product', 'SFDU'. Your new tag being all caps `TEAM-GENERATED IMAGE` is a little out of place. Is there a chance that can be more inline in PDS4? say `Team-generated Image`?

**Comment by nttoole** [comment]
@thareUSGS Certainly! We can capitalize the value in the templates on our end.  I'll update the original request above.

**Comment by thareUSGS** [comment]
Added to v1210 branch - waiting for github actions to build: https://github.com/pds-data-dictionaries/ldd-msn_surface/blob/6a7004ffdd298c1764e7fee376b6a759fde7290b/src/PDS4_MSN_SURFACE_IngestLDD.xml#L334

**Comment by thareUSGS** [comment]
dev builds pushed to master last week https://github.com/pds-data-dictionaries/ldd-msn_surface/tree/master/build/development/6a7004ffdd298c1764e7fee376b6a759fde7290b .  

Will get picked up for next PDS-wide release. closing.
