### ISSUE TITLE
[ldd-msn,ldd-msn_surface] Extend the legal regex for all SCLK related values to 9 decimal places

### ISSUE THREAD

**Issue by nttoole** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#153]
**Issue Type**
Enhancement 

**Describe the issue identified (if applicable)**
Please extend the regex for all msn and msn_surface SCLK fields to include 9 decimal places in the fractional component.

**Describe the solution you'd like**
Originally, this started off as a needed update for a single field under M20:
https://github.com/pds-data-dictionaries/ldd-m2020/issues/10
..but it seems this approach should be generalized for all SCLK fields captured under msn and msn_surface namespaces.

**Describe alternatives you've considered**
Leaving as-is is possible, tho not ideal as it will introduce inconsistency.  
The original 6-figures was a recommended guess.

**LDD Dictionary Version**
msn: 1.E.0.0
msn_surface: 1.D.0.0_1.2.0.0
For bug fixes, note the LDD dictionary version in question.

**PDS4 IM Version**
UNK

**Need-by Date**
Request is made for consistency, so there is no hard need by date.

**Additional context**
@rgdeen may have some more information on which fields should be included.

**Comment by nttoole** [comment]
Well since this request is to help with consistency, we would be ok with updating it for 10 as well

**Comment by thareUSGS** [comment]
@nttoole @rgdeen Well for better or worse when msn or msn_surface were created they don't have a forced "pattern" for SCLK attributes...

Should we force a pattern or keep this open (and leave alone) for both msn and msn_surface?

Mars2020 pattern: https://github.com/pds-data-dictionaries/ldd-m2020/blob/e06cbb5220954cfbb9c457f2b37c38da26123810/src/PDS4_MARS2020_IngestLDD.xml#L294

msn - a string less than 256...
https://github.com/pds-data-dictionaries/ldd-msn/blob/3d1de7f792558de53bcb562bb6abf37f453b5f34/src/PDS4_MSN_IngestLDD.xml#L145

msn_surface uses any string too. e.g.
https://github.com/pds-data-dictionaries/ldd-msn_surface/blob/8e44b7a7f4c8b9078010611acd08bcbca9ac94cc/src/PDS4_MSN_SURFACE_IngestLDD.xml#L364

**Comment by sslavney** [comment]
Different missions have different rules for SCLK. We should not force a pattern. But allowing up to 10 digits after the decimal is not going to disrupt anything.

**Comment by rgdeen** [comment]
I have no issue with 10.  I’d rather be consistent if someone else needs 10.   It’s not like it’s a problem to have too much precision in pretty much any context I can think of... and people can always add a mission specific constraint for less if they need it.   You can’t add a mission specific constraint for more.

-Bob

**Comment by rgdeen** [comment]
I’m not in general in favor of being too restrictive so I’m happy keeping it general unless someone really feels strongly otherwise.

-Bob

**Comment by nttoole** [comment]
Agreed, in this instance, the more open, the better.

**Comment by thareUSGS** [comment]
@nttoole @rgdeen @sslavney Okay so I plan on closing this ticket with **no** updates to msn or msn_surface. 

I'm sorry I brought up 10 for a length (I think it just confused things). But I will assume Mars2020 dictionary will remain at 9 (again msn and msn_surface will not have any length restriction).
