### ISSUE TITLE
[ldd-img_surface] Need new valid for geometry_projection_type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#155]
Need a new valid value for geometry_projection type.  Currently it supports Raw, Linearized, and None.  New value:

Trapezoid: Trapezoidal reprojection, used to compensate for an off-axis camera such as the Mars 2020 PIXL MCC.

Yes, in the multimission dictionaries.  This type of correction could be used on other instruments too that look off-axis.

**Comment by thareUSGS** [comment]
When adding Trapezoid, I notice the is no "None". I assume "Raw" is meant to be used for "None" or do you want me to add "None" as an option?

`RAW -  Indicates the image has not been reprojected. The original camera model is still in use.`

**Comment by thareUSGS** [comment]
Updated one Trapezoid (did not include "None"). In this branch for testing:
https://github.com/pds-data-dictionaries/ldd-img_surface/tree/release/1.16.0.0

or dev builds: https://github.com/pds-data-dictionaries/ldd-img_surface/tree/release/1.16.0.0/build/development/e3f552c8ea79c65e4752447372324db682631ff5

**Comment by rgdeen** [comment]
We need raw.  None is generally good to have on general principle although in this case that’s pretty much synonymous with raw.

Which is a long winded way of saying I don’t have a strong opinion here. ;-)

-Bob

Sent from my iPhone

On May 10, 2021, at 10:04 AM, Trent Hare ***@***.******@***.***>> wrote:


@rdgeen When adding Trapezoid, I notice the is no "None". I assume "Raw" is meant to be used for "None" or do you want me to add "None" as an option?

RAW - Indicates the image has not been reprojected. The original camera model is still in use.

**Comment by thareUSGS** [comment]
leaving None out for now. We can add later if needed. closing.
