### ISSUE TITLE
[ldd-img] definition tweak for tile_num_bands

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#156]
We should augment the definition of tile_num_bands to better explain usage.

Current:

Specifies the number of bands for this tile.

Proposed:

Specified the number of bands for this tile.  The tile number of bands may not match the number of bands for the overall image, in which case it reflects the number of bands the original tile had before assembly, or the number of bands the tile should have after disassembly.

**Comment by thareUSGS** [comment]
update in v1.8.50.
