### ISSUE TITLE
[ldd-img] new compression type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#159]
Please add new valid to img:onboard_compression_type

"H.264 Frame" - Frame extracted from a video encoded using the H.264 codec

The "Frame" part distinguishes it from the overall video.  You could also add H.264 generally if you want, although it's unclear how that would be used in the context of a single-frame product so I wouldn't right now.

**Comment by thareUSGS** [comment]
added enumeration in v1.8.5.0
