### ISSUE TITLE
[ldd-img] Add internal/external reference to img:Video

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#162]
The img:Video class needs an Internal_Reference/External_Reference pair (the usual pattern, allowing either one or neither but not both, see e.g. Brightness_Correction_File).

The allowed reference type should be "video_frame_to_video".

**Comment by thareUSGS** [comment]
Updated in v1.8.5.0. 

Note Brightness_Correction_File class was not a good example, but Data_Processing_File class was (as used in Brightness_Correction_File). Just pointing out a minor distinction.
