### ISSUE TITLE
[ldd-img] Aperture

### ISSUE THREAD

**Issue by KalofXeno** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#163]
**Issue Type:** ENHANCEMENT

Add a new attribute under img:Optical_Properties:

```xml
<img:Optical_Properties>
  <aperture>8.91886</aperture>
</img:Optical_Properties>
```

**Definitions:**

Aperture 
Defines opening through which light passes in an optical instrument. 
From [EXIF](https://exiftool.org/TagNames/EXIF.html), aperture value is noted being displayed as an F number, but stored as an APEX value.

**Additional context**
Example: sqrt(2^(8918863/1000000)) = f/22 = aperture

children: none, unless a description for APEX value and or aperture stop value is warranted.

**Comment by thareUSGS** [comment]
@KalofXeno Question. How is this different from f_number: https://github.com/pds-data-dictionaries/ldd-img/blob/7e518c226d07c138c5b8be23c87bdfdc6d8d806e/src/PDS4_IMG_IngestLDD.xml#L1626

If different, can you recommend better definition for f_number to distinguish it from aperture.

**Comment by KalofXeno** [comment]
@thareUSGS After talking with PI of "mission" I think we are good with f_number, exposure_duration, and focal_length. Aperture may not be necessary after all. Perhaps I was concentrating on *effective aperture* and how it is inversely proportional to f_number (f_number = focal_length / effective aperture). 

This issue can probably be closed.

**Comment by thareUSGS** [comment]
I will close for now, but if you have second thoughts we can reopen. Thanks for digging into it.
