### ISSUE TITLE
[ldd-img] Documentation fix for frame_index

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#165]
The writeup for img:frame_index discusses its use in the Video class but not the Focus_Stack class.

Current wording:

The frame_index attribute specifies the sequence number of this frame in the context of the entire video, i.e. the first frame of the video would be index 1, up to frame_count.

Revised wording:

When in a Video class, the frame_index attribute specifies the sequence number of this frame in the context of the entire video, i.e. the first frame of the video would be index 1, up to frame_count.

When in a Focus_Stack class, the frame_index attribute specifies the index of the first frame used to make up the focus stack.

**Comment by thareUSGS** [comment]
update in the definition in branch v1860_JAXA  dev builds available (not merged to main) until they sign off on #164 

https://github.com/pds-data-dictionaries/ldd-img/tree/v1860_JAXA/

**Comment by thareUSGS** [comment]
As a follow-up for this attribute, M2020 requested frame_index to allow negative integers. Apply to v1860_release.
