### ISSUE TITLE
[ldd-msss_cam_mh] Add new zstack attributes

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#166]
Four ZSTACK-related attributes got missed.  Please add them, probably between analog_offset and Detector.  All are cardinality 0-1 of course.

start_camera_product_Id - The camera_product_id of the first frame used to make a focus merge (Zstack) product.

exposure_count - The number of exposures that went in to making the focus merge (Zstack) product.

focus_merge_blending_flag - Indicates whether intra-stack image blending has been performed during a focus merge (Zstack) operation.

focus_merge_registration_flag - Indicates whether intra-stack image resgistration has been performed during a focus merge operation.

---

The astute reader may note similarities to the img:Focus_Merge class... but per design, this Mini-header DD contains all items in the mini-header with a minimum of interpretation, while most items are duplicated elsewhere in the label in a more multimission, reusable context.

**Comment by thareUSGS** [comment]
@rgdeen dev build with updates - please check it out.
https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/tree/main/build
