### ISSUE TITLE
[ldd-msss_cam_mh] Change top-level class name

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#17]
The top level class name is "Surface_Mission_Information".... doh!  Cut-and-paste disease.  It should be "MSSS_Camera_Mini_Header".

Also a number of xs:element entries are needed in img: so we can find the cross-dictionary elements.

Much as I hate to say it, in img:, Companding is a child of Sampling.  So we should do the same here... refer to img:Sampling rather than img:Companding (although likely it'll be nothing but an img:Companding child inside img:Sampling).

**Comment by rgdeen** [comment]
@thareUSGS also please include the new img:Optical_Properties as a child in the MSSS dictionary (which also means exposing it as a xs:element in img as well)

**Comment by thareUSGS** [comment]
> Also a number of xs:element entries are needed in img: so we can find the cross-dictionary elements.

I don't know what this means. Do we need to do anything here for MSSS_Camera_Mini_Header

**Comment by rgdeen** [comment]
@thareUSGS well if the cross-dictionary use gets approved, then all that's needed in this dictionary is to refer to the img: items (which I think is already in place).  It's really a to-do for the img: dictionary to add the xs:element entries that allow cross-dictionary usage.

The list is:

img:Sampling
img:Detector
img:Exposure
img:Focus
img:Onboard_Compression
img:Optical_Filter
img:Subframe
img:Instrument_State 

Note that img:Companding is not needed because img:Sampling is on the list.  Once a top level item is there, it apparently makes all children available too (at least given the geom coord reference example).

**Comment by thareUSGS** [comment]
I get it. Yes those were updated to use IMG and just pulled in via https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/pull/10
