### ISSUE TITLE
[ldd-img] data type for img:filter_position_count

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#170]
We are seeing a number of instances in zcam where img:filter_position_count (in Optical_Filter) is negative.  We do not know why that is, but there are enough of them it's not an anomaly.

So the data type for this should be changed from nonnegative int to just int.

Needed for m20 validation.

**Comment by thareUSGS** [comment]
Updated in v1860_release.
