### ISSUE TITLE
[ldd-img] exposure_duration_count needs to be a float

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#171]
For the helicopter, they get fractional values for exposure counts (which are NOT seconds - they're still engineering units, thus "count" - the value is converted to seconds also for exposure_duration).  But the data type for exposure_duration_count is integer.  We need to expand it to be float.

**Comment by thareUSGS** [comment]
updated to ASCII_Real to v1860_release  (for Mars2020 helicopter)
