### ISSUE TITLE
[ldd-img] Addition of Data_Quality class 

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#172]
**Issue Type**
Using the LABELS section to the right of this window >>>> , please indicate if this is a BUG or ENHANCEMENT request. If unknown, feel free to leave that blank, and the LDD Steward can triage appropriately.

**Describe the issue identified (if applicable)**
The imaging dictionary currently does not include a Data_Quality Class

See the spreadsheet for the needed attributes and definitions.
[Data_Quality_Class_Attributes.xlsx](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/files/6850325/Data_Quality_Class_Attributes.xlsx)

**Describe the solution you'd like**
The Mars 2020 Mastcam_Z team would like the addition of Data_Quaity attributes to describe the quality of their image products. 

**Describe alternatives you've considered**
The Data_Quality class could be broken up into several classes, i.e. Data_Qulaity, Hot_Pixels, Saturated_Pixels, Nonlinear_Pixels if this makes more sense for general utility.

Alternatively, these Data_Quality attributes could go in a  different dictionary, although the attributes seem to be specific to images.

**LDD Dictionary Version**
For bug fixes, note the LDD dictionary version in question.

**PDS4 IM Version**
1.16

**Need-by Date**
ASAP, these attributes will be needed to validate the upcoming Mars2020 PDS release.

**Additional context**
Add any other context or examples of products

The spreadsheet is updated definitions  to go with the  Data_Quality Class
The txt file is really an XML file with  an example of what the class should look like and notes for usage.

Updated files 
[Data_Quality_Class_Definitions_AB.xlsx](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/files/6894334/Data_Quality_Class_Definitions_AB.xlsx)

with Bob Deen Comments on 07/28
[data_quality_class_eaxmple.xml.txt](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/files/6896528/data_quality_class_eaxmple.xml.txt)

**Comment by thareUSGS** [comment]
I would think:
1) missing_pixel_count could be used for NOSSIGNAL_PIXEL_COUNT (although nosignal_pixel_count definition specifies an "above bias" which is not in the missing pixel definition.
2) I get "hot" pixel although somewhat odd name, but what is NONLINEAR?  Can we get a better definition?

still working over others... For example, XML doesn't like "arrays" or comma separated values like "1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0". Need to think on how to handle this.

**Comment by rgdeen** [comment]
I thought we discussed this months ago and resolved it?  Am I mis-remembering?  I know I had a conversation with zcam about it at least.

There are two ways to handle the qualities that are consistent with current usage.

One would be like we do e.g. temperatures, where we have a set of quality name and value pairs.  So (highly abbreviated) something like:
```
<Q>
  <name>Saturated</>
  <value>true</>
</Q>
<Q>
  <name>Zero-Value Pixels</>
  <value>false</>
</Q>
```
... etc

That's somewhat nice in that you don't have to change the DD to add new value types, but it's more cumbersome to use.

The other way is to actually define the flags, e.g.
```
<Data_Quality_Flags>
  <saturated>true</>
  <zero_value_pixel>false</>
   ...
</Data_Quality_Flags>
```
which would be a heck of a lot easier to use, but would require updating the DD whenever items are added.  Of course even the <name> mechanism would require this, if we listed valid values for the name.

So I'm leaning more towards the latter.  It's much easier to use, and much easier to get definitions for the keywords.  And the keywords are reusable too for other instruments - different set of them, but they'd all be cardinality 0-1.

There is NO reason whatsoever to store this in a bit field.  That would just be horrific to users.

**Comment by katecrombie** [comment]
Thanks Bob,

I agree with the no but field approach. Your idea with the defined quality items (second example) would be easy for a user to interpret and seems like it would have broad applicability.

Kate
Sent from my iPhone

On Jul 22, 2021, at 6:31 PM, rgdeen ***@***.***> wrote:

﻿

I thought we discussed this months ago and resolved it? Am I mis-remembering? I know I had a conversation with zcam about it at least.

There are two ways to handle the qualities that are consistent with current usage.

One would be like we do e.g. temperatures, where we have a set of quality name and value pairs. So (highly abbreviated) something like:

<Q>
  <name>Saturated</>
  <value>true</>
</Q>
<Q>
  <name>Zero-Value Pixels</>
  <value>false</>
</Q>


... etc

That's somewhat nice in that you don't have to change the DD to add new value types, but it's more cumbersome to use.

The other way is to actually define the flags, e.g.

<Data_Quality_Flags>
  <saturated>true</>
  <zero_value_pixel>false</>
   ...
</Data_Quality_Flags>


which would be a heck of a lot easier to use, but would require updating the DD whenever items are added. Of course even the mechanism would require this, if we listed valid values for the name.

So I'm leaning more towards the latter. It's much easier to use, and much easier to get definitions for the keywords. And the keywords are reusable too for other instruments - different set of them, but they'd all be cardinality 0-1.

There is NO reason whatsoever to store this in a bit field. That would just be horrific to users.

**Comment by katecrombie** [comment]
I'll work on getting a better nonlinear definition from the Mastcam-Z team.

**Comment by katecrombie** [comment]
@thareUSGS Ive updated the ticket with a spreadsheet and an example of what the Class should look like in the dictionary.

**Comment by katecrombie** [comment]
Updated file attachments with Bob's comments implemented on 7/28

**Comment by thareUSGS** [comment]
@katecrombie Can repost the "txt" file I think it was the wrong file.

**Comment by katecrombie** [comment]
@thareUSGS File is updated.  It was the wrong one.  Sorry about that.

**Comment by thareUSGS** [comment]
@katecrombie @rgdeen This block is feeling overly mission specific. I am worried about pushing this through so quickly without time for reviews and prototyped test cases. There is precedence also in OREX for a "Data_Quality" section. https://github.com/pds-data-dictionaries/dd-library/blob/9891a1d8955539265fb3bbf52d016ec7a37503a3/mission/orex/v1/orex_ldd_OREX_1400.xsd#L78

What is the impact if this updated doesn't make it for release 1?

**Comment by katecrombie** [comment]
@thareUSGS maybe it would be better to ask for this in the  Mars2020 mission dictionary.  The OREx example you point to was very mission-specific and applied to spectrometers as well as imagers.

**Comment by jordanpadams** [comment]
@thareUSGS as a quick aside, we should be careful to use OREX too heavily as a precedent since PDS4 and Discipline LDDs were in their infancy when that mission LDD was created. they did the best with what they had, but in hindsight, some things in there do make sense to be is discipline LDDs e.g. they have [lat/longs](https://github.com/pds-data-dictionaries/dd-library/blob/9891a1d8955539265fb3bbf52d016ec7a37503a3/mission/orex/v1/orex_ldd_OREX_1400.xsd#L342) and incidence angles specified in there as well :-) .

that being said, this particular Data_Quality class does seem very mission-specific. the other option would be to come up with a more generic data model for this class with some sort of key-value pairs to specify the information, but that may be overkill if this isn't something used often / similarly across missions.

**Comment by rgdeen** [comment]
I think it's completely mulitimission.  None of those concepts are overtly mission-specific, or no more than a few.  Other missions will likely need other kinds of quality flags but they can add them.

**Comment by thareUSGS** [comment]
@katecrombie @rgdeen @jordanpadams I think I have enough confirmation from folks -- I will try to add it to IMG

**Comment by rgdeen** [comment]
the general philosophy for img has been: add what we need in a way that we think will be resuable multi-mission-wise... knowing that we are far from complete or covering all potential cases.  Other missions can add what they need too, when they need it.

**Comment by thareUSGS** [comment]
@katecrombie @rgdeen  For <Data_Quality> 

1. are any attributes allowed to be repeated? 
2. I assume all Data_Quality internal classes and attributes are optional?
3.  I assume <Data_Quality> is to be included under the <Imaging> class or something like the <Instrument_State> or <Detector> Class? 
4. Lastly can <Data_Quality> itself be repeated?

**Comment by katecrombie** [comment]
1. No attributes need  to be repeated (at least as far I can imagine)
2. Yes all internal classes and attributes are optional, with the exception of <unit>.  If you have a threshold_value, you need to give it a unit.
3. I was thinking of it as at the same level as Radiometric_Calibration Class, but it could go in a Class like Image_State or something.  Maybe @rgdeen has a better idea.  
4. Data_Quality needs to be repeated because it could be needed to describe more than one image array or bayer cell.

**Comment by thareUSGS** [comment]
@katecrombie Also in this example section, I don't think I have seen <unit> listed outside an defined attribute value (for example: `<length unit=”m”>3</length>`

although we would be using Units_of_Spectral_Radiance here not length. Is <unit> needed for these classes? 

```
	<Saturated_Pixel>
		<count></count>
		<threshold_value></threshold_value>
		<unit></unit> <!-- DN,  W/M**2/SR/NM,  -->
	</Saturated_Pixel>
	<Nonlinear_Pixel>
		<count></count>
		<threshold_value></threshold_value>
		<unit></unit>  <!-- DN,  W/M**2/SR/NM,  -->
	</Nonlinear_Pixel>
```

I also change <count> to <pixel_count>

**Comment by rgdeen** [comment]
1-2-4 yes.
3. yeah I like same-as-rad-corr.  By design most everything goes in both Commanded_Parameters and Imaging.  While it's a bit of a stretch to imagine commanding the flags, one could imagine commanding the thresholds for a camera to so something with bad pixels.  So there's at least some theoretical possibility for Commanded thus we should keep the same general design.

**Comment by thareUSGS** [comment]
> 2\. threshold_value
Okay - so threshold_value will have Units_of_Spectral_Radiance

And I will try it in <Imaging> and <Commanded_Parameters>

**Comment by thareUSGS** [comment]
@katecrombie @rgdeen new build with initial Data_Quality Class. Please check it out. Also definition for IOF, still rough. Didn't want to definie it just for Mars. https://github.com/pds-data-dictionaries/ldd-img/tree/v1860_release

current IOF def:  https://github.com/pds-data-dictionaries/ldd-img/blob/902d8863e7f0b4f363b0e1edb1c3ec3ed933f18f/src/PDS4_IMG_IngestLDD.xml#L3000

**Comment by katecrombie** [comment]
@thareUSGS Thanks!  I'm going to share the build link with the Mastcam-Z team, so they can start to update templates.

**Comment by thareUSGS** [comment]
@katecrombie updated example, with a couple notes.

[data_quality_class_eaxmple_v2.xml.txt](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/files/6901194/data_quality_class_eaxmple_v2.xml.txt)

**Comment by katecrombie** [comment]
@thareUSGS Thanks!
