### ISSUE TITLE
[ldd-img] Addition of effective_wavelength attribute 

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#174]
**Issue Type**
ENHANCEMENT 

**Describe the issue identified (if applicable)**
The Mars2020 Mastcam-Z would like to add an effective_wavelength attribute to the imaging dictionary

**Describe the solution you'd like**
We would like an effective_wavelenght  attribute that defines the weighted average of the system response and solar spectrum  (float array).  This could go near the  <radiometric_zenith_scaling_factor> or it could go with IOF attributes (to be proposed in the next issue). 

**PDS4 IM Version**
1.16

**Need-by Date**
Needed for the  upcoming Mars 2020 at release

**Additional context**
Add any other context or examples products

**Comment by thareUSGS** [comment]
I have added using Units_of_Length (allows for "nm"). -- dealing with bad "log" directory can't push new files just yet.  I have asked for help.

**Comment by thareUSGS** [comment]
@katecrombie log issue is cleared up so the latest build version to test with this fix is here:
https://github.com/pds-data-dictionaries/ldd-img/tree/v1860_release

**Comment by thareUSGS** [comment]
was released with  1.8.6.0. Just closing tickets.
