### ISSUE TITLE
[ldd-img] Addition of  IOF class 

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#175]
**Issue Type**
ENHANCEMENT request.

**Describe the issue identified (if applicable)**
There are no available attributes to describe image IOF parameters.  

The Mars2020  Mastcam-Z  team would like the addition of attributes to describe reflectance (IOF) images. These attributes could be made into a class if that is better for general use.

iof_conversion_coefficient  - IOF Conversion coefficient (float_array)
iof_conversion_coefficient_std - 1-sigma standard deviation in IOF conversion coefficient (float_array)

**Describe the solution you'd like**
These attributes could go just after the  <Radiometric_Calibration> class,  or where ever you feel these are best located.

**PDS4 IM Version**
1.16

**Need-by Date**
Needed for the upcoming Mars2020 data release.

**Additional context**
Add any other context or examples products

**Comment by thareUSGS** [comment]
@katecrombie Is this need imminent? 

For any new IOF can we simply add "radiance factor" as a  radiometric_type?
https://github.com/pds-data-dictionaries/ldd-img/blob/9f9bfa9c619132f9a929cece2a761e60f40eae35/src/PDS4_IMG_IngestLDD.xml#L2931

And then add these two new attributes as optional under the Radiometric_Correction class: https://github.com/pds-data-dictionaries/ldd-img/blob/9f9bfa9c619132f9a929cece2a761e60f40eae35/src/PDS4_IMG_IngestLDD.xml#L6578

But you also list them as float_array? Are they really or just a single floating-point value? Arrays again is harder to support in XML and I would need an example.

**Comment by katecrombie** [comment]
@Trent, if this is easy to implement, soon would be good.   

I like the "radiance factor"  as a radiometric_type solution.

The two new IOF attributes could be implemented the same way as responsivity and responsivity_std.  (no float arrays, it would be a single floating point value per attribute)

**Comment by thareUSGS** [comment]
still need better radiance factor definition but implemented. Having wired "logs" directory issue. Hopefully it will clean itself up.
