### ISSUE TITLE
[ldd-img] Allow responsivity attributes to be nillable

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#178]
**Issue Type**
Enhancement

**Describe the issue identified (if applicable)**
We have few cases where the responsivity_r,g,b  attributes in a label are inapplicable.  In order to support this, we need to allow these attributes to be nillable.

**Describe the solution you'd like**
Please make 

"responsivity_r" 
 "responsivity_g" 
 "responsivity_b" 
 "responsivity_pan" 

nillable attributes.

**Describe alternatives you've considered**
No alternative

**LDD Dictionary Version**
For bug fixes, note the LDD dictionary version in question.

**PDS4 IM Version**
1.16

**Need-by Date**
ASAP for Mastcam-Z

**Additional context**
Add any other context or examples products

**Comment by thareUSGS** [comment]
updated in branch v1860_release for testing:
https://github.com/pds-data-dictionaries/ldd-img/tree/v1860_release/build

**Comment by rgdeen** [comment]
This should be accommodated by just leaving the attributes off.  Why do they need to be nillable?

I don't object per se, but removing attributes that are not needed or not applicable is the Best Practices paradigm for the imaging dictionary.

So If it's not cardinality 0-1 already, it should be...
