### ISSUE TITLE
[ldd-disp] Axis names are not being validated

### ISSUE THREAD

**Issue by jstone-psi** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#183]
**Describe the issue identified (if applicable)**
The `horizontal_display_axis` and `vertical_display_axis` attributes are expected to match the name of an axis in the associated array, but this is not being enforced. Labels where the axis names don't match (for instance, if the case does not match) are passing validation. An example of one such label is attached.

**Describe the solution you'd like**
I would like to Schematron rules added that require that the `horizontal_display_axis` and `vertical_display_axis` attributes match the `axis_name` of one `Axis_Array` element in the associated array.

**LDD Dictionary Version**
1.5.0.0

**Additional context**
[703_20210708_2B_N19079_01_0004.arch.txt](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/files/7220732/703_20210708_2B_N19079_01_0004.arch.txt)

**Comment by thareUSGS** [comment]
@jstone-psi Does geom:horizontal_display_axis have the same schema need?

Also should those be enumerated such that only "Sample" and "Line" are available. Could there be other options supported?

**Comment by jstone-psi** [comment]
@thareUSGS Yes, I believe that `geom:horizontal_display_axis` and `geom:vertical_display_axis` will ultimately have the same need. The documentation for those attributes matches the equivalent attributes in the display dictionary.

I don't believe that having only `Line` and `Sample` immediately makes sense. Currently, the documentation for the display direction classes only states that it must match an exisitng `axis_name`. I would think that's intentional, and that it should be enforced as written for now.

**Comment by thareUSGS** [comment]
Now let's see if I can figure out how to do a schema rule for those...

**Comment by jstone-psi** [comment]
Thanks @thareUSGS. I have some experience with this, so let me know if I can help.
