### ISSUE TITLE
[ldd-cart] Grid_Coordinate_System should require a choice

### ISSUE THREAD

**Issue by wkiri** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#209]
**Describe the issue identified**
The Grid_Coordinate_System class has three optional sub-classes, but semantically requires one and only one to be chosen.

**Describe the solution you'd like**
Organize the three options as a XSChoice with cardinality [1,1]. 

**LDD Dictionary Version**
1.9.6.0

**PDS4 IM Version**
1.18.0.0

**Need-by Date**
May 20, 2022 to be included in the next IM build.

**Additional context**
DMSP workshop follow-up.

**Comment by thareUSGS** [comment]
updated in v1960 (heading to main soon):
https://github.com/pds-data-dictionaries/ldd-cart/blob/929ed4708acebf6884a5eeb3fe029a71f60a7374/src/PDS4_CART_IngestLDD.xml#L2712

**Comment by thareUSGS** [comment]
released so closing.
