### ISSUE TITLE
[ldd-img] Sub-frame and down-sampling class help

### ISSUE THREAD

**Issue by msbentley** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#21]
Taking advantage of the GitHub functionality, I'd like to ask a couple of questions, if I may! I'm trying to write a label for a monitoring (engineering) camera onboard BepiColombo and am struggling to fit two attributes into the label:

1. The camera has an "undersampling" mode which sends every other line/row from the sensor (i.e. 1/4 of the pixels). Is this the right place/way to describe this:

    ```Image_Product_Information/Sample_Parameters/sampling_factor = 2```

2. The camera can return a full frame, or quarter frames - centered, or in the corners and along each side (9 possibilities). Is Subframe_Parameters the right place for this? If so, I can see how to describe the start pixel and size using first_line/first_sample and lines/samples, but am unclear about the meaning of the mandatory "samples" attribute: "indicates the total number of data instances along the horizontal axis of an image or sub-image." Could someone clarify?

Thanks!!

**Comment by thareUSGS** [comment]
@msbentley please re-open if needed. Closing for now.

**Comment by msbentley** [comment]
Thanks @thareUSGS I haven't worked on this for some time, and am not sure when we will coordinate an IM and dictionary update, but will post back if I still have questions!
