### ISSUE TITLE
[ldd-cart] Repo needs a separate change log file

### ISSUE THREAD

**Issue by sarabond** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#212]
**Describe the issue identified (if applicable)**
There is no change log file. The information is captured in the ingest file but that information needs to be updated. 

**Describe the solution you'd like**
Create a separate change log file.

**LDD Dictionary Version**
1.9.6.0

**PDS4 IM Version**
1.18.0.0

**Need-by Date**
May 20, 2022 to be included in the next IM build.

**Additional context**
DMSP workshop follow-up.

**Comment by thareUSGS** [comment]
thanks for the note to update. CHANGELOG.md added to new branch - will be push to main soon:
https://github.com/pds-data-dictionaries/ldd-cart/tree/v1.9.6.0

**Comment by wkiri** [comment]
Great!  I suggest leaving this issue open and indicating when you do the PR for that branch that it will at that time close the issue.  That way it won't get lost in the shuffle :)

**Comment by thareUSGS** [comment]
oops - will try to remember to leave other tickets open until PR is finished.

**Comment by wkiri** [comment]
Easy to reopen as desired!

**Comment by thareUSGS** [comment]
released a while ago, but never closed. closing
