### ISSUE TITLE
[ldd-cart] Update definitions to fix typos/wording

### ISSUE THREAD

**Issue by wkiri** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#224]
**Describe the issue identified**
Some class/attribute definitions have typos or other wording issues.

**Describe the solution you'd like**
Recommended typos/fixes:

Map Projection Class definitions:
* [x] Line 3982: `Map_Projection_Lander` class: Definition says "The Map_Projection class" but should say "The Map_Projection_Lander class"
----
Other class definitions:
* [x] Line 4017: `Surface_Model_Parameters` class definition: To be consistent with other class definitions it should read “The Surface_Model_Parameters class describes…” instead of "This class describes"
* [x] Line 2694: `Cartography` class definition: Extra "or" in "The Cartography class provides a description of how a 3D sphere, spheroid, or elliptical spheroid, or the celestial sphere is mapped onto a plane."
* [x] Lines 4637 (`Vector_Projection_X_Axis`) and 4653 (`Vector_Projection_Y_Axis`): Definitions include "this vector defines how the * axis in the mosaic is oriented in space": should the "*"  be there? Is that a placeholder for a word?
----
Attribute definitions (alphabetic order):
* [x] `angular_scale`: Suggest definition indicates "radians/pixel" (plural) or "rad/pixel".
* [x] Line 1414: `bearing_reference_meridian`: The value_meaning for "Magnetic" refers to the Earth only.  Omit "on Earth"?
* [x] Line 565: `c_axis_radius`: Suggest adding a period to the end of the definition.
* [x] Line 652: `coordinate_system_type`: Suggest capitalizing "an inertial..." in the value_meaning for Inertial.
* [x] Line 1332: `distance_resolution`: Definition says "expressed in Planar Distance Units of measure" but unit_of_measure_type is Units_of_Map_Scale.  Suggest using the same language in the definition.
* [x] `east_bounding_coordinate`: Suggest removing commented-out Terminological_Entry values if not needed.
* [x] Line 1053, 1058: `grid_coordinate_system_name`: Very nice value_meanings.  Suggest capitalizing the start of value_meaning for ARC Coordinate System and Other Grid System and making them into complete sentences.
* [ ] Line 2552: `local_time_scale`: It is not clear from the definition how this is a "time scale".
* [x] Line 583-584: `longitude_direction`: Suggest updating definition to use Title Case versions of permissible values instead of all-caps (e.g., POSITIVE_EAST -> Positive East) for internal consistency.
* [x] Line 603: `longitude_direction`: Typo in value_meaning for Positive East: "bodies" -> "body's"
* [x] Line 2480: `look_direction`: Update "theBIDR" -> "the BIDR". Please also spell out BIDR to avoid unknown acronyms.
* [x] Lines 2492, 2496: `look_direction`: One value_meaning uses "ground-track" while the other uses "groundtrack"; resolve for consistency (should also match usage in definition).
* [x] Line 996: `map_projection_name`: van der Grinten value_meaning refers to itself as "Vander Grinten".  Capitalization and spacing should be consistent.
* [x] Line 924: `map_projection_name`: Orthographic value_meaning states: "... a plane tangent to the earth".  Suggest changing to "a plane tangent to the body" to generalize beyond the Earth.
* [x] `map_projection_name`:  Equirectangular value_meaning states: "This form is often called the Plate Carree or the Simple Cylindrical projection."  Since these are not permissible values, consider clarifying that Equirectangular is the preferred term for all three.
* [x] `map_projection_name`: Robinson value_meaning states: "Also called orthophanic."  Orthophanic is not a permissible value, so consider clarifying that Robinson is the preferred term.
* [x] `map_projection_name`: van der Grinten value_meaning states: ""conceived as a compromise between the Mercator and the Mollweide projection"", but Mollweide is not a permissible value.  Consider adding a reference so readers know what it is.

(List as of May 11, 2022; future updates will be added below here)

* [x] Line 2060: `map_projection_rotation`: Definition would benefit from more detail - what is this value?  Why was it "included for generality" even though always 90 degrees for one particular instrument?
* [ ] `max_footprint_line`: Definition: "size" of a footprint seems like it should require units.  Or, should this be the "number" of footprints?
* [ ] `max_footprint_sample`: Definition: "size" of a footprint seems like it should require units.  Or, should this be the "number" of footprints?
* [x] `maximum_elevation`: Definition: it isn't clear why this value applies for more projections than the minimum_elevation attribute does.  Should they mach?
* [ ] `min_footprint_line`: Definition: "size" of a footprint seems like it should require units.  Or, should this be the "number" of footprints?
* [ ] `min_footprint_sample`: Definition: "size" of a footprint seems like it should require units.  Or, should this be the "number" of footprints?
* [x] `minimum_elevation`: Definition: it isn't clear why this value applies for fewer projections than the maximum_elevation attribute does.  Should they match?
* [x] `north_bounding_coordinate`: Suggest removing commented-out Terminological_Entry values if not needed.
* [ ] `oblique_line_latitude`: Definition: recommend explaining what "the oblique line" is.
* [ ] `oblique_line_longitude`: Definition: recommend explaining what "the oblique line" is.
* [x] `oblique_proj_pole_latitude`: Definition: recommend changing OBLIQUE_CYLINDRICAL to match "Oblique_Cylindrical" for consistency with specification in the Map_Projection class.
* [x] `oblique_proj_pole_longitude`: Definition: recommend changing OBLIQUE_CYLINDRICAL to match "Oblique_Cylindrical" for consistency with specification in the Map_Projection class.
* [x] `oblique_proj_pole_rotation`: Definition: recommend changing OBLIQUE_CYLINDRICAL to match "Oblique_Cylindrical" for consistency with specification in the Map_Projection class.
* [x] `oblique_proj_x_axis_vector`: (1) Typos in definition: "attirubte" -> "attribute"; "makeup" -> "make up"; "90" should be deleted. (2) Recommend changing all-caps class names to Title Case for consistency with specification in the Map_Projection class (and elsewhere).
* [x] `oblique_proj_y_axis_vector`: (1) Typos in definition: "attirubte" -> "attribute"; "makeup" -> "make up"; "90" should be deleted. (2) Recommend changing all-caps class names to Title Case for consistency with specification in the Map_Projection class (and elsewhere).
* [x] `oblique_proj_z_axis_vector`: (1) Typos in definition: "attirubte" -> "attribute"; "makeup" -> "make up"; "90" should be deleted. (2) Recommend changing all-caps class names to Title Case for consistency with specification in the Map_Projection class (and elsewhere).
* [x] `projection_elevation_line`: The minimum value of 1 implies that lines are one-indexed (versus zero-indexed); if so, it might be helpful to explicitly state this in the definition.
* [x] `reference_latitude`:  (1) Definition appears only to apply to the Cassini mission; check if this is true or should be generalized (i.e., for any mission using Oblique_Cylindrical). (2) Recommend changing all-caps class names to Title Case for consistency with specification in the Map_Projection class (and elsewhere).
* [x] `reference_longitude`: (1) Definition appears only to apply to the Cassini mission; check if this is true or should be generalized (i.e., for any mission using Oblique_Cylindrical). (2) Recommend changing all-caps class names to Title Case for consistency with specification in the Map_Projection class (and elsewhere).
* [x] `rings_map_projection_name`: Definition: Please define CIRS or remove this reference to a specific instrument, for general use.
* [x] `south_bounding_coordinate`: Suggest removing commented-out Terminological_Entry values if not needed.
* [x] `spcs_zone_identifier`: (1) This coordinate system seems to be specific to the U.S.; if retained, it would be helpful to specify this limitation in the definition. (2) There are only ~125 zones, so it is not clear why the user must specify four digits.  Should the leading digit be optional (and minimum_characters set to 3)?  If not, perhaps the definition can explain why four digits are required to aid the user.
* [x] `start_azimuth`: Definition says this only applies to Cylindrical and Cylindrical_Perspective classes, but it is also required by the Perspective class.
* [x] `stop_azimuth`: Definition says this only applies to Cylindrical and Cylindrical_Perspective classes, but it is also required by the Perspective class.
* [x] `ups_zone_identifier`: It is not clear what the A, B, Y, Z values mean; more information would help users choose.
* [x] `utm_zone_number`: UTM zones are typically 1-60, but here 0 is allowed as well as negative values down to -60.  It is not clear what those values would mean.  Consider updating the definition to clarify.
* [x] `west_bounding_coordinate`: Suggest removing commented-out Terminological_Entry values if not needed.

(List as of May 18, 2022; future updates will be added below here)

**LDD Dictionary Version**
1.9.6.0

**PDS4 IM Version**
1.18.0.0

**Need-by Date**
May 20, 2022 to be included in the next IM build.

**Additional context**
DMSP workshop follow-up.

**Comment by wkiri** [comment]
I added several more suggested updates to attribute definitions in the issue description above.

**Comment by thareUSGS** [comment]
Updates in 1.9.7.0. Simply closing.
