### ISSUE TITLE
[ldd-cart] Recommended updates to attribute specifications

### ISSUE THREAD

**Issue by wkiri** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#228]
**Describe the issue identified**
Some attribute specifications are incomplete or could use some updates.

**Describe the solution you'd like**
Recommended updates are listed below.  Feel free to check off any that you decide to skip!

Attributes (alphabetic order):
* [x] `angular_scale`: Has specified_unit_id but no min/max.
* [x] `bearing_reference_direction`: Currently specifies min and max chars for the string length, but it seems this is handled by the specified permissible values.  Omit min/max char length?
* [x] `bearing_reference_meridian`: Currently specifies min and max chars for the string length, but it seems this is handled by the specified permissible values.  Omit min/max char length? 
* [x] `bearing_resolution`: (1) Needs a specified_unit_id for the minimum_value. (2) Consider adding a maximum_value.
* [x] `coordinate_system_name`: Suggest making this UTF8_Text_Preserved instead of ASCII_Text_Preserved, since it is a free text entry, for greater flexibility.
* [x] `coordinate_system_type`: Currently specifies min and max chars for the string length, but it seems this is handled by the specified permissible values.  Omit min/max char length?
* [x] `data_count`: Perhaps does not need a specified_unit_id for the minimum_value since unit_of_measure_type is Units_of_None?
* [x] `distance_resolution`: Units_of_Map_Scale is deprecated: https://pds.nasa.gov/datastandards/documents/im/current/index_1H00.html#class_pds_units_of_map_scale ; consider Units_of_Pixel_Resolution_Map
* [x] `east_bounding_coordinate`: Suggest removing commented-out Terminological_Entry values if not needed.
* [x] `grid_coordinate_system_name`: Since this is not a numeric measure, omit units_of_measure_type.
* [x] `lander_map_projection_name`: (1) Since this is not a numeric measure, omit units_of_measure_type. (2) One of the permissible values is "Orthographic", but since its meaning differs from that of Orthographic in the map_projection_name attribute, we recommend making it "Orthographic_Lander" (also for consistency with the XSChoice in the Lander Map Projection class).
* [x] `latitude_type`: Since this is not a numeric measure, omit units_of_measure_type.
* [x] `line`: Should this be an integer type instead of ASCII_Real?
* [x] `line_name`: Suggest making this UTF8_Text_Preserved instead of ASCII_Text_Preserved.
* [x] `local_description`, `local_georeference_information`, `local_planar_description`, `local_planar_georeference_information`: (1) Suggest making this UTF8_Text_Preserved instead of ASCII_Text_Preserved.  (2) Consider omitting unit_of_measure_type since it is a string (not a measure).
* [x] `longitude_direction`: (1) Currently specifies min and max chars for the string length, but it seems this is handled by the specified permissible values.  Omit min/max char length? (2) Since this is not a numeric measure, omit units_of_measure_type.
* [x] `look_direction`: (1) Suggest updating permissible values to use Title Case instead of all-caps (e.g., RIGHT -> Right) for consistency. (2) Since the values are strings, omit units_of_measure_type. (3) In the generalization attempt, consider adding a value "Both".
* [x] `map_projection_name`: (1) Since the values are strings, omit units_of_measure_type.
* [x] `oblique_proj_x_axis_vector`, `oblique_proj_y_axis_vector`, `oblique_proj_z_axis_vector`: Since this attribute is "redundant", consider omitting it and encouraging the use of the oblique_proj_* attributes only (especially since currently this is ASCII_Text_Preserved and does not enforce any structure/formatting of the value).
* [x] `pixel_resolution_x`, `pixel_resolution_y`: (1) Definition permits "degree/pixel", but this is not a valid choice according to the specified unit of measure (Units_of_Map_Scale).  pixel/degree is permitted; was this intended? (2) Units_of_Map_Scale is deprecated: https://pds.nasa.gov/datastandards/documents/im/current/index_1H00.html#class_pds_units_of_map_scale ; consider Units_of_Pixel_Resolution_Map (which does permit degree/pixel)
* [x] `pixel_scale`, `pixel_scale_x`, `pixel_scale_y`: (1) Definition permits "pixel/distance", but this is not a valid choice according to the specified unit of measure (Units_of_Map_Scale).  distance/pixel is permitted; was this intended? (2) Units_of_Map_Scale is deprecated: https://pds.nasa.gov/datastandards/documents/im/current/index_1H00.html#class_pds_units_of_map_scale ; consider Units_of_Pixel_Scale_Map (although this only permits pixel/degree not pixel/distance)
* [x] `projection_azimuth`: (1) It is not clear why the minimum value should be 1 degree.  Could it be a real number less than 1 (like 0.5 or 0.0)?  If not, please explain in the definition. (2) Should there be a maximum specified?
* [x] `projection_elevation`: Should there be a minimum value specified?  Maximum?  e.g. 0 and 90 since this is an elevation in degrees?
* [x] `projection_elevation_line`: (1) If this value must be an integer, consider ASCII_NonNegative_Integer instead of ASCII_Real. (2) The minimum value of 1 implies that lines are one-indexed (versus zero-indexed); if so, it might be helpful to explicitly state this in the definition.
* [x] `radial_scale`: Should a minimum value such as 0.0 be specified?
* [x] `reference_azimuth`: Should there be a minimum and maximum specified?
* [x] `rings_map_projection_name`: Since this is not a numeric measure, omit units_of_measure_type.
* [x] `sample`: Should this be an integer type instead of ASCII_Real?
* [x] `sample_name`: Suggest making this UTF8_Text_Preserved instead of ASCII_Text_Preserved.
* [x] `scale_factor_at_projection_origin`: Should this attribute have a minimum value of 0.0 akin to scale_factor_at_central_meridian?
* [x] `sphere_intersection_count`: If the only valid values are 1 and 2, consider using an enumeration.  If not, consider ASCII_NonNegative_Integer (it does not seem that this value can be negative) and specify the min and max values.
* [x] `sphere_radius`: This attribute has a minimum_value but no specified_unit_id; consider adding it.
* [x] `start_azimuth`, `stop_azimuth`: Minimum_value and maximum_value are specified, but there is no specified_unit id.  Consider adding it (probably deg).
* [x] `surface_model_type`: Since the only permissible values are specified, I think this should have the enumeration_flag set to true.
* [x] `target_center_distance`: Given the semantics, it seems likely that the minimum_value should be set to 0 (i.e., no negative values).
* [x] `x`, `y`, `z`: The definition indicates that this value is unitless; consider adding Units_of_None as the unit_of_measure_type.
* [x] `x_length`, `y_length`, `z_length`: Since this is a length, consider specifying a minimum_value of 0 (and corresponding specified_unit_id).
* [x] `x_unit`, `y_unit`, `z_unit`: The Vector_Cartesian_Unit_Base class indicates that min/max values of this attribute should be -1 and 1 respectively.  Suggest adding them explicitly here. 

**LDD Dictionary Version**
1.9.6.0

**PDS4 IM Version**
1.18.0.0

**Need-by Date**
May 20, 2022 to be included in the next IM build.

**Additional context**
DMSP workshop follow-up.

**Comment by thareUSGS** [comment]
Updates in 1.9.7.0. SImply closing.
