### ISSUE TITLE
[ldd-cart] IN Local, make subclasses part of a choice statement

### ISSUE THREAD

**Issue by mit3ch** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#229]
**Describe the issue identified (if applicable)**
The Local class contains three optional subclasses. It looks like the class should require one and only one of the subclasses be present.

**Describe the solution you'd like**
Assuming the issue statement above is correct, consider combining the subclasses in a choice statement with cardinality of [1,1]

**Describe alternatives you've considered**
If the interpretation in the issue statement is incorrect, do nothing.

**PDS4 IM Version**
Not urgent

**Need-by Date**
Not urgent

**Comment by thareUSGS** [comment]
Good comment. However, in practice a Local system can be defined not as Map_Projection_Lander or Map_Projection_Rings. Others refer this also as engineering coordinates. For that style of system, the required local_description should be used to define the local system used in the label.

cons: local could be used as a catch-all for those not wanting to really define their system or map projection.

I am closing without updates.
