### ISSUE TITLE
[ldd-img] Additional compression types

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#23]
img:onboard_compression_type needs two additional values:

LZO - Lempel-Ziv-Oberhumer, a type of lossless data compression focused on decompression speed.
GZIP - GZIP lossless compression

(I don't have any better descriptions, just pulled those from wikipedia ;-) )

**Comment by thareUSGS** [comment]
update in forthcoming IMG v1.8.0.0.

To your second post, @rgdeen, I have not seen a request for msn_surface to include onboard_compression_type. If you still need lets start a new msn_surface issue. For inclusion of one attribute from IMG, I would be tempted to simply copy it (noting in both dictionaries it has been copied.

**Comment by rgdeen** [comment]
oh I thought the above was an implied request ;-)

So given that the compression is happening at the data product level and can apply to ANY data product, it seems like msn_surface is needed.

But... it's kind of by definition lossless (you can't lossy compress a data product without knowing what the contents are).  So it's a bit less important, but it's still good to document.

It would be easiest for me/most consistent to throw in an img:Onboard_Compression.  But given that it's only lossless, we could perhaps get by with just a single compression type keyword, with appropriate definition.

Thoughts?
