### ISSUE TITLE
[ldd-ml] Address DMSP suggestions

### ISSUE THREAD

**Issue by wkiri** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#232]
**Describe the issue identified**
Address suggestions from DMSP review of this sub-model.

**Describe the solution you'd like**
* [x] `Data_Set` class: `data_set_size` could  be misinterpreted as a byte size. Maybe data_set_count would be a better name.
* [ ] `Data_Set` class: Add an attribute called `data_set_name` or other attributes to document the source of the data_set. See  comments for Training_Set, Validation_Set, Test_Set
* [x] `Machine_Learning_Algorithm`: `algorthm_learning_style`: For enumerated values, the   meaning of labeled data is unclear. Explanation could be clearified in   documentation.
* [x] `Test_Performance`: `performance_score`: It is not clear if the value has   limits; is always positive; has a limit that means a perfect score. Can a   min/max be added to definition and the description be revised to   clarify?
* [x] `Training_Set, Validation_Set,   Test_Set`: These (Data_Set class) classes   do not include attributes to provide provence or processing details as noted   in the class definitions. Add appropriate attributes to the Data_Set class.
* [x] `Validation_Set, Test_Set`: The difference between these two   classes is not clear. Either update the class definitions and/or explain in   the documentation.

**Describe alternatives you've considered**
None

**LDD Dictionary Version**
1.0.1.0

**PDS4 IM Version**
1.18.0.0

**Need-by Date**
When possible.

**Additional context**
DMSP workshop follow-up.

**Comment by wkiri** [comment]
I've addressed all of the suggestions except the one to add a `data_set_name` attribute to the Data_Set class.  Not all data sets have a designated name, so this might be hard to fill in.  However, for provenance, it is worth thinking of a way to include a `data_set_source` (DOI?) which would give the option for a direct link to the original data set.

**Comment by jordanpadams** [comment]
@wkiri You could maybe leave this somewhat "open ended" and have a choice for how they want to reference the data set amongst a few options. Here are some that come to mind, but others may have some ideas:
* https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#class_pds_internal_reference
* (DOI can be used here) https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#class_pds_external_reference
* https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#class_pds_external_reference_extended

Not sure if these would be considered "source products" or not, but here are some others:
* https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#class_pds_source_product_internal
* https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#class_pds_source_product_external
* https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#9.37%C2%A0%C2%A0class_pds_table_delimited_source_product_external
* https://pds.nasa.gov/datastandards/documents/im/v1/index_1I00.html#9.37%C2%A0%C2%A0class_pds_table_delimited_source_product_internal

**Comment by wkiri** [comment]
@jordanpadams YThanks! es, I think a `pds.external_reference` would be great.  We use that for a DOI for the machine learning algorithm specification (when documented with a paper); see below.  I think a DOI for the data set(s) likewise formatted would be a good addition.

https://github.com/pds-data-dictionaries/ldd-ml/blob/c13e6ca92c9bfc18b42778ad2f7bb06e9e17b67e/src/PDS4_ML_IngestLDD.xml#L388-L394
