### ISSUE TITLE
[ldd-img_surface] Add correlation_pyramid_level

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#239]
Please add a new keyword to img_surface:Stereo_Product_Parameters.

correlation_pyramid_level
int, cardinality 0-1
range 0-n

Contains the pyramid level for the correlation.  Correlations are often downsampled by a power of 2 (2, 4, 8, etc) in order to speed computation.  If multiple such powers of 2 exist they form a "pyramid", hence the name.  This keyword stores the pyramid level for this correlation, as a power of 2.  For example, if the value is 0, it says the correlation image is the same size as the input image.  If the value is 3, it says the correlation image is 1/2^3 = 1/8 the original image size (fractions are truncated).

@thareUSGS

**Comment by thareUSGS** [comment]
added to v1280 img_surface
