### ISSUE TITLE
[ldd-img] Groups to support subordinate image types in img:

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#24]
So there are a number of image products that can be asked for in addition to an image. These all need representation in the Command_Parameters group (and for completeness, in Imaging as well). They are:

thumbnails
row sums
column sums
reference pixels
histograms

I think the best way to do this is to have a class for each of these types, containing what is needed (mostly other existing classes or attributes, see below). Each one contains product_flag saying whether or not the product was requested (or in a non-command setting, whether or not this IS said product). I'm reusing Frame for the image itself for this purpose. In all cases, cardinality is 0..1.

product_flag - string, True/False
Indicates whether the product in the enclosing class was requested for downlink (when in Commanded_Parameters), or whether this product actually is the type in question (when in Imaging). For example, Commanded_Parameters.Histogram.product_flag = True indicates that a histogram was requested as part of the command that created the data product being labeled, while Imaging.Histogram.product_flag = True indicates that this data product itself is (or contains) a histogram.

Frame - same as before, just add a new sentence to the end of the description: In the context of Frame, product_flag refers to the actual image.
product_flag

Thumbnail - Describes a Thumbnail product, which is a greatly reduced resolution version of the image.
product_flag
download_priority
Subframe
Onboard_Compression

Row_Sum - Describes a Row Summation product, which is a single column containing the sum of all pixels in each row of the image.
product_flag
download_priority

Column_Sum - Describes a Column Summation product, which is a single row containing the sum of all pixels in each column of the image.
product_flag
download_priority

Reference_Pixel - Describes a Reference Pixel product, which is a set of dark, non-imaging pixels used to monitor electronics.
product_flag
download_priority
Onboard_Compresson

Histogram - Describes a Histogram product.
product_flag
download_priority

**Comment by rgdeen** [comment]
add Sampling as an optional child of Thumbnail too.

**Comment by thareUSGS** [comment]
@rgdeen so Frame is currently very simple only having 2 attributes (3 with product_flag). see: https://github.com/pds-data-dictionaries/ldd-img/blob/26eea684ad632137ed146d14922644acafcbddd1/src/PDS4_IMG_IngestLDD.xml#L4805

but classes like Onboard_Compression live outside of Frame. But now we want to include Onboard_Compression within a new class called Thumbnail. Does this imply you will have need to have a Frame defined and Thumbnail, Histogram, etc. defined in the same label? Is it possoble to simply have a Thumbnail label with its own Onboard_Compression (thus there is no need to have Onboard_Compression within Thumbnail -- trying to keep the label consistent.

Now if you have a Frame label with a section for Thumbnail, Histogram then I guess this works...

**Comment by rgdeen** [comment]
yeah the thing is, we have Commanded versions of all of those at once.  But only one actual.  So I would not want to use the Onboard_Compression within an actual Thumbnail (really, actual Thumbnail just says flag=true), but rather in the primary Onboard_Compression, since the product IS the thumbnail in that case.  I do need it in Thumbnail though.

Putting Thumb, Histo etc under Frame doesn't work I think because Frame is a sibling.  The command asks for all of: frame, histo, thumb.  However, I'm loath to move things like the primary image's commanded compression under Frame.  Then you end up with everything under Frame and haven't bought much.  So I'm kind thinking Frame is a special case, basically just the flag, and all the others get the pieces they need.  (only the Thumb needs compression for example, since the others aren't images that get compressed).

I agree it's a bit messy but don't have a better solution.

**Comment by thareUSGS** [comment]
messy implemented :-) in forthcoming v1.8.0.0
