### ISSUE TITLE
[ldd-rings] Request for version 1G00_1B00 

### ISSUE THREAD

**Issue by mace-space** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#240]
An R&A data provider requires version 1G00_1B00 of the rings dictionary to be made available at https://pds.nasa.gov/datastandards/dictionaries. I can find 1G00_1A00 at https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#rings, but I cannot find 1G00_1B00. 

The version is already built at https://github.com/pds-data-dictionaries/ldd-rings/tree/main/build/release/1.16.0.0, but when I try to run the validate tool on the R&A data provider's bundle, there is an error:
` Error occurred while loading schematron: Schematron 'https://pds.nasa.gov/pds4/rings/v1/PDS4_RINGS_1G00_1B00.sch' error: Cannot read schematron from URL https://pds.nasa.gov/pds4/rings/v1/PDS4_RINGS_1G00_1B00.sch`

**LDD Dictionary Version**

PDS4_RINGS_1G00_1B00

**Comment by mace-space** [comment]
Would Richard Chen be able to fix this? @rchenatjpl

**Comment by jordanpadams** [comment]
@mace-space this is actually @c-suh . even though the release was tagged, it looks like it was tagged as part of the 1H00_1B00 release, but we only grab the latest LDD released when we post online. Any past versions need to be manually released online.

You can do so here: https://github.com/NASA-PDS/operations/issues/new?template=-ldd-request--pds-ldd-release.md

**Comment by mace-space** [comment]
Thanks @jordanpadams. I've requested it via your link

**Comment by c-suh** [comment]
Addressed in https://github.com/NASA-PDS/operations/issues/352 (now closed).

**Comment by jordanpadams** [comment]
thanks @c-suh
