### ISSUE TITLE
[ldd-rings] [ldd-cart] Reprojection grid attributes for ring coordinate system

### ISSUE THREAD

**Issue by matthewtiscareno** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#241]
**Describe the issue identified (if applicable)**
A data provider will deliver images reprojected onto a radius-longitude grid in a ring-based coordinate system.  Both inertial and co-rotating longitudes may be desired. 

**Describe the solution you'd like**
Do attributes to describe reprojection grids already exist in the Cartography LDD?  If so, do they (or could they) include radius and longitude as appropriate for this project?  Alternatively, should we create attributes of this kind in the Rings LDD?

**Comment by thareUSGS** [comment]
Currently, the Rings sections under CART has one defined map projection called "Ring_Polar". Thus, it does look like we need a new Class and new attributes. I have no experience with Rings map projections and would need help with the Class name, attributes, and definitions. This issue could be a location to start collecting those attributes (or simple add to a new file and request a pull.

For context, here is the one class under Rings which has the single map projection: https://github.com/pds-data-dictionaries/ldd-cart/blob/6f3585fb2de8573fc63400091a44310111e3cd9d/src/PDS4_CART_IngestLDD.xml#L4674

Here are the attributes: https://github.com/pds-data-dictionaries/ldd-cart/blob/6f3585fb2de8573fc63400091a44310111e3cd9d/src/PDS4_CART_IngestLDD.xml#L4683

**Comment by matthewtiscareno** [comment]
Thank you, @thareUSGS.  We'll have to look at whether we can expand the Ring_Polar class for our purposes, or whether we should add one or more new ones.  

I see that Ring_Polar is currently the only available subclass of Map_Projection_Rings, but you likely did it that way in order to make room for future additional classes alongside it.  One issue is that Ring_Polar's name is unduly broad, as the alternatives I have in mind are also polar projections. 

What do you use for map projections of a planetary surface?  Is it Map_Projection_Lander (the only other class I see), or something else?  It seems like it would be good for ring projections to have the same format as other projections.

**Comment by thareUSGS** [comment]
CART is trying to provide support for "typical" cartographic surface mapping applications, more in-situ rover projections, and now "rings".

For these 3 domains, they are organized into the 3 major map projection sections.

1. Geographic = Lat/Lon (not really a map projection).  But _"defines where the data is located on the bodies' surface"_ -[Esri](https://www.esri.com/arcgis-blog/products/arcgis-pro/mapping/gcs_vs_pcs/)
2. Planar = [Planar](https://pds-data-dictionaries.github.io/ldd-cart/detailed/example.html#planar) meaning a defined Cartesian plane (in meters). This is bulk for typical map projection information for "surface" mapping application.  _"a map projection is any method of flattening a continuous curved surface onto a plane"_ -[wikipedia](https://en.wikipedia.org/wiki/Map_projection)
3. Local = (Rover, Rings, other)
more: https://pds-data-dictionaries.github.io/ldd-cart/detailed/example.html

This whole design was heavily modeled after the FGDC data model: https://www.fgdc.gov/csdgmgraphical/spref/horiz/planar.htm
more: [Map projections: A working manual](https://doi.org/10.3133/pp1395)

**Comment by matthewtiscareno** [comment]
Per the discussion here and at #301, we plan to implement more detailed ring reprojection attributes in the Rings LDD and not in the Cartography LDD.
