### ISSUE TITLE
[ldd-rings] Update ring longitude attributes

### ISSUE THREAD

**Issue by mace-space** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#244]
**Describe the issue identified (if applicable)**

The ring longitude attributes should be more clearly named, to distinguish different frames of reference. Currently `<rings:minimum_ring_longitude>` and `<rings:maximum_ring_longitude>` refer to the inertial frame.

**Describe the solution you'd like**

Deprecate/rename `<rings:minimum_ring_longitude>` and `<rings:maximum_ring_longitude>` (that is, for inertial longitudes) and create new attributes that include the type of frame in the attribute name: `<rings:minimum_ring_longitude_inertial>`, `<rings:maximum_ring_longitude_inertial>` and `<rings:minimum_ring_longitude_corotating>`, `<rings:maximum_ring_longitude_corotating>`.

**Comment by matthewtiscareno** [comment]
This was done by [v1.12](https://github.com/pds-data-dictionaries/ldd-rings/pull/16)
