### ISSUE TITLE
No `ldd-proc` built against IM 1.J.0.0?

### ISSUE THREAD

**Issue by myche** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#246]
**Issue Type**
Missing release for `PDS4_PROC_1J00_XXXX`

**Describe the issue identified (if applicable)**
While updating all the various `schemaLocations` and `xml-model` to reflect the latest configuration for MSAM labels, I discovered that `ldd-proc` did not have an entry here:
https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml

Where it then told me:
> NOTE: A new version of this Local Data Dictionary was not generated with this version of the PDS4 Information Model. To submit a request the have the LDD generated, please contact the [PDS Operator](mailto:pds-operator@jpl.nasa.gov), or create an issue in the [PDS4 LDD Issues Repository](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues)

**Describe the solution you'd like**
I'd like to start using the latest IM and `validate`, so I'm hoping all the LDDs I run into have updated releases.

**Describe alternatives you've considered**
I could use the latest available ldd-proc built against an older IM, but then I'll have to avoid warnings about mixing IMs (I think)

**PDS4 IM Version**
1.J.0.0

**Need-by Date**
Whenever possible.  I'd like to test out the latest IM and LDDs for the impending MSAM delivery

**Comment by jordanpadams** [comment]
@myche https://github.com/NASA-PDS/operations/issues/387 . once that is posted we will let you know

**Comment by cgobat** [comment]
From @c-suh in [NASA-PDS/operations#387](https://github.com/NASA-PDS/operations/issues/387#issuecomment-1524044983_):

> This LDD has been validated (with v3.2.0) and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml#proc.
