### ISSUE TITLE
[ldd-clipper] Update mission-phase-name value set

### ISSUE THREAD

**Issue by seanhardman** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#247]
**Issue Type**
This is an enhancement for the ldd-clipper mission dictionary.

**Describe the issue identified (if applicable)**
The mission_phase_name value set was initially a placeholder for the actual values. The actual values are now known.

**Describe the solution you'd like**
Please replace the existing value set for mission_phase_name with the following value set:

- Launch
This phase includes include launch, initial acquisition, solar array deployment, establishment of power-positive attitude, and re-establishing telemetry.
- Interplanetary Cruise
This phase starts one day after launch and includes two sub-phases: Inner Cruise and Outer Cruise. Activity includes flight system characterization and navigating to the Mars and Earth gravity assists along with periodic maintenance, calibrations, and navigation activities.
- Arrival
This phase starts three months prior to JOI and includes two sub-phases: Jupiter Approach and Jupiter Orbit Capture. Activities include navigation maneuvers to achieve Jupiter orbit capture.
- Tour
This phase starts eight hours after perijove and includes four sub-phases: Transition to Europa Campaign 1, Europa Campaign 1, Transition to Europa Campaign 2 and Europa Campaign 2. Activities include positioning for and execution of close flybys of Europa, Ganymede and Callisto.
- Disposal
This phase starts 30 days after the last targeted closest approach of Europa. Activities include preparation for impact with Jupiter.

**Describe alternatives you've considered**
N/A

**LDD Dictionary Version**
N/A

**PDS4 IM Version**
N/A

**Need-by Date**
Summer 2023

**Additional context**
N/A

**Comment by thareUSGS** [comment]
updated in PR: https://github.com/pds-data-dictionaries/ldd-clipper/pull/6
