### ISSUE TITLE
[ldd-clipper] Add a new element encounter_id

### ISSUE THREAD

**Issue by seanhardman** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#248]
**Issue Type**
This is an enhancement for the ldd-clipper mission dictionary.

**Describe the issue identified (if applicable)**
Along with orbit_number, the Europa Clipper mission has identified encounter as a meaningful attribute for data identification. 

**Describe the solution you'd like**
Add a new element to the dictionary named _encounter_id_ that does not have a distinct value set but has the following meaning:

_Initial Definition_
- An encounter is from 2 days before a targeted closest approach of a Jovian moon to 2 days before the next targeted closest approach of a Jovian moon. An encounter can span multiple orbits. An orbit will usually include parts of two encounters, but could be wholly contained in a single encounter. Valid values consist of a three-character identifier (e.g., EO1, G02, etc.) where "E01" indicates the first encounter with Europa and "G02" indicates the second encounter with Ganymede and so on. For data collected during gravity assists, there are two special values of "EGA" and "MGA", representing Earth and Mars gravity assists, respectively. There is one more additional special value of "XXX" representing data collected outside of an official encounter. 

_Updated Definition_
- The Playback and Flyby periods together comprise an Encounter, defined as the period of time during the Tour beginning two days before the targeted closest approach of a Jovian moon, and ending two days before the next targeted closest approach of a Jovian moon. While most Jupiter orbits include a targeted flyby, there are some phasing orbits without a targeted flyby; in these cases, an encounter will span more than one orbit. Valid values consist of a three-character identifier (e.g., EO1, G02, etc.) where "E01" indicates the first encounter with Europa and "G02" indicates the second encounter with Ganymede and so on. There is one more additional special value of "XXX" representing data collected during cruise up until the first encounter. 

**Describe alternatives you've considered**
N/A

**LDD Dictionary Version**
N/A

**PDS4 IM Version**
N/A

**Need-by Date**
Summer 2023

**Additional context**
N/A

**Comment by matthewtiscareno** [comment]
I see that there is a "XXX" value for "no encounter," but it seems that it is not used except before JOI and after the final encounter of the prime mission (since an encounter does not end until the beginning of the next encounter).  

This means that a data product might be obtained several orbits after the most recent encounter, having nothing to do with that encounter, but this attribute would mark it as being part of that most recent encounter rather than part of "XXX."  Is that the intention?

**Comment by seanhardman** [comment]
Upon further investigation of the Mission Plan, the original definition of an encounter above is pretty spot on to how the encounters in the plan are defined starting with the first encounter with Ganymede (G00). From that point forward, encounters run back-to-back throughout the tour, including through the campaign transitions (I was mistaken about this at the DAWG). So, Matt's concern above is a reality where an encounter spans multiple orbits. It only happens in a handful of cases and they are mostly in the transitions. There are a couple of encounters in the current plan that span 3 orbits until the next encounter.

I do plan on tweaking the element definition above to point out that "XXX" will be used during cruise up until the first encounter. I also plan to nix the sentence about gravity assist values since they are not officially in the mission plan (at least for now).

**Comment by seanhardman** [comment]
Upon further investigation of the Mission Plan, the original definition of an encounter above is pretty spot on to how the encounters in the plan are defined starting with the first encounter with Ganymede (G00). From that point forward, encounters run back-to-back throughout the tour, including through the campaign transitions (I was mistaken about this at the DAWG). So, Matt's concern above is a reality where an encounter spans multiple orbits. It only happens in a handful of cases and they are mostly in the transitions. There are a couple of encounters in the current plan that span 3 orbits until the next encounter.

I do plan on tweaking the element definition above to point out that "XXX" will be used during cruise up until the first encounter. I also plan to nix the sentence about gravity assist values since they are not officially in the mission plan (at least for now).

**Comment by thareUSGS** [comment]
Please review PR: https://github.com/pds-data-dictionaries/ldd-clipper/pull/6
