### ISSUE TITLE
[ldd-clipper] Update orbit_number description

### ISSUE THREAD

**Issue by seanhardman** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#249]
**Issue Type**
This is an enhancement for the ldd-clipper mission dictionary.

**Describe the issue identified (if applicable)**
The current description for orbit_number is generic. 

**Describe the solution you'd like**
I suggest the a more Clipper-specific description as follows:

- The orbit_number attribute identifies the number of the orbital revolution of the spacecraft around Jupiter. Prior to JOI (i.e., from launch through cruise including gravity assists), the orbit value will be 0. After JOI, starting with the first apojove, the value will increase by 1 with each revolution around Jupiter incrementing at each subsequent apojove.

**Describe alternatives you've considered**
N/A

**LDD Dictionary Version**
N/A

**PDS4 IM Version**
N/A

**Need-by Date**
Summer 2023

**Additional context**
This value is captured within the mission as a 9-bit unsigned integer meaning it has a valid value range of 0 to 511. I am not sure how common this is within other mission dictionaries, but we could put a value range restriction on this element, if desired.

**Comment by thareUSGS** [comment]
We can set a minimum_value = 0 and a maximum_value=511. Seems like this could be limiting for any extended mission. Maybe set a maximum_value=999 or round up to 1000...?

**Comment by thareUSGS** [comment]
Please review: Please review PR: https://github.com/pds-data-dictionaries/ldd-clipper/pull/6

**Comment by seanhardman** [comment]
The orbit is limited by its definition as a 9-bit integer, so 511 is the true maximum value. There are going to be 83 orbits in the prime mission, so I don't believe there are any issues overrunning the maximum value in an extended mission.

**Comment by thareUSGS** [comment]
Okay - set down to 511, PR rebuilding schemas now.
