### ISSUE TITLE
[ldd-img] Add focal_length

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#25]
Shockingly, there is no place for focal_length in the img: dictionary!  Nor is there a particularly obvious place to put it.

So I suggest a new class, Optical_Properties, which would go in both Imaging and Commanded_Parameters:

```
<Optical_Properties>
    <focal_length unit="mm">xxx</>
</>
```

floating point number, cardinality 0-1, no range limits, units of length.  (I don't think negative focal lengths mean anything but I'm not sure I can rule it out...?

Decriptions:

Optical_Properties - Describes properties of the optics used in acquiring the image.

focal_length - Defines the focal length of the optics used in acquiring the image.

If you wanted, you could add f_number also... I don't have a current need for it, but it is an obvious optical property that goes along with focal_length.  I guess the description would be "Defines the f/number for the optics used in acquiring the image.".  Also a float with no range limit.

**Comment by rgdeen** [comment]
Also need a place to put zoom, so add these also to Optical_Properties (modeled directly after focus_position):

zoom_position (card 0-1)
The zoom_position attribute defined, in a camera-specific way, the zoom metric that should be used for geometric processing of the data (e.g. for creating camera models).  This will often be the zoom motor count.

@thareUSGS tagging you here so you don't miss this comment.

**Comment by thareUSGS** [comment]
quote, "modeled directly after focus_position"

@rgdeen I have not seen the need for "focus_position" in this issue or other issue. What is "focus_position"? Is it needed?

**Comment by thareUSGS** [comment]
added in forthcoming IMG v1.8.0.0. And yes IMG feels more complete with focal_length!

**Comment by rgdeen** [comment]
oh good you found it.  I was about to look that up.
