### ISSUE TITLE
[ldd-ebt] Schematron rule contradicts `coordinate_system_equinox` attribute nillability

### ISSUE THREAD

**Issue by cgobat** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#252]
### Issue Type
BUG in Earth-based telescope LDD.

### Describe the issue identified
As [I mentioned here](https://github.com/pds-data-dictionaries/ldd-ebt/pull/9#discussion_r1248328432), there are currently conflicting rules in the EBT LDD that make passing validation impossible. In the LDD, there is a schematron rule which mandates that:

> If ebt:Reference_Frame_Identification/ebt:name = GAPPT or ICRS, then ebt:coordinate_system_equinox must be nill.

which checks the value of `ebt:Reference_Frame_Identification/ebt:name` and whether `ebt:coordinate_system_equinox/@xsi:nil eq 'true'`. However, the `nillable_flag` in the definition of the `coordinate_system_equinox` attribute is set to `false`, which makes this rule impossible to comply with, if the frame name is GAPPT or ICRS.

It seems like some discussion might also be warranted as to whether it is desirable in the first place to consistently have `coordinate_system_equinox` present with `xsi:nil=true` rather than just removing it when not applicable/necessary, but either way, the schematron rule needs to be revised.

### Describe the solution you'd like
Either set `coordinate_system_equinox`'s `nillable_flag` to `true`, or change the rule to not require that it be nilled when the frame is GAPPT or ICRS.

### Describe alternatives you've considered
Other possible solutions:
- remove this rule completely
- change it to mandate that `coordinate_system_equinox` not be present at all when the frame name is ICRS or GAPPT
- change it to define allowable equinox values for these special-case frames (i.e. 2000 for ICRS/J2000)

### LDD Dictionary Version
1.0.0.0 (currently the only published version)

### PDS4 IM Version
All

### Need-by Date
No specific date (but ASAP, since this is a breaking issue).

**Comment by cgobat** [comment]
Hi @benjhirsch—have you had a chance to look at this or the other [issues](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues?q=label%3Aldd-ebt+author%3Acgobat)/[PRs](https://github.com/pds-data-dictionaries/ldd-ebt/pulls/cgobat) I opened?

**Comment by cgobat** [comment]
@benjhirsch&ndash; Would you like me to be the one to propose a fix for this via another PR? I am happy to help if you need it&mdash;just let me know.

**Comment by cgobat** [comment]
@benjhirsch I really think this issue should be addressed before the December release, given that it is a breaking issue. If you'd like, take a look at the [coordsys-epoch-nillability](https://github.com/cgobat/ldd-ebt/tree/coordsys-epoch-nillability) or [coordsys-epoch-schematron](https://github.com/cgobat/ldd-ebt/tree/coordsys-epoch-schematron) branches of [my fork](https://github.com/cgobat/ldd-ebt) for two possible fixes that are both pretty straightforward. In the latter, I just tweaked the [relevant schematron rule](https://github.com/cgobat/ldd-ebt/blob/coordsys-epoch-schematron/src/PDS4_EBT_IngestLDD.xml#L1462) to mandate the *omission* (rather than nillification) of the `coordinate_system_equinox` attribute when the frame used is GAPPT or ICRS. IMO, that is probably the more elegant solution, rather than forcing it to be present but nil in a large number of cases. I will also note that by no means do I claim to be a schematron language expert&mdash;I'm sure someone else (@acraugh?) could make that syntax cleaner. 🙂

Either of these proposals would solve the problem, and they are not even the only possibilities to do so. I am happy to open a PR if you'd like, or you're welcome to use my branch(es) as inspiration if you'd prefer to implement a fix on your own. However, I'd really appreciate some word/communication either way, or at least an update on the resolution timeline if you're already on top of it.

cc @jordanpadams @mkelley

**Comment by mkelley** [comment]
In case it wasn't obvious, Option 1, "remove this rule completely," probably should not be used.

Options 2 and 3, both make sense to me.   The FITS standard v4 says EQUINOX is "not applicable" for GAPPT and ICRS, but does not define how to handle "not applicable" keywords.  Is it too complicated to program both?  For these frames, could we make equinox optional, and if it is present it must be nil?

(also cc @yeqzids)

**Comment by cgobat** [comment]
> an equinox attribute should be required (and nillable for cases where it cannot be determined) for the frames based on systems that require it, and forbidden elsewhere

Right, makes sense to me. I think that would mean we should make _both_ of the changes in the two branches that I linked above: allowing it to be nilled and forbidding its presence when it doesn't apply (in the case of ICRS/GAPPT).

---

> "ICRS" is a reference _system_ definition, not a reference _frame_. It's the reference frame that should be specified.

So should it be "ICRF" (or FK5, or J2000, or...?) instead of "ICRS"? And should the attribute name be `coordinate_frame_equinox` rather than `coordinate_system_equinox`? That change might call for its own issue.

**Comment by cgobat** [comment]
Okay, great! That sounds like a good solution to me. Have those updates been pushed yet to somewhere I could take a look at?

**Comment by acraugh** [comment]
There are actually three different flavors of "ICRF" (ICRF1, ICRF2, and
ICRF3), and those are defined with respect to radio sources rather than
optical (it matters, I assume, when you calculate astrometry - you need a
frame where the reference points are visible in your data), For most PDS
applications at the moment, the difference is immaterial. It only matters
when you get down to precise astrometry - so clearly relevant for surveys,
probably not so much for just about everything else at this point. The
optical frames so far are HCRF, Gaia-CR2 and Gaia-CRF3. Here's a useful
Wikipedia article:
https://en.wikipedia.org/wiki/International_Celestial_Reference_System_and_its_realizations.
An actual astronomer should weigh in, but I know I've seen multiple
informal references to "ICRF". Let me see if IVOA has a vocabulary for
this...

-Anne.

**Comment by acraugh** [comment]
The IVOA vocabulary (http://www.ivoa.net/rdf/refframe) is a mishmash of
systems and frames. They use "ICRS" for this case. So if we want to stick
with "ICRS" we can extend the dictionary when we need to be extremely
precise, and be compatible with at least some related communities in the
meantime.

If there are astronomers listening, some indication of how much you might
care about the difference between 'ICRS" and "ICRF" would be in order right
about now...

-Anne.

**Comment by benjhirsch** [comment]
@cgobat I've created a new branch off the 1.21 release branch that incorporates this change (as well as unrelated other changes). You can take a look here: https://github.com/pds-data-dictionaries/ldd-ebt/tree/lucy+psi_additions_branch

If there are no problems, I'll be merging later today in time for the IM build deadline.

**Comment by mkelley** [comment]
Frame sounds like the right thing, but I don't understand it all enough to say something more useful right now.

**Comment by cgobat** [comment]
Thanks @benjhirsch. Those updates look good to me.

**Comment by cgobat** [comment]
Resolved by pds-data-dictionaries/ldd-ebt#19 and pds-data-dictionaries/ldd-ebt#20
