### ISSUE TITLE
[ldd-vgr] <earth_received_time needs to be nillable>

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#253]
**Issue Type**
Using the LABELS section to the right of this window >>>> , please indicate if this is a BUG or ENHANCEMENT request. If unknown, feel free to leave that blank and the LDD Steward can triage appropriately.

**Describe the issue identified (if applicable)**
Within the VGR mission LDD, earth _recieve_time is a required attribute, but is not nillable. The source VGR data being used in our study does not always contain an earth _recieve_time.  WIthout input data we can not give a reliable time for this attribute.  WE therefore need earth _recieve_time to be nillable.

**Describe the solution you'd like**
Since there are instances in the source data where earth_recieve_time is not given, there is no way we can populate this attribute with a meaningful time.  It would be best to make this attribute nillable.

**Describe alternatives you've considered**
No alternate is proposed

**LDD Dictionary Version**
For bug fixes, note the LDD dictionary version in question.

**PDS4 IM Version**
1.16

**Need-by Date**
July 20

**Additional context**
Add any other context or examples products

**Comment by matthewtiscareno** [comment]
https://github.com/pds-data-dictionaries/ldd-vgr/pull/9
