### ISSUE TITLE
[ldd-vgr] <spacecraft_clock_count_partition should be a integer>

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#255]
**Issue Type**
bug

**Describe the issue identified (if applicable)**

The spacecraft_clock_count_partition is currently described as: 

<     	
<      
<      
---
>     	<xs:pattern value='[0-9]?[0-9]/[0-9]{5}:[0-9]{2}(:[0-9]{3})?'/>
>      <xs:minLength value="1"/>
>      <xs:maxLength value="255"/>

 It really should be an integer, as it is only the partition part of the sclk string.  In the VGR RAV1CUIN instance the partition values can be 0, 1, 2, 3,or 4.

**Describe the solution you'd like**
change spacecraft_clock_count_partition to an integer.

**Describe alternatives you've considered**
none

**LDD Dictionary Version**

**PDS4 IM Version**
1.16

**Need-by Date**
July 20, 2023

**Additional context**
Add any other context or examples products

**Comment by matthewtiscareno** [comment]
https://github.com/pds-data-dictionaries/ldd-vgr/pull/9

**Comment by cgobat** [comment]
Resolved by merge of aforementioned PR.
