### ISSUE TITLE
[ldd-vgr] <Update of enumerated values for edit_mode_id, legacy_label_na_exposure_type, legacy_label_wa_exposure_type>

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#256]
**Issue Type**

**Describe the issue identified (if applicable)**
Please update the enumerated values lists of the following attributes

 edit_mode_id - please add "0:0" to the list  to indicate unknown, as there are instances where this information is not available
 
legacy_label_na_exposure_type - please add "Auto" to the enumeration list for this attribute. "Auto" indicates that the auto-exposure methodology was used to acquire the image.

legacy_label_wa_exposure_type - please add "Auto" to the enumeration list for this attribute. "Auto" indicates that the auto-exposure methodology was used to acquire the image.

**Describe the solution you'd like**
please update the enumeration lists

**Describe alternatives you've considered**
none

**LDD Dictionary Version**
PDS4_VGR_1G00_0100

**PDS4 IM Version**
1.16.

**Need-by Date**
July 22, 2022

**Additional context**
Add any other context or examples products

**Comment by matthewtiscareno** [comment]
If "0:0" signifies information not available from source, rather than signifying a value found in source, then the better solution would be for `edit_mode_id` to be made nillable.  I'll do that.

**Comment by matthewtiscareno** [comment]
I am adding "Auto" as an enumerated value for the two `legacy_label_*a_exposure_type` attributes, with the definition "The auto-exposure methodology was used to acquire the image."  It would be nice to have similar definitions for the other enumerated values, and indeed for many other things in this dictionary that came to me from the RAV1CUIN data providers.  

Just mentioning that that is probably the last conversation we should have before I increment this LDD to v1.0

**Comment by katecrombie** [comment]
My understanding is that the edit_mode_id “0:0” is used in the original data processing pipeline to indicate “unknown” from telemetry.  To conserve the original intent, the data provider will use the  “0:0” notation.  Due to the complicated nature of how this specific attribute is populated in the label, the programming overhead to make this attribute “nillable” is beyond the resources of the data provider.

**Comment by matthewtiscareno** [comment]
@katecrombie:  Okay.  If this value occurs in the source data product, then I propose this definition: "The source data product from which this data product is being migrated contains edit_mode_id = 0:0, indicating that the edit mode of the camera is unknown."

**Comment by katecrombie** [comment]
Perfect!

Sent from my iPhone

On Jul 17, 2023, at 3:39 PM, Matthew Tiscareno ***@***.***> wrote:

﻿
@katecrombie: Okay. If this value occurs in the source data product, then I propose this definition: "The source data product from which this data product is being migrated contains edit_mode_id
External ***@***.******@***.***>)
  Report This Email<https://protection.inkyphishfence.com/report?id=bmV0b3JnZnQzMTA1NTY4L2Nyb21iaWVAaW5kaWdvaW5mb3MuY29tL2I0YmQ5Yzk4NDU3MTM2Y2NkMDdmY2I5Y2MwNWMwODhmLzE2ODk2MzM1NDAuMTE=#key=38d2a89e658b7553a32f315a8cc93760>  FAQ<https://www.godaddy.com/help/report-email-with-advanced-email-security-40813>  GoDaddy Advanced Email Security, Powered by INKY<https://www.inky.com/protection-by-inky>


@katecrombie<https://shared.outlook.inky.com/link?domain=github.com&t=h.eJxNjkEOgyAURK9iWDcCQRBceRX5gP5YodHvyvTuDaZJu5158zIXO_cnGxq2EL2OgfMZaTl9C2Xj60QR9rJ5jOzRsLViOVLZ50RKCq2N5d9-xBxwLphTOe6t73xw4Gyne6kMQBB9Au8AhAZhbeLSWGeU0p1opaz6eOsLYUKYCEs-xt-XCoQK_EXvD1alO0g.MEQCIFMIRh28DgR8zV0mSGOo2v_A-QPm2RMzIK5glBbM5RVXAiBomwZerH7y6d2qhwrRekvIcZ1lyqd4DSjbQl1v0yGXUA>: Okay. If this value occurs in the source data product, then I propose this definition: "The source data product from which this data product is being migrated contains edit_mode_id = 0:0, indicating that the edit mode of the camera is unknown."

**Comment by matthewtiscareno** [comment]
https://github.com/pds-data-dictionaries/ldd-vgr/pull/9
