### ISSUE TITLE
[ldd-vgr] <Enumerated value list additions for edit_mode_id and legacy_label_telemetry_mode >

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#258]
**Issue Type**

**Describe the issue identified (if applicable)**
Please update the enumerated value lists of the following attributes:

edit_mode_id needs the enumerated value of 3:5 added to the list.  I don’t have a definition
legacy_label_telemetry_mode needs the enumerated value of “IM-Q” added to the list.  I don’t have a definition. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**LDD Dictionary Version**
PDS4_VGR_1G00_0500

**PDS4 IM Version**
1.16

**Need-by Date**
Describe a need-by date for these updates and the rationale for that date.

**Additional context**
Add any other context or examples products

**Comment by cgobat** [comment]
Resolved by pds-data-dictionaries/ldd-vgr#10&mdash;it just didn't get linked to close automatically.
