### ISSUE TITLE
[ldd-img_surface] Move PDS4_IMG_SURFACE_1G00_1280.sch online

### ISSUE THREAD

**Issue by mnhughes** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#259]
**Issue Type**
unknown

**Describe the issue identified (if applicable)**
There is an upcoming M2020 release on July 27th. The urn:nasa:pds:mars2020_rover_places:data_maps collection for this release is using this version of the img_surface data dictionary in their labels: PDS4_IMG_SURFACE_1G00_1280.sch, but it doesn't seem to be online yet, giving me validate errors ([https://pds.nasa.gov/pds4/img_surface/v1/PDS4_IMG_SURFACE_1G00_1280.sch].) Is it possible for it to be moved online before the 27th?

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Where possible please include details like:
The updated dictionary to be moved online

**Describe alternatives you've considered**

**LDD Dictionary Version**
PDS4_IMG_SURFACE_1G00_1280

**PDS4 IM Version**
1.16.0.0

**Need-by Date**
7/27/23 (M2020 release 7 goes online)

**Comment by jordanpadams** [comment]
https://github.com/NASA-PDS/operations/issues/417

**Comment by jordanpadams** [comment]
@mnhughes @thareUSGS @Myche thanks to @c-suh this LDD has been posted. Sorry for the delay!
