### ISSUE TITLE
[ldd-msn] Add instrument_clock_stop and instrument_stop_time elements to the Mission_Information Class

### ISSUE THREAD

**Issue by jmafi** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#261]
**Describe the issue identified (if applicable)**
The Mission_Information class currently includes instrument_clock_start and instrument_start_time attributes. There are, however, no corresponding instrument_clock_stop and instrument_stop_time attributes. These are important to include for time ordered data.

**Describe the solution you'd like**
Add an instrument_clock_stop attribute following the instrument_clock_start attribute, and instrument_stop_time following the instrument_start_time attribute.

**Describe alternatives you've considered**
No good alternatives are readily apparent. The current work around is to note the instrument_clock_stop value in the Obeservation_Area/comment, which is physically located a good distance away from the Mission_Information object, which resides in the Discipline_Area.

**LDD Dictionary Version**
N/A

**PDS4 IM Version**
This feature should be implement against the current version of the PDS4 Information Model (1.20.0.0).

**Need-by Date**
This is needed as soon as practicable, but not on an emergency basis. Work is proceeding using the workaround described above.

**Additional context**
Add any other context or examples products

**Comment by cgobat** [comment]
Resolved by pds-data-dictionaries/ldd-msn#31
