### ISSUE TITLE
[ldd-clipper] Add a new element named aid

### ISSUE THREAD

**Issue by seanhardman** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#264]
**Issue Type**
This is an enhancement for the ldd-clipper mission dictionary.

**Describe the issue identified (if applicable)**
The Europa Clipper mission has identified the Accountability Identifier (AID) as a meaningful attribute for data identification.

**Describe the solution you'd like**
Add a new element to the dictionary named _aid_ that does not have a distinct value set but has the following meaning:
* A hexadecimal representation of the Accountability Identifier (AID) which serves as a globally unique identifier across all instruments and mission phases for an observational activity onboard the spacecraft. Data tagged with a given AID is collected into an Accountable Data Product (ADP) on the ground and will result in one or more associated PDS data products in the archive. The AID is a 32-bit unsigned integer which contains three fields: Instrument ID (4-bits), Orbit Number (9-bits) and Data Acquisition ID (19-bits). The hexadecimal string value is prefixed with “0x”.

**Describe alternatives you've considered**
N/A

**LDD Dictionary Version**
N/A

**PDS4 IM Version**
N/A

**Need-by Date**
End of October 2023

**Additional context**
I suggest positioning the _aid_ element following the _encounter_id_ element in the _Observational_Information_ class.

**Comment by thareUSGS** [comment]
updated with latest build (for review): https://github.com/pds-data-dictionaries/ldd-clipper/tree/v1.0.0.0_SUDA/build/development/581d9e61837af9628b9a3e5c6dbe23b612b671ba

**Comment by seanhardman** [comment]
Hey @thareUSGS, I neglected to mention that this element should allow multiple values. Should I just update the description to specify comma-separated values are allowed. For example:

- \<clipper:aid\>"0x30004000", "0x30004001"\</clipper:aid\> or
- \<clipper:aid\>0x30004000, 0x30004001\</clipper:aid\>

Or, should we allow for multiple \<clipper:aid\> entries? What do you think?

**Comment by thareUSGS** [comment]
even though painful, XML really wants to see lists as multiple attributes. That is suppose to help with XML parsing.

So I would recommend, multiple <clipper:aid> entries.

**Comment by thareUSGS** [comment]
Added multiple attributes for "aid" under Observational_Information classes and a separate "aid" under SUDA_Parameters class. Both use the same aid definition.

new build for testing: https://github.com/pds-data-dictionaries/ldd-clipper/tree/v1.0.0.0_SUDA/build/development/4b35348ac56d7234757059929a2929d6738cdc1d

**Comment by seanhardman** [comment]
Thanks @thareUSGS. For the development builds, could you build for versions 1.17 through 1.20 going forward?

**Comment by thareUSGS** [comment]
rebuilt for 1.17 - 1.20:
https://github.com/pds-data-dictionaries/ldd-clipper/tree/v1.0.0.0_SUDA/build/development/b73939653d30276fbd1d875822df240ee2a01a86

Feels like we are getting close to a 1.0 release even thought there are stub attributes for EIS and ETHEMIS.
