### ISSUE TITLE
[ldd-img] HDR section for img

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#27]
Supercam has HDR capability. Strawman label:

```
<High_Dynamic_Range>  (uses <Data_Processing> thus has <active_flag> and <processing_venue> and algo)
   <active_flag>
   <processing_venue>
   <processing_algorithm> - need at least one name to use here
   <hdr_acquisition_mode>Single, Multiple, Piecewise
   <hdr_frame_count>n
   <hdr_clipping_threshold> - need a better definition here
   <High_Dynamic_Range_Exposure>   (repeated n times as needed)
      <exposure_duration>
      <exposure_duration_count>
      <exposure_time_delta> - difference in exposure time from previous frame>
      <pds:Internal_Reference> - points to the separate image used for this slot
```

High_Dynamic_Range would of course go under both the Commanded_Parameters and the non-commanded section, as per usual for the img dictionary.

vicar labels:
HDR_ACQUISITION_MODE = NONE, SINGLE, MULTIPLE, PIECEWISE
HDR_FRAME_COUNT =7
HDR_CLIP_THRESHOLD =800
HDR_EXPOSURE_TIME_DELTA = (val0, val1, val2)

Details of new items:

High_Dynamic_Range - cardinality 0-any. Subclass from <Data_Processing>. We can have more than one potentially because HDR processing could be done both onboard and on the ground, for example.

Specifies parameters related to High Dynamic Range processing, which combines multiple exposures of different lengths into a single product with a greater dynamic range than any of the inputs.

hdr_acquisition_mode - cardinality 1-1.
Specifies how the HDR frames were acquired.

Valid list:
None - No HDR processing
Single - Single exposure
Multiframe - HDR is processed using several separately-acquired images
Piecewise - HDR is processed onboard the camera TBD not a great name...

hdr_frame_count - cardinality 0-1, int, valid 0-any
Specifies the number of frames that go into the HDR product.

hdr_clipping_threshold - cardinality 0-1, int valid 0-any
Specifies the threshold for pixel clipping.

High_Dynamic_Range_Exposure - cardinality 0-any
Specifies parameters for each individual exposure in an HDR image

Children of High_Dynamic_Range_Exposure:

exposure_duration - reuse existing keyword, card 0-1
exposure_duration_count - reuse existing keyword, card 0-1
pds:Internal_Reference - reuse existing class

exposure_time_delta - card 0-1, float, range=-any to +any
Specifies the change in exposure time for this exposure compared to the previous. Should be 0 for the first item in the list.

**Comment by rgdeen** [comment]
Confirmed.  The algorithm name to use is TBD, and the description of Piecewise is also TBD, but we can leave those unspecified for now and do the rest of it.

**Comment by rgdeen** [comment]
@thareUSGS can we please slip High_Dynamic_Range in as an exposed class as well?  I need to use it in the mars2020: supercam mini-header too.

**Comment by thareUSGS** [comment]
@rgdeen and @jordanpadams  for Detector and High_Dynamic_Range_Exposure how about
"data_to_raw_source_product"

**Comment by jordanpadams** [comment]
works for me

**Comment by rgdeen** [comment]
I don't like "raw" because there's no guarantee it'll be a "raw" product, and I'm very anti-those-pds-classifications.  But I'm also not using the lid reference right now anyway, so I can fight that out later if needed.  ;-)
