### ISSUE TITLE
[ldd-img] New autoexposure parameters

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#272]
The CADRE rovers have a different autoexposure algorithm ("ModalAI MSV 2022") with a different set of parameters.  These parameters need to be added to the Autoexposure class.

auto_exposure_target_msv - real, card 0:1
For "ModalAI MSV 2022" this is the setpoint for the algorithm.  The algorithm attempts to make the Mean Sample Value of the image match this value.

auto_exposure_max_delta - real, card 0:1, units of seconds (microseconds, really)
For "ModalAI MSV 2022", this is the maximum exposure change that is allowed across image frames.  Limiting the change makes it more friendly to feature tracking algorithms, in that successive scenes do not vary greatly in brightness.

auto_exposure_alpha - real, card 0:1, data range 0..1
For "ModalAI MSV 2022", this is a weighting parameter that decides whether to prefer exposure changes more or gain changes.  Values closer to 1 mean exposure changes are preferred more.

Need date: 3Q 2024

**Comment by thareUSGS** [comment]
dev version built for review: https://github.com/pds-data-dictionaries/ldd-img/tree/v1900/build/development
