### ISSUE TITLE
[ldd-msn_surface] Additional command parameters

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#273]
Additional attributes for the Command_Execution class to accommodate CADRE.  They all have potential multimission applicability.

expected_command_duration - real, card 0:1, units of time
Expected command execution duration.

command_duration - real, card 0:1, units of time
Actual command execution duration.
(note: I only need expected for cadre, but seems like we should include this one for completeness)

command_sampling_interval - int, card 0:1
For a repeating sequence of events, such as images acquired as a movie, this specifies what interval those events are sampled at.  For example, a value of 1 means every even, 2 means every other event, 4 means every 4th event.

selected_instrument_id - string, card 0:any
Specifies the instrument IDs of instruments selected by this command.

Need date: 3Q 2024

**Comment by thareUSGS** [comment]
ready for review: https://github.com/pds-data-dictionaries/ldd-msn_surface/tree/v1300_release/build
