### ISSUE TITLE
[help-desk] Can't figure out why kplo branch doesn't build

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#276]
@jordanpadams or other here. I can't figure out why the kplo mission dictionary branch isn't building. I see the errors but can't diagnose what it is. help.
https://github.com/pds-data-dictionaries/ldd-kplo/actions/runs/7316941594/job/19932008087

any ideas?

**Comment by thareUSGS** [comment]
Wait this looks like a different error than I originally saw.

"line 12, 26: The value of the attribute logical_identifier must start with either: urn:nasa:pds: or urn:esa:psa: or urn:jaxa:darts: or urn:ros:rssa: or urn:isro:isda:
        1 product validation(s) completed
"

Confused. I don't think I am using any logical_identifier anywhere in the Ingest...

**Comment by thareUSGS** [comment]
I think that was a red herring. I believe this is the issue I had:
https://github.com/pds-data-dictionaries/ldd-kplo/actions/runs/7878623262/job/21497265823

"
Run ls -R /tmp/artifacts
ls: cannot access '/tmp/artifacts': No such file or directory
"

**Comment by thareUSGS** [comment]
@jordanpadams Am I going crazy. I think something is still breaking when I do the merge. Added a version, failed. remove the version and still fails... Maybe permissions?

**Comment by thareUSGS** [comment]
I am good - keep closed. deleted wrong line

**Comment by jordanpadams** [comment]
@thareUSGS great news! I think the pds4_versions file got corrupted somehow (CRLF or maybe it needs a newline at the end?). Either way, glad it is working.
