### ISSUE TITLE
[ldd-img] Addition of data_received or image_received attribute

### ISSUE THREAD

**Issue by CSeyb** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#282]
**Issue Type**
ENHANCEMENT

**Describe the issue identified (if applicable)**
The imaging dictionary currently does not include a Data_Quality_Description Class.
See example of MRO_CTX PDS3 label:
<img width="885" alt="MRO_CTX" src="https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/assets/101605602/3f735b73-a6ad-410e-95a8-b3d2c51585fd">

Per the MRO CTX SIS for ‘DATA_QUALITY_DESCRIPTION’: ‘This field will be set to "OK" if all fragments of the image were received without detected checksum or sequence errors, and "ERROR" otherwise.’ 

**Describe the solution you'd like**
Create the attribute ‘data_received’ to add “OK” or “ERROR” as a value, within the Array_2D class, under 'File_Area_Observational' class. 

Here is the proposed PDS4 label snippet using a "data_received" attribute:

<img width="406" alt="MRO_CTX_data_received" src="https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/assets/101605602/435a3766-2b63-45c2-9de3-c2aff8992c6a">

**Describe alternatives you've considered**
Create the attribute ‘image_received’ to add “OK” or “ERROR” as a value

Here is the proposed PDS4 label snippet using a "image_received" attribute:

<img width="423" alt="MRO_CTX_image_received" src="https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/assets/101605602/ca9f3658-27de-47bc-9b80-01a7bb5982e3">

**LDD Dictionary Version**
img

**PDS4 IM Version**
1.21

**Need-by Date**
Non-urgent

**Additional context**
*Please note – I am making my best guess as to where this would reside, so please advise if this is not appropriate

**Comment by thareUSGS** [comment]
Added data_received under Data_Quality class. Note this is **not** under File_Area_Observational as shown the example screen shots above.

Version ready for review: https://github.com/pds-data-dictionaries/ldd-img/tree/v1910_release/build
