### ISSUE TITLE
[ldd-img] Addition of line_exposure_duration attribute

### ISSUE THREAD

**Issue by CSeyb** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#283]
**Issue Type**
ENHANCEMENT 

**Describe the issue identified (if applicable)**
The imaging dictionary currently does not include a line_exposure_duration attribute.
See example of MRO_CTX PDS3 label:
<img width="425" alt="MRO_CTX_Label example" src="https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/assets/101605602/c5b4ede7-b233-461c-aba1-db815ad12974">

The PDS3 attribute, ‘line_exposure_duration’ differs from ‘exposure_duration’. Per the CTX SIS: 'Per-line exposure duration in units of milliseconds. The time at which a given line was acquired can be determined by multiplying the line exposure time by the number of previous lines and adding it to the image start time. Note that CTX implements downtrack summing by increasing the line time; for example, a 2X2 summed image has an actual line time twice that given by this field.'

**Describe the solution you'd like**
Unsure - Are there other imaging systems that use this property? 

If not, the new attribute line_exposure_duration could be useful in the img: Exposure class. This would also require a Unit of Time option in milliseconds. The definition should specify that this value would be constant across the image.

**Describe alternatives you've considered**
A hefty nuance/comment will be required, as this needs to be included in the label 

**LDD Dictionary Version**
img

**PDS4 IM Version**
1.21 

**Need-by Date**
Non-urgent

**Comment by thareUSGS** [comment]
@CSeyb We can still consider adding in line_exposure_duration to IMG but it should be available to you in the MRO dictionary. HiRISE has the same attribute. And even in PDS3 calls it out under the MRO instrument setting (see below).   So, HiRISE PDS4 labels are still in review, but so far that team is going to use the MRO dictionary for line_exposure_duration attribute.

The description currently says HiRISE, but can be updated to list CTX also:
https://github.com/pds-data-dictionaries/ldd-mro/blob/f261c755bd489087a128709780277b122133af4e/src/PDS4_MRO_IngestLDD.xml#L1908

What do you think?

from HiRISE PDS3 EDR label, e.g.: https://pdsimage2.wr.usgs.gov/Mars_Reconnaissance_Orbiter/HiRISE/EDR/PSP/ORB_003100_003199/PSP_003103_1765/ 

```
/* Instrument settings. */

GROUP = INSTRUMENT_SETTING_PARAMETERS
    MRO:CPMM_NUMBER                 = 6
    MRO:CHANNEL_NUMBER              = 0
    FILTER_NAME                     = "NEAR-INFRARED"
    CENTER_FILTER_WAVELENGTH        = 900 <NANOMETERS>
    BANDWIDTH                       = 200 <NANOMETERS>
    MRO:SCAN_EXPOSURE_DURATION      = 84.5625 <MICROSECONDS>
    MRO:LINE_EXPOSURE_DURATION      = 169.1250 <MICROSECONDS>
    MRO:IMAGE_EXPOSURE_DURATION     = 1707147.7500 <MICROSECONDS>
    MRO:DELTA_LINE_TIMER_COUNT      = 169
    MRO:POWERED_CPMM_FLAG           = (ON, ON, ON, ON, ON, ON, ON, ON, ON, ON,
                                      ON, ON, ON, ON)
    MRO:BINNING                     = 2
    MRO:TDI                         = 128
    MRO:TRIM_LINES                  = 3003
    MRO:FOCUS_POSITION_COUNT        = 2023
    MRO:FELICS_COMPRESSION_FLAG     = YES
    MRO:STIMULATION_LAMP_FLAG       = (OFF, OFF, OFF)
    MRO:HEATER_CONTROL_MODE         = "CLOSED LOOP"
    MRO:HEATER_CONTROL_FLAG         = (ON, ON, ON, ON, ON, ON, ON, ON, ON, ON,
                                      ON, ON, ON, ON)
    MRO:LOOKUP_TABLE_TYPE           = "STORED"
    MRO:LOOKUP_TABLE_MINIMUM        = -9998
    MRO:LOOKUP_TABLE_MAXIMUM        = -9998
    MRO:LOOKUP_TABLE_MEDIAN         = -9998
    MRO:LOOKUP_TABLE_K_VALUE        = -9998
    MRO:LOOKUP_TABLE_NUMBER         = 10

```

**Comment by rgdeen** [comment]
@thareUSGS Is there any chance to "promote" the attributes out of MRO into IMG?  Is it too late?  It seems to be a useful general concept for a pushbroom type camera.

**Comment by thareUSGS** [comment]
pushbroom (aka line scanners) can be fairly particular in how they function. I could see a want to move this up into IMG, but I also worry that every sensor might be a little different. For example, the LROC scanner also needs some "code" along with the line_exposure:
https://github.com/pds-data-dictionaries/ldd-lro/blob/c48270cefc4e5fbb728433234a0e1a5ce3049c16/src/PDS4_LRO_IngestLDD.xml#L1324

And EIS, doesn't need it all.
https://github.com/pds-data-dictionaries/ldd-clipper/blob/6759b4dd2799ea9b95e513dd5714b11ca15dead8/src/PDS4_CLIPPER_IngestLDD.xml#L44

So LROC also uses its mission dictionary for line_exposure_duration. Again, it would be good to move this up, but given the potential for more unique pushbroom attributes, we might be better off leaving them in the mission dictionary.

**Comment by CSeyb** [comment]
@thareUSGS Well, that's embarrassing that I missed that. Still learning!! I think it makes sense to use it from the MRO dictionary but I'll review it with Kate when I meet w/her

**Comment by CSeyb** [comment]
Will use the attribute from the MRO DD

**Comment by rgdeen** [comment]
Revisiting this... is it too late to move them?  The line_exposure_duration can be a computed value, that's no problem.  Multiply it by two for CTX, apply that formula for LROC.  Looks to me like that LROC "code" is just converting from DN (called line_exposure_code) to physical values (line_exposure_duration) and both could go in the IMG label.  For CTX the raw value could go in _code (although it might be be called _count if it's DN) and the x2 value in _duration.
