### ISSUE TITLE
[ldd-msn] Addition of orbit_identifier attribute to MSN DD

### ISSUE THREAD

**Issue by CSeyb** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#286]
**Issue Type**
 ENHANCEMENT

**Describe the issue identified (if applicable)**
Mission-specific DDs, such as JUNO and MRO, include the attribute ‘orbit_identifier’ while the 
mission information commons discipline DD does not. 

Considering that more than 1 mission project may need an attribute to assign an orbit value to (often, but not always a number), 'orbit_identifier' should be created for the msn dd.

See samples of JUNO and MRO_CTX PDS3 labels:

<img width="1174" alt="Sample JUNO and MRO_CTX labels" src="https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/assets/101605602/49132016-a829-4015-977d-405b1422ecee">

Per the JUNO SIS for ‘orbit_number’: ‘The orbit_number element identifies the number of the orbital revolution of the spacecraft around a target body. This value is N/A for cruise images.’

Per the MRO CTX SIS for ‘orbit_number: ‘The orbit number from the start of the mapping phase as defined by the MRO Project.’

Per notes below, '...Cassini orbits are labeled 000, 00A, 00B, 00C, 003, 004, ... then continuing up to 293', so 'identifier' is more useful than 'number'.

**Describe the solution you'd like**
Create the attribute ‘orbit_identifier’ to add to the msn DD.

Here are examples of PDS4 JUNO and MRO CTX  labels using an ‘orbit_identifier’ attribute:

<img width="678" alt="JUNO orbit_identifier example" src="https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/assets/101605602/96ddcbfc-ef30-4e9b-8e8f-3ad137691205">

<img width="662" alt="MRO_CTX orbit_identifier example" src="https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/assets/101605602/4bfd9132-03c6-48f8-a636-ca85d7cbcab0">

**Describe alternatives you've considered**
None

**LDD Dictionary Version**
msn

**PDS4 IM Version**
1.21

**Need-by Date**
Non-urgent

**Comment by matthewtiscareno** [comment]
If the eventual vision would be for this attribute to supplant all similar attributes that are currently in mission-specific LDDs, then please be advised that Cassini orbits are labeled 000, 00A, 00B, 00C, 003, 004, ... then continuing up to 293.

**Comment by rgdeen** [comment]
given the Cassini usage, perhaps it should be `orbit_identifier` as a string rather than number as an int?

**Comment by thareUSGS** [comment]
build version ready to test: https://github.com/pds-data-dictionaries/ldd-msn/tree/v1310_release/build

Note this was added **under** the orbit_identifier to Orbital_Mission class. I can pull this out if needed.
