### ISSUE TITLE
[ldd-msn] Something is wrong with the 1M00 schematron

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#287]
I was validating an M20 label using local copies of the LDDs (version 1G).  Somehow version PDS4_MSN_1M00_1303.sch got into the directory.  Validate failed with a really bizarre error message (see https://github.com/NASA-PDS/validate/issues/958#issuecomment-2221569758).

Further investigation showed that there must be something wrong with the sch file.  I copied it to 1G00_1300 to match the "correct" version, and edited the file to change internal version numbers, and it still failed.  I did the same to the xsd (so that the xsd and sch matched) and still got the same error.

I can't completely rule out that it's something about the 1M LDD that's incompatible with 1G, but I have looked and can't find anything (it would almost have to be some difference in PDS core, but it doesn't obviously use any core facilities that might have changed).  I also don't know what the actual error is, only that it produces a cryptic validate error.

See the Validate bug for the command line and sample data.

**Comment by thareUSGS** [comment]
hmm - [at v1303](https://github.com/pds-data-dictionaries/ldd-msn/commit/125d7753fc16df232309e6aca6b3a867b158ca29#diff-3cfd9e03b6829b89055b9f7dde78f4acf7004f3e6a618cc4578afe951f86b72b) I only see very minor additions.  I will see if I can build locally and see if there is a difference.

**Comment by thareUSGS** [comment]
I'm still not seeing the issue. Can you attach a label for me to test.

**Comment by jordanpadams** [comment]
@thareUSGS per this comment, I think this may be an issue with the way @rgdeen was running this and supplying the schemas/schematrona via command line. This seems to check out when I use the online versions. https://github.com/NASA-PDS/validate/issues/958#issuecomment-2223436195
