### ISSUE TITLE
[help-desk] Seeking to transfer my stewardship of ldd-lt to colleagues

### ISSUE THREAD

**Issue by dvpolitte** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#289]
My responsibilities related to Lunar Trailblazer at the PDS Geosciences Node have been transferred to two of my colleagues, and I'm seeking to transfer my stewardship of [its LDD repo](https://github.com/pds-data-dictionaries/ldd-lt). And while we're here, I'd suggest that we also remove from the list a few of my former colleagues at GEO who are now retired.

The stewardship team in question: https://github.com/orgs/pds-data-dictionaries/teams/lt-ldd-stewardship-team

Please remove these members:
- @dvpolitte (me): no longer involved in GEO's archival of LT
- @edguinness: retired
- @sslavney: retired

Please add these members:
- @mnhughes
- @alknight-wustl 

Please let me know if I should file an issue somewhere else instead; I was not able to find specific instructions for how to request a transfer of stewardship.

**Comment by jordanpadams** [comment]
@dvpolitte done. I also gave @mnhughes and @alknight-wustl Maintainer access to that team for any future updates.
