### ISSUE TITLE
[ldd-img] autoexposure additions for supercam

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#29]
Need several attributes added for the supercam autoexposure algorithm, under img:Autoexposure:

auto_exposure_lower_threshold - card 0-1, int any
Specifies the lower threshold DN value for which a specified number of pixels is permitted to exceed. The auto_exposure_lower_limit defines the number of pixels allowed to exceed this threshold.

auto_exposure_lower_limit - card 0-1, int 0-any
Specifies the maximum number of pixels that are allowed to be below the lower threshold defined by auto_exposure_lower_limit.

auto_exposure_upper_threshold - card 0-1, int any
Specifies the upper threshold DN value for which a specified number of pixels is permitted to exceed. The auto_exposure_upper_limit defines the number of pixels allowed to exceed this threshold.

auto_exposure_upper_limit - card 0-1, int 0-any
Specifies the maximum number of pixels that are allowed to be above the upper threshold defined by auto_exposure_upper_limit.

auto_exposure_roi_lines - card 0-1, int 0-any
Specifies the number of lines in the autoexposure region of interest.

auto_exposure_roi_samples - card 0-1 int 0-any
Specifies the number of samples in the autoexposure region of interest.

auto_exposure_roi_first_line - card 0-1 int 0-any
Specifies the (1-based) starting line for the autoexposure region of interest.

auto_exposure_roi_first_sample - card 0-1 int 0-any
Specifies the (1-based) starting sample for the autoexposure region of interest.

**Comment by thareUSGS** [comment]
added for forthcoming IMG v1.8.0.0
