### ISSUE TITLE
[ldd-img] Rolling shutter support

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#300]
There is currently no common place to capture whether a framing camera uses a global or rolling shutter, or the parameters of the rolling shutter.  This is important in terms of describing artifacts.  Request is from Michael Aye of JANUS JUICE.

Need date: unknown

Proposal:

Introduce six new attributes to img:Detector.  They are:

shutter_type: ascii string, cardinality 0:1
Valid: Global, Rolling
Specifies the type of shutter the camera uses.  "Global" exposes all pixels at the same time, so the image captures a consistent view of moving objects.  "Rolling" scans across the scene, meaning each pixel is exposed at a slightly different time, which can introduce distortions for rapidly moving objects.  This is generally a property of the camera itself and does not vary from frame to frame.

readout_direction_pixel: ascii string, cardinality 0:1
Valid: "Left to Right", "Right to Left", "Top to Bottom", "Bottom to Top"
Specifies the direction in which adjacent pixels are read from a camera.  Generally important only for rolling shutters, but can be specified for any camera if desired.  Directions are relative to the image as displayed (thus there may be an interaction with disp:Display_Direction).

readout_direction_line: ascii string, cardinality 0:1
Valid: "Left to Right", "Right to Left", "Top to Bottom", "Bottom to Top"
Specifies the direction in which lines are read from a camera.  Generally important only for rolling shutters, but can be specified for any camera if desired.  Directions are relative to the image as displayed (thus there may be an interaction with disp:Display_Direction).

pixel_readout_time: real, cardinality 0:1
Unit: Time
Specifies the time between readout of each adjacent pixel.  It is the time from the start of one pixel to the start of the next.  Generally important only for rolling shutters, but can be specified for any camera if desired.

line_readout_time: real, cardinality 0:1
Unit: Time
Specifies the time between readout of the same pixel on adjacent lines.  It it the time from the start of one pixel to the start of the same pixel on the following line.  Generally important only for rolling shutters, but can be specified for any camera if desired.

frame_readout_time: real, cardinality 0:1
Unit: Time
Specifies the time it takes for readout of the entire camera frame.  This is the time from readout of the first pixel to readout of the last and does not include exposure time or other delays.

**Comment by rgdeen** [comment]
from Michael Aye in OpenPlanetary slack:
this looks good to me, thanks. i forwarded it to my team as well.

**Comment by thareUSGS** [comment]
@rgdeen - almost feels like there should be a Shutter class, then a Pushbroom class, etc. under Detector class. thoughts?

**Comment by rgdeen** [comment]
Yeah that makes sense.  They are all related to Shutter, so put them all in a Shutter class that's a (optional) child of Detector.  Many of the values make sense mostly for rolling shutter, but if someone wants to use them for global they can.

Also... I'm not a big fan of required elements but it seems like shutter_type is a candidate for being required (in which case add Unknown as an escape hatch).  Required only if the Shutter class is used, of course.

**Comment by thareUSGS** [comment]
new Shutter class and attributes are ready for review:
https://github.com/pds-data-dictionaries/ldd-img/tree/v1910_release/build/release/1.22.0.0
