### ISSUE TITLE
[ldd-geom]  More valid values for geom:Coordinate_Space_Indexed/geom:coordinate_space_frame_type

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#303]
**Issue Type**
Enhancement

**Describe the issue identified (if applicable)**
The geom:Coordinate_Space_Indexed/geom:coordinate_space_frame_type should never have been a validated enum due to the wide variety of frames across different missions.  But, it is, so here we are again with new frames to add.  This time for MSL.

I can't rule out coming across more of these in the future, because it is nearly impossible to find the complete list of all enumerations.  But MSAM should have flushed most of them out already.

**Describe the solution you'd like**
Please add two new valid values:

SAM1 - Sample Analysis at Mars frame 1 (used by MSL)
SAM2 - Sample Analysis at Mars frame 2 (used by MSL)

**Describe alternatives you've considered**
There really isn't any, other than ignoring the validation errors or leaving off the keyword entirely.

**LDD Dictionary Version**
current

**PDS4 IM Version**
1J (1.19)

**Need-by Date**
ASAP.  The project has already generated labels (a handful will need to be regenerated with a new LDD version for this fix) and they are planning to deliver within the month.

**Additional context**
Please let me know what the version *will be* as soon as it is known, even if it's not yet released.  Thanks.

**Comment by thareUSGS** [comment]
Hmm - coordinate_space_frame_type is almost up to 100 enumerations! Seems like it is time to let it be free text. That change is backwards compatible and will remove a ton of lines from Geom LDD. I guess a list of the original enums could be maintained as examples I guess.

**Comment by rgdeen** [comment]
I would be okay with de-enumerating them.  This is a perfect test case for the mission-specific validation I'm working on (to be presented at the upcoming PMC).

**Comment by alknight-wustl** [comment]
@rgdeen @thareUSGS I've submitted a pull request with @mnhughes to add those two values to the Geometry Data Dictionary. I believe the new version should be PDS4_GEOM_1M00_1980. Would you both please review the pull request, and let me know if you spot any issues with it?

Also, we're looking into the possibility of making coordinate_space_frame_type be free text in the future. Do you think we should look into changing the rule that "*_type" attributes must be enumerated?

**Comment by matthewtiscareno** [comment]
It seems like perhaps it was a mistake for this attribute to be named as a `type`, since it seems that its values are not really types of frames but names of specific frames.  Is that correct? 

To put it another way: Is this an attribute that people will want to search on, particularly across different data sets?  If so, then maintaining it as a `type` and keeping a lid on the number of values would seem to be the way to go. 

If this information is not desired for search, then perhaps we should establish a new attribute called `coordinate_space_frame_name` and use that going forward?  

We could deprecate `coordinate_space_frame_type` for future versions of the LDD, but we could also use the Registry to link the old attribute in old labels to the new ones.

**Comment by rgdeen** [comment]
@alknight-wustl thanks I'll take a look.  In terms of the broader questions... this is an excellent case for the mission-specific validation of multimission keywords idea that I'll be presenting at the PMC in a couple weeks.  De-enumerating it in the meantime would be fine with me (doing so will allow the mission-specific validation).  Or, leave it alone until y'all see that and see if it gets adopted.  In terms of `_type` needing enumeration, is that actually a hard rule or is it a recommendation/best-practice?  Where is that documented?  In any case, we can't change the keyword name at this point.

**Comment by rgdeen** [comment]
@alknight-wustl from the PR it looks like the auto-dev-build was triggered, but it's version 1.9.7?  Instead of .8?  Am I looking in the wrong place?  The changes look fine from an inspection point of view; want to try actually validating once we get xsd/sch.  Thanks.

**Comment by alknight-wustl** [comment]
@rgdeen If I'm not mistaken, I believe the auto-generated LDDs for the pull request should be [version 1.9.8.0](https://github.com/pds-data-dictionaries/ldd-geom/tree/update-alk/build/development/ac2d8200f2e8528bae4849c9aa8dceb9a29a2768/1.19.0.0). Thank you very much for reviewing the changes; I'll go ahead and merge the pull request since the update looks okay to you!

Also, I think @mnhughes and I will hold off on de-enumerating *_type for the time being as you suggested.

**Comment by rgdeen** [comment]
Yes I see them on the build/development dir in GitHub, but my understanding is that there's an extra step to "publish" them, so they're available as https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1J00_1980.sch where validate can find them.

**Comment by alknight-wustl** [comment]
@rgdeen I've just contacted EN to get them published to the PDS website, so Validate can access them. I'll let you know as soon as they're available!

**Comment by alknight-wustl** [comment]
@rgdeen It sounds like EN is about to start working on the upcoming scheduled build for LDDs in the next few weeks, and sticking to the PDS4 build schedule is generally preferred over initiating off-nominal releases whenever possible. However, I think there are ways to direct Validate to a local location to access the files without having to modify any labels by using an [XML Catalog](https://nasa-pds.github.io/validate/operate/index.html#using-an-xml-catalog). Do you think this would be a viable solution that would enable the products to be validated before they're published with the next scheduled build?

**Comment by rgdeen** [comment]
Hmmm... I haven't heard of that catalog before... will have to check it out.  Could certainly do it by just downloading the xsd/sch but that means modifying the validate command line in the pipeline.  Anyway, we can deal with that, it's just a PITA.  Any idea when the build is due out?  I'll have to compare that against their data release date, as the LDD has to be published before data release.  Thanks.

**Comment by alknight-wustl** [comment]
@rgdeen I believe the next build is scheduled for December 5th. However, I don't think the 1J (1.19) version will be updated with the build as I understand it. I've [submitted a request](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/307) for that version to be published. Could you please review the issue description and let me know if the details look correct? Thanks!

**Comment by alknight-wustl** [comment]
@rgdeen The PDS4_GEOM_1J00_1980 version is now available [here](https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml#geom)!

**Comment by rgdeen** [comment]
Thanks!
