### ISSUE TITLE
[ldd-geom] New release request for PDS4_GEOM_1J00_1980

### ISSUE THREAD

**Issue by alknight-wustl** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#307]
**Issue Type**
Unknown

**Describe the issue identified (if applicable)**
There is an upcoming MSL release that needs this version of the Geometry LDD: PDS4_GEOM_1J00_1980. This version contains additional enumerated values that are needed for MSL SAM. Is it possible for it to be moved online ASAP?

**Describe the solution you'd like**
New PDS4_GEOM_1J00_1980

**Describe alternatives you've considered**
No alternatives that I'm aware of 

**LDD Dictionary Version**
PDS4_GEOM_1J00_1980

**PDS4 IM Version**
1.19.0.0

**Need-by Date**
ASAP. Next MSL release is on 12/6/2024. 

**Additional context**

**Comment by jordanpadams** [comment]
@alknight-wustl we actually prefer these requests to go to the [operations repo](https://github.com/NASA-PDS/operations/issues/new/choose). I moved this over there.

**Comment by jordanpadams** [comment]
https://github.com/NASA-PDS/operations/issues/570
