### ISSUE TITLE
Issues for ldd-cassini are not like those for other LDDs

### ISSUE THREAD

**Issue by matthewtiscareno** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#312]
Hey @jordanpadams, why am I able to create an issue in this repo?  For other LDDs, there isn't even an Issues tab, and instead issues are created at the [PDS4-LDD-Issue-Repo](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues) where there are a bunch of tags to indicate the LDD to which the issue applies.  However, at that location, there is no tag for ldd-cassini.  Is this something to fix?

**Comment by jordanpadams** [comment]
New issue template created in this repo. Disabling the tickets on the ldd-cassini repo

**Comment by jordanpadams** [comment]
@matthewtiscareno 

> the former ldd-cassini issues https://github.com/pds-data-dictionaries/ldd-cassini/issues/1, https://github.com/pds-data-dictionaries/ldd-cassini/issues/2, https://github.com/pds-data-dictionaries/ldd-cassini/issues/3, https://github.com/pds-data-dictionaries/ldd-cassini/issues/6, https://github.com/pds-data-dictionaries/ldd-cassini/issues/7, https://github.com/pds-data-dictionaries/ldd-cassini/issues/8, https://github.com/pds-data-dictionaries/ldd-cassini/issues/9, and https://github.com/pds-data-dictionaries/ldd-cassini/issues/11 now are redirects to ldd-cassini pull requests with the same number, which is not necessarily correct,

This is actually expected. Pull requests are basically just a specialized Issue in GitHub system terms, so the numbers increment together.

> the former ldd-cassini issue [4](https://github.com/pds-data-dictionaries/ldd-cassini/issues/4) is now a 404 page not found, and

I reopened the tickets and migrated this over to the issues repo

**Comment by matthewtiscareno** [comment]
> This is actually expected. Pull requests are basically just a specialized Issue in GitHub system terms, so the numbers increment together.

Ah, that explains something we were wondering about yesterday. 

> I reopened the tickets and migrated this over to the issues repo

Great.  The former ldd-cassini issue [4](https://github.com/pds-data-dictionaries/ldd-cassini/issues/4) is now a redirect to (closed) PDS4-LDD-Issue-Repo issue [313](https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/313).
