### ISSUE TITLE
[ldd-msn_surface] OBSERVATION_REQUEST_PARMS for msn_surface

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#37]
SOURCE_ID
Command_Execution.command_source_id - string, no valids

Specifies where the command that triggered acquisition of this data came from. This may be "GROUND" for ground commanding, or the name of a flight software module that initiated the request.

MSL nuance: The field is based on the value for IMAGE_ID and the mappings are per convention; there is no guarantee that the mappings are used in this way during operations.

-- MSL value is "GND", convert this to "GROUND" in the template. Otherwise, pass the value through unchanged. Looking at the list of values it seems like one that should be kept in all caps rather than Initialcaps (i.e. don't change the case).

Note that we look ONLY at OBSERVATION_REQUEST_PARMS in Velocity for this one. The SOURCE_ID in the other request fields is ignored.

**Comment by thareUSGS** [comment]
command_source_id was previously added and included with Command_Execution but using a slightly different definition. Is that enough or do you want it updated with this one?

```
  <DD_Attribute>
    <name>command_source_id</name>
    <version_id>1.0</version_id>
    <local_identifier>command_source_id</local_identifier>
    <nillable_flag>false</nillable_flag>
    <submitter_name>Jordan Padams</submitter_name>
    <definition> The command_source_id attribute specifies the flight software element that was the
      source of a particular command. </definition>
    <DD_Value_Domain>
      <enumeration_flag>false</enumeration_flag>
      <value_data_type>ASCII_Short_String_Collapsed</value_data_type>
      <minimum_characters>1</minimum_characters>
      <maximum_characters>255</maximum_characters>
      <unit_of_measure_type>Units_of_None</unit_of_measure_type>
    </DD_Value_Domain>
  </DD_Attribute>
```

**Comment by rgdeen** [comment]
I think we should update the definition to include the ground case, as it's actually the most common IIRC.
