### ISSUE TITLE
[ldd-img_surface] start_image_id et al

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#41]
Add to img_surface:Image_Identifiers:

start_image_id - card 0-1, int, any
Specifies the starting image ID for some operation.
MSL nuance: For ChemCam RMI, this is the commanded image start in case the SRAM on the ChemCam Mast Unit goes bad.

observation_number - card 0-1, int, any
Identifies which observation of many this data product pertains to.
M20 nuance: For SuperCam RMI, this refers to the number of the point in a raster activity.

parameter_table_number - card 0-1, int, any
Specifies which table of parameters to use. Tables are necessarily defined in a mission- and instrument-specific manner.
M20 nuance: For SuperCam RMI, tables hold values of parameters such as gains, internal CMS HDR settings, and internal CMOS parameters.

The last one is a bit weak but I don't have any place better to put it.

Also from the SCAM perspective these are commanded parameters so they should go in an instance of Image_Identifiers within Commanded_Parameters in the img_surface main class.

start_image_id is MSL-only, as it turns out, but let's add it anyway.  I think there are potential MSSS camera cases for it too.

**Comment by thareUSGS** [comment]
implemented in forthcoming v1.2.0.0
