### ISSUE TITLE
[ldd-img_surface] Commanded_Parameters for img_surface

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#42]
We now have TWO commanded items for img_surface, making it worth creating a Commanded_Parameters class (along the lines of the one in img, and the one proposed for msn_surface).
```
<Commanded_Parameters>
    <ops_instrument_key>
    <image_id>
    <image_id_2>
```
Note that this supercedes the request for command_instrument_key in issue pds-data-dictionaries/ldd-img_surface#2.  Since we need Commanded_Parameters for image_id anyway, we might as well combine them all using the CP paradigm.

Note also that image_id_2 is not needed in CP now but since you'll be adding it to the non-commanded one anyway, might as well add it to CP also.

The image_id's are both cardinality 0-1.  The ops_instrument_key is cardinality 0-any (consistent with issue pds-data-dictionaries/ldd-img_surface#1).

**Comment by thareUSGS** [comment]
I think I have this defined as needed but I need a definition for Commanded_Parameters. Any comments, e.g. occurrences?

```
  <!-- Commanded_Parameters class defintion    -->
  <DD_Class>
    <name>Commanded_Parameters</name>
    <version_id>1.0</version_id>
    <local_identifier>Commanded_Parameters</local_identifier>
    <submitter_name>Trent Hare</submitter_name>
    <definition>The Commanded_Parameters class specifies TBD</definition>
    <abstract_flag>false</abstract_flag>
    <DD_Association>
      <identifier_reference>Instrument_Information</identifier_reference>
      <reference_type>component_of</reference_type>
      <minimum_occurrences>0</minimum_occurrences>
      <maximum_occurrences>1</maximum_occurrences>
    </DD_Association>
    <DD_Association>
      <identifier_reference>Image_Identifiers</identifier_reference>
      <reference_type>component_of</reference_type>
      <minimum_occurrences>0</minimum_occurrences>
      <maximum_occurrences>1</maximum_occurrences>
    </DD_Association>
  </DD_Class>
  <!-- End of Commanded_Parameters class defintion    -->
```

**Comment by rgdeen** [comment]
So taking straight from the Commanded_Parameters in img:

The Commanded_Parameters class contains
        attributes used to identify or describe the commands sent to a
        spacecraft to perform one or more actions resulting in the
        acquisition of the current data product. These are distinct from
        similar values in the root Surface_Imaging class which indicate the
        state of the image as acquired.

Re: occurrences, I'm pretty much always a 0-1 kind of guy...  ;-)
