### ISSUE TITLE
[ldd-img_surface] image_id_2

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#43]
Add image_id_2 as a sibling of image_id in img_surface:Image_Identifiers.

Can use the same description as image_id, or just say something as simple as "Second image_id for missions with two, same use cases".

VICAR keyword is, surprisingly, IMAGE_ID_2.

Background: back when we thought we'd handle EECAM tile reconstruction by supplying the size of the recon via image_id, it was determined that we needed more bits than the 32 in image_id. So the FSW added image_id_2 as an additional 32-bit field. We are no longer doing tile reconstruction in this way, so image_id_2 may or may not be used... but it should be captured in case it is.

**Comment by thareUSGS** [comment]
Added image_id_2 for forthcoming v 1.2.0.0
