### ISSUE TITLE
[ldd-img_surface] command_instrument_key

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#44]
Add command_instrument_key to img_surface:Instrument_Information (parallel to ops_instrument_key).

The command_instrument_key specifies the identifier or key for the instrument that was commanded to take the observation. It may differ from ops_instrument_key in that the command may apply to the stereo camera as a pair (e.g. MCAMZ_BOTH) rather than a specific left or right eye.

Comes from OBSERVATION_REQUEST_PARMS.COMMAND_INSTRUMENT_ID.

One could legitimately ask, why is this not in Imaging. Well, same reason ops_instrument_key isn't there - Cristina had a major objection to it being there, which is why it was moved to img_surface. I didn't agree, but was okay with the compromise. But since we're here now, it makes sense to keep the command id in the same place. Also, there's no particularly good place to put it in img:Commanded_Parameters.

**Comment by thareUSGS** [comment]
heading issue #42 - closing this
