### ISSUE TITLE
[ldd-img_surface] Cardinality of ops_instrument_key

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#45]
ops_instrument_key (aka the short name we actually use to identify the instruments, without having to go through the whole context product thing) under Instrument_Information has cardinality 0:1.  But for mosaics, there is more than one possible instrument... thus it would be helpful to have more than one key.  Currently we're getting from the template:

```
<img_surface:Instrument_Information>
   <img_surface:instrument_type>IMAGING CAMERA</img_surface:instrument_type>
   <img_surface:ops_instrument_key>(MAST_LEFT,NAV_LEFT_B)</img_surface:ops_instrument_key>
</img_surface:Instrument_Information>
```

but I think this would be better as:

```
<img_surface:Instrument_Information>
   <img_surface:instrument_type>IMAGING CAMERA</img_surface:instrument_type>
   <img_surface:ops_instrument_key>MAST_LEFT</img_surface:ops_instrument_key>
   <img_surface:ops_instrument_key>NAV_LEFT_B</img_surface:ops_instrument_key>
</img_surface:Instrument_Information>
```

Sound okay?

**Comment by thareUSGS** [comment]
implemented img_surface:ops_instrument_key as unbounded in forthcoming 1.2.0.0 version
