### ISSUE TITLE
[ldd-msn] Add instrument_clock_start and instrument_start_time

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#48]
Add to <Mission_Information>:

<instrument_clock_start>  The value of the clock returned by the
      instrument at the beginning of the observation.  This may differ from
      the spacecraft clock due to several factors such as clock drift, or
      differences in definition of start time (for example, spacecraft clock
      might be when an image was commanded, but instrument clock might be
      after autoexpoure or autofocus processes).

<instrument_start_time>  This is instrument_clock_start converted to UTC.

Both are cardinality 0:1

**Comment by rgdeen** [comment]
Modification to definition to be more expansive (to accommodate the helicopter use case, which has its own time unrelated to sclk (based on linux time, actually), which is also converted to sclk):

The value of the clock returned by the instrument at the beginning of the observation. This may differ from the spacecraft clock due to several factors such as clock drift, or differences in definition of start time (for example, spacecraft clock might be when an image was commanded, but instrument clock might be after autoexpoure or autofocus processes), or differences in the time epoch between the instrument and the main spacecraft.

**Comment by thareUSGS** [comment]
This was previously updated so just changed the definition to allow for helicopter use. It does have a recommended formation rule but it doesn't need to be followed if the helicopter uses something else. Really any ASCII_Short_String_Collapsed can be used up to 255 characters.

`      <value_data_type>ASCII_Short_String_Collapsed</value_data_type>
      <formation_rule>Value should be of the form: nnnnnnnnn.mmm</formation_rule>
      <minimum_characters>1</minimum_characters>
      <maximum_characters>255</maximum_characters>
`
