### ISSUE TITLE
[ldd-img] atmospheric_opacity

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#50]
Under <Radiometric_Correction> add:

<atmospheric_opacity> The atmospheric opacity (tau) value used in radiometric correction.
<atmospheric_opacity_reference> The atmospheric opacity (tau) target value to which the image was corrected.

These are both floats, card 0-1.  No specific range.

**Comment by thareUSGS** [comment]
added at IMG v1.7.1.0
