### ISSUE TITLE
[ldd-img] Add Image_Compression_Segments to JPEG_Paramters

### ISSUE THREAD

**Issue by katecrombie** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#53]
**Issue Type**
ENHANCEMENT

**Describe the issue identified (if applicable)**
Image_Compression_Segments within the JPEG_Paramters class are not available.  The compression segments are needed for the PHOENIX mission SSI/RAC labels. 

**Describe the solution you'd like**
Please add Image_Compression_Segments to the JPEG_Paramters class.

**Describe alternatives you've considered**
none

**LDD Dictionary Version**
For bug fixes, note the LDD dictionary version in question.

**PDS4 IM Version**
Please implement as soon as possible.

**Need-by Date**
09/01/2020 - We would like to complete the migration of the PHONEIX RAC/SSI images by 9/30/2020

**Additional context**
Add any other context or examples products

**Comment by thareUSGS** [comment]
Added "Image_Compression_Segment" (no "s") under JPEG_Parameters for forthcoming IMG v1.8.0.0
