### ISSUE TITLE
[ldd-img] bad pixel support

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#56]
Okay I thought this was already in the DD but apparently not.

In img:Detector please add:

bad_pixel_replacement_flag - boolean, card 0-1
Specifies whether or not bad pixel replacement processing was requested or completed.

bad_pixel_replacement_table_id - int, card 0-1
Specifies the table used to replace bad pixels.  A bad pixel table typically lists the location of each bad pixel on a detector.  The specific table used is mission-specific.

Note that I could totally see more bad pixel stuff in the future, like actually listing the bad pixels... but we'll do that when/if we need it.

(I originally said just _table but we might want to use that to define the actual table in the future, thus _table_id).

**Comment by thareUSGS** [comment]
added at IMG v1.7.3.0. for forthcoming IMG v1.8.0.0 renamed attribute bad_pixel_replacement_table to bad_pixel_replacement_table_id and updated definition
