### ISSUE TITLE
[ldd-img_surface] camera_model_serial_number

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#74]
Add a new field to img_surface:Instrument_Information :

camera_model_serial_number: string, card 0-1
Specifies the manufacturer's serial number for the camera for which the camera model was derived. This should match instrument_serial_number in most cases; generally speaking a mismatch should only occur during testing/development.

**Comment by thareUSGS** [comment]
closed per branch  v1200 
https://github.com/pds-data-dictionaries/ldd-img_surface/tree/v1200

pull a release next. Auto-build makes a release but need to build with GEOM. Thus might need to run lddtool locally and release. see related: #77

**Comment by rgdeen** [comment]
@thareUSGS I downloaded version 1200 and this item isn't there....?

But then again the LDD shows it was last modified 7 days ago so that doesn't make sense...?

**Comment by rgdeen** [comment]
okay I found it in the 1200 branch... but it didn't get delivered to master?
