### ISSUE TITLE
link to IMG during auto-build

### ISSUE THREAD

**Issue by thareUSGS** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#77]
This dev. build seems to have built, but it doesn't include IMG (shown here): 
https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/blob/v1000/build/development/5fa0821755df0c1bf23f72b8718cae695c442389/1.14.0.0/PDS4_MSSS_CAM_MH_1E00_1000.xsd

Is there a method in the lddtool command used on GitHub to also list the IMG dependency? See lddtool command below.

shown here, IMG needs to be listed at top ar built with a local LDDtool install: 
https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/blob/v1000/build/release/1.E.0.0_1.0.0.0/PDS4_MSSS_CAM_MH_1E00_1000.xsd

Also my local LDDtool run set a IMG version to "1E00_1600" instead of "1E00_1800" (as shown in the above link, line 25, but commented out for temporary inclusion for the latest build on github).

local lddtool run (with IMG dictionary):
`lddtool -lpsnJ PDS4_IMG_IngestLDD.xml PDS4_MSSS_CAM_MH_IngestLDD.xml`

**Comment by jordanpadams** [comment]
@thareUSGS is this still a problem? or can we close this out?

**Comment by jordanpadams** [comment]
@thareUSGS closing this since i believe this has been fixed
