### ISSUE TITLE
[ldd-img] Commanded_Parameters last

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#79]
Can we keep Commanded_Parameters the last thing under Imaging?  It was, but many of the new items slipped in underneath it.  It really doesn't make logical sense to have CP occur in the middle of Imaging, when CP itself can have pretty much anything that Imaging can.

Hopefully we haven't really published this before, or not long enough that anyone might have used it, so the move is simple.

Another option is to change Imaging itself from a xs:sequence (requiring ordering) to something else where order doesn't matter  It was initially alphabetical except for Instrument_State and then Commanded_Parameters being at the bottom.  If you want to keep ordering, can we sort the new classes in the right place alphabetically?

**Comment by thareUSGS** [comment]
@rgdeen I did move Instrument_State and Commanded_Parameters to the last spot. But I think we should try to not enforce ordering here. To me for most of these classes, I don't see why order would matter...

@jordanpadams Question. In a LDD Ingest file how do you set a class so order doesn't matter.

**Comment by jordanpadams** [comment]
@thareUSGS I think you can try using a choice and use the number of occurrences to enable more than one? just a guess... if not, i would ping Ron Joyner. he knows how to do all things XSD / SCH

**Comment by thareUSGS** [comment]
@rgdeen and @jordanpadams I was just informed that "PDS elected to ONLY allow enforced ordering of all elements (e.g., classes & attributes within classes)".  So alphabetical it is for IMG except for Instrument_State and Commanded_Parameters.

I guess should all the other classes we have been working on do the same (e.g. msss_cam_mh)?

**Comment by rgdeen** [comment]
Wow.  Okay.  (had to read that 3 times to parse it ;-)  )

I've been adapting the velocity ordering to what's in the DD, with a few exceptions like this where I thought it mattered. I would hope that the ordering in Commanded_Parameters matches that in Imaging, and that the ordering in msss_cam_mh generally matches too.  If you want to reorder anything else (today or tomorrow) that's fine, just let me know so I can change to match.

I guess we need to be a little more careful with that going forward!

**Comment by rgdeen** [comment]
(changing the ordering in velocity is pretty easy but it needs to be done now before this all gets released, so just let me know).

**Comment by thareUSGS** [comment]
update in v1800 branch. A few other new (at v1.8.0.0 classes have re-sorted attributes.
