### ISSUE TITLE
[ldd-msn_surface] telemetry_source_start_time format

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#80]
telemetry_source_start_time is actually defined as a DOY value, can that be added as a valid format per the .sch ?

e.g.

2020-079T13:29:08.12846948Z

YYYY-DDDT...

**Comment by edguinness** [comment]
Probably easier to change the data_type to ASCII_Date_Time_DOY_UTC. Currently it is ASCII_Date_Time_YMD_UTC.

**Comment by rgdeen** [comment]
I think that could work.  At least until someone else needs it in MM-DD format.  ;-)

**Comment by thareUSGS** [comment]
@rgdeen @edguinness thanks for the tip for DOY but what is the formation rule for DOY?

      <formation_rule>yyyy-dddThh:mm:ss.sssZ</formation_rule>

for comparison:
      <value_data_type>ASCII_Date_Time_YMD_UTC</value_data_type>
      <formation_rule>yyyy-mm-ddThh:mm:ss.sssZ</formation_rule>

**Comment by rgdeen** [comment]
I think it's exactly the same except ddd instead of mm-dd.

Oh, and we have 6 digits of fractional seconds.

Example:
2021-071T19:01:05.71336938Z

**Comment by edguinness** [comment]
Here is the formation rule from the current information model:

 

	
YYYY-DOYTHH:MM:SS.SSSSSSZ <https://pds.jpl.nasa.gov/datastandards/documents/im/current/index_1E00.html#value_pds_ascii_date_time_doy_utc_pds_formation_rule_yyyy-doythh:mm:ss.ssssssz>

**Comment by thareUSGS** [comment]
thanks for the link. Googling lead me no where to find that formation rule - I figured it existed. Need to stop trusting Google search so much.
