### ISSUE TITLE
[ldd-msss_cam_mh] element order

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#81]
for consistency, the MSSS_Camera_Mini_Header should have the same ordering as Imaging.  If you sort Imaging per issue #79, then that means moving Sampling between Optical_Filter and Subframe.  (Instrument_State should stay last).

Also, all the other img: references use ref="img:xxx"  but Sampling has name="xxx", is this a problem?  (I don't care, it just looks weird to be different).

**Comment by thareUSGS** [comment]
fixed this issue for img:Sample inside IMG but I need to have EN push a new IMG release to the website. Unfortunately, IMG is building locally but the auto-build on GitHub is failing now. I have a ticket in to @jordanpadams .

I tried get order corrected. @rgdeen I could use another set of eyes to see if I got it right or am missing anything (in v1000 branch here):
https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/blob/v1000/build/release/1.E.0.0_1.0.0.0/PDS4_MSSS_CAM_MH_1E00_1000.xsd

**Comment by rgdeen** [comment]
class ordering in the top-level looks good.

Best test is validate, so push it in...
