### ISSUE TITLE
[ldd-disp] Dictionary is all messed up

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#82]
Something very bad happened to disp.

There is no top-level element exposed.  So nothing can be used at all!

The Local_Internal_Reference is defined but is no longer a child of Display_Settings (or any other class!) like it used to be.

**Comment by jordanpadams** [comment]
@rgdeen the ingestLDD was developed for this after the schema / schematron was already built. we should maybe grab and InSight or some other label that specifies a DISP area, and use that as a regression test here

**Comment by thareUSGS** [comment]
I haven't tried to touch (update) DISP yet. @rgdeen Are you talking to the official release or the GitHub version? Currently the GitHub version hasn't been sync'd to current release. But if the current PDS release is bad (PDS4_DISP_1B00) - that is not good. Planning to tackle with related ticket #68

**Comment by rgdeen** [comment]
1B00 works, although there's no JSON file (which I also need).  It was the dev version here (based on 1E00) that is broken.
I worry thought that the LDD Ingest file might be messed up, it's not just a sync thing... although I don't know for sure.

**Comment by jordanpadams** [comment]
@rgdeen @thareUSGS see regression test thought above :-) .

**Comment by rgdeen** [comment]
sounds like a plan.  But that's also a larger issue than just here... regression test generally would be a nice thing.  But probably a long range thing?

**Comment by thareUSGS** [comment]
I figured getting the LDD DISP ingest file working was just not a sync issue but a complete check-up (oil, filter and brake fluids replaced).

**Comment by rgdeen** [comment]
Likely.

We can limp by on 1B00 for the PR if necessary (if I can get the JSON) so this would be a lower priority I think... still important, just not mandatory for the PR.

**Comment by thareUSGS** [comment]
development 1E00 ready for testing.
https://github.com/pds-data-dictionaries/ldd-disp/tree/master/build/development/46ba0e84c7f370714bd1adc0b81a44f60a711866
