### ISSUE TITLE
[ldd-img] Special_Point name

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#86]
So I expected Special_Point to use <name>, but apparently it wants <img:name>.  Is that because in the xsd it says:

```
      <xs:element name="name" type="pds:name" minOccurs="0" maxOccurs="1"> </xs:element>
```
instead of using <xs:ref> ?

Same for description.  I don't really care if you change this or not, just let me know if you do.  Mostly I just wanted to point it out as an oddity, to make sure it's expected (and not a Validate bug).

**Comment by thareUSGS** [comment]
@rgdeen to "use ," what? Not sure what I need to fix.

I copied the use of name, description from classes like LED_Illumination_Source

**Comment by rgdeen** [comment]
oh my the formatting went south.  To use "name" (specifically, pds:name without the prefix) rather than "img:name".

If you're okay with img:name here you can just close this, I just wanted to point it out.

**Comment by thareUSGS** [comment]
lets see if we can live we this. we can change if it doesn't work.
