### ISSUE TITLE
[ldd-img] focus_mode valids

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#89]
The "valid" list in the img:focus_mode description was not meant to be prescriptive but rather just examples.  I'm personally more comfortable with not having a valid list here but if you want to expand it to include all of these you can.  Let's please go with UPPER_CASE_UNDERSCORE styles for the value here because with the multiple words it would be really difficult to convert them to MixedCase.  So the valid list really is as follows (trying to make the definitions mostly multimission):

(SuperCam)
NO_FOCUS - Doesn't move focus
MANUAL - Positions focus based on other parameters (focus_distance for SuperCam)
BASELINE - Uses SuperCam laser to find optimal focus position
AF_OFFSET - Applies offset from last autofocus solution

(Mastcam-Z and SHERLOC)
AUTOFOCUS - Autofocus mode
EARLY_TERMINATION - Stops the autofocus before the full number of steps has been reached if a peak is detected
THRESHOLD - Causes the focus to not be changed if a test image is within a certain percentage of the last image taken with autofocus (5% for Mastcam-Z and SHERLOC)
EARLY_TERMINATION_AND_THRESHOLD - combination of both

Note that the current keyword also defines Relative and ZStack.  Can we change those to RELATIVE and ZSTACK for consistency?  I don't have definitions.

The other option is just to take off the validation values...?

**Comment by thareUSGS** [comment]
make focus_mode free text in branch v1800. I left example use case as a comment in the class.
