### ISSUE TITLE
[ldd-img] Illumination

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#90]
The cardinality of LED_Illumination_Source should be 0-any not 1-any.  We have a case where we have a name only, e.g.

```
        <img:Illumination>
          <name>Flood_Light</name>
        </img:Illumination>
```

**Comment by thareUSGS** [comment]
resolves:
https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/90
