### ISSUE TITLE
[ldd-img] segment_count check

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#92]
Got this validation error:
```
      ERROR  [error.label.schematron]   line 1427, 34: IMG:error:icer_comprs_segment_check: img:ICER_Parameters/img:segment_count must match the number of img:Image_Compression_Segment classes.
```
That's fine... except in this case there are NO ICS classes, because we have no additional information.  Before, we had an ICS with nothing but the segment number, which seemed silly.  So please update this check to say the number of ICS classes must match segment_count OR be 0.

(if you can't do that, then just remove the check).

**Comment by thareUSGS** [comment]
I update the rule, hopefully this works:
```
<rule_test>(count(img:Image_Compression_Segment) = img:segment_count) or (count(img:Image_Compression_Segment) = 0)</rule_test>
```
