### ISSUE TITLE
[ldd-img] Compression segments for LOCO

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#97]
Apparently LOCO has compression segments just like ICER.  So, add a:
```
      <xs:element name="Image_Compression_Segment" type="img:Image_Compression_Segment" minOccurs="0" maxOccurs="unbounded"> </xs:element>
```
to LOCO_Parameters just like there is for ICER_Parameters.

**Comment by thareUSGS** [comment]
added Added Image_Compression_Segment class to LOCO_Parameters at v1.8.1.0
