### ISSUE TITLE
[ldd-img] illumination name

### ISSUE THREAD

**Issue by rgdeen** [pds-data-dictionaries/PDS4-LDD-Issue-Repo#98]
We should have an optional name under Illumination.  For the PIXL use case, we have a name for the overall thing and then a name for each LED source, e.g.

        <img:Illumination>
          <name>Flood_Light</name>
          <img:LED_Illumination_Source>
            <name>R1R3R5</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 735</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>R2R4R6</name>
 ...

so we need that first <name> directly under Illumination.

**Comment by thareUSGS** [comment]
@rgdeen I added name under Illumination. But in your example I see
        <img:led_state>OFF</img:led_state>

which is not available in LED_Illumination_Source class. does that need to be in there. If so I assume allowable valuaes are just "ON" or "OFF". -- or free text?

**Comment by rgdeen** [comment]
whoops!!   Good catch!!  Yes please.  I think ON/OFF are fine here, we can always add more states if needed later (but that would be other missions).

**Comment by thareUSGS** [comment]
@rgdeen argh so
`        <img:led_wavelength unit="nm"> 735</img:led_wavelength>`
is not there but 
<illumination_wavelength> is

**Comment by rgdeen** [comment]
oh, also I had the velocity folks change it to img:name instead of just name so keep using the name like you have is okay instead of switching to ref

**Comment by rgdeen** [comment]
okay we can change it to illumination_wavelength, no prob

**Comment by rgdeen** [comment]
although you should add units to that

**Comment by rgdeen** [comment]
(nvm the units are already there)

**Comment by thareUSGS** [comment]
it is set to "pds.name". Does that mean you need to use pds.name or does just "name" work for that? Not sure myself.

also unit of length can be added.

**Comment by thareUSGS** [comment]
Also to be consistent should we use 
<illumination_state>  On/Off  (Is that case use okay which aligns with other permissible values)

**Comment by rgdeen** [comment]
if you do this, as currently in LED:
```
      <xs:element name="name" type="pds:name" minOccurs="0" maxOccurs="1"> </xs:element>
```
then you end up using img:name.  Thats the .xsd, not sure how that looks in the LDD.  If it ends up with reference, like this:
```
      <xs:element ref="pds:Local_Internal_Reference" minOccurs="0" maxOccurs="1"> </xs:element>
```
then you don't have the img: prefix.

**Comment by rgdeen** [comment]
In case I missed something else, here's the whole section:
```
        <img:Illumination>
          <img:name>Flood_Light</img:name>
          <img:LED_Illumination_Source>
            <name>R1R3R5</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 735</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>R2R4R6</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 735</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>G1</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 530</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>G2</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 530</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>G3</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 530</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>G4</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 530</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>G5</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 530</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>G6</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 530</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>B1B4</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 450</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>B2B5</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 450</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>B3B6</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 450</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>UV1UV4</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 385</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>UV2UV5</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 385</img:led_wavelength>
          </img:LED_Illumination_Source>
          <img:LED_Illumination_Source>
            <name>UV3UV6</name>
            <img:led_state>OFF</img:led_state>
            <img:led_wavelength unit="nm"> 385</img:led_wavelength>
          </img:LED_Illumination_Source>
        </img:Illumination>
```

**Comment by rgdeen** [comment]
I'm okay with illumination_state if you want to change that, and On/Off.

**Comment by rgdeen** [comment]
that way you can reuse those in other illumination types in the future

**Comment by rgdeen** [comment]
so...
```
        <img:Illumination>
          <img:name>Flood_Light</img:name>
          <img:LED_Illumination_Source>
            <img:name>R1R3R5</img:name>
            <img:illumination_state>OFF</img:illumination_state>
            <img:illumination_wavelength unit="nm"> 735</img:illumination_wavelength>
          </img:LED_Illumination_Source>
```

**Comment by rgdeen** [comment]
(updated to Off above)

**Comment by thareUSGS** [comment]
but really - subtle case difference - you got it
`            <img:illumination_state>Off</img:illumination_state>`

**Comment by rgdeen** [comment]
yep

**Comment by rgdeen** [comment]
btw, pushing hard to find any of these that require DD changes today... getting close to the end.  Can't rule out more but we've squished most of them at this point, and have successfully validated some of the products.

**Comment by thareUSGS** [comment]
I might be off for a couple hours but will check back tonight/tomorrow. pushing v1.8.1.0 to GitHub now

**Comment by thareUSGS** [comment]
@rgdeen dev. build for testing v1810
https://github.com/pds-data-dictionaries/ldd-img/tree/master/build/development/1caab992a4d21a3f1bfcf54f4cbcbed8029a33b5/1.14.0.0

**Comment by rgdeen** [comment]
thanks!
